// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlevisionapi.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the GoogleVisionAPI module

	public static java.lang.String getGoogleVisionApi_Endpoint()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GoogleVisionAPI.GoogleVisionApi_Endpoint");
	}
}