// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appmain.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AppMain module
	public static void aCo_IncidentPhoto(IContext context, masterdata.proxies.IncidentReportPhoto _incidentReportPhoto)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IncidentReportPhoto", _incidentReportPhoto == null ? null : _incidentReportPhoto.getMendixObject());
		Core.microflowCall("AppMain.ACo_IncidentPhoto").withParams(params).execute(context);
	}
	public static void aCT_Assign_ServicePerson(IContext context, masterdata.proxies.ServiceEngineer _servicePerson, masterdata.proxies.Incident _incidentReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ServicePerson", _servicePerson == null ? null : _servicePerson.getMendixObject());
		params.put("IncidentReport", _incidentReport == null ? null : _incidentReport.getMendixObject());
		Core.microflowCall("AppMain.ACT_Assign_ServicePerson").withParams(params).execute(context);
	}
	public static void aCT_Customer_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.ACT_Customer_New").withParams(params).execute(context);
	}
	public static void aCT_Customer_Save(IContext context, administration.proxies.AccountPasswordData _accountPasswordData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AccountPasswordData", _accountPasswordData == null ? null : _accountPasswordData.getMendixObject());
		Core.microflowCall("AppMain.ACT_Customer_Save").withParams(params).execute(context);
	}
	public static void aCT_DownloadBillDOCX(IContext context, masterdata.proxies.Bill _bill)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bill", _bill == null ? null : _bill.getMendixObject());
		Core.microflowCall("AppMain.ACT_DownloadBillDOCX").withParams(params).execute(context);
	}
	public static void aCT_DownloadBillPDF(IContext context, masterdata.proxies.Bill _bills)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bills", _bills == null ? null : _bills.getMendixObject());
		Core.microflowCall("AppMain.ACT_DownloadBillPDF").withParams(params).execute(context);
	}
	public static void aCT_GenerateDownloads(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.ACT_GenerateDownloads").withParams(params).execute(context);
	}
	public static void aCT_IncidentReportPhoto_Download(IContext context, masterdata.proxies.IncidentReportPhoto _incidentReportPhoto)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IncidentReportPhoto", _incidentReportPhoto == null ? null : _incidentReportPhoto.getMendixObject());
		Core.microflowCall("AppMain.ACT_IncidentReportPhoto_Download").withParams(params).execute(context);
	}
	public static void aCT_MyIncident_New(IContext context, masterdata.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("AppMain.ACT_MyIncident_New").withParams(params).execute(context);
	}
	public static void aCT_MyIncident_New_NoImage(IContext context, masterdata.proxies.UserData _userData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserData", _userData == null ? null : _userData.getMendixObject());
		Core.microflowCall("AppMain.ACT_MyIncident_New_NoImage").withParams(params).execute(context);
	}
	public static void aCT_MyIncident_Save(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		Core.microflowCall("AppMain.ACT_MyIncident_Save").withParams(params).execute(context);
	}
	public static void aCT_MyIncident_Save_NoImage(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		Core.microflowCall("AppMain.ACT_MyIncident_Save_NoImage").withParams(params).execute(context);
	}
	public static void aCT_NewBill(IContext context, masterdata.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("AppMain.ACT_NewBill").withParams(params).execute(context);
	}
	public static void aCT_ResetBills(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.ACT_ResetBills").withParams(params).execute(context);
	}
	public static void aCT_ResetForATS(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.ACT_ResetForATS").withParams(params).execute(context);
	}
	public static void aCT_SaveCustomerDetails(IContext context, masterdata.proxies.Customer _customer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		Core.microflowCall("AppMain.ACT_SaveCustomerDetails").withParams(params).execute(context);
	}
	public static void aCT_UnassignEngineer(IContext context, masterdata.proxies.ServiceEngineer _serviceEngineer, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ServiceEngineer", _serviceEngineer == null ? null : _serviceEngineer.getMendixObject());
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		Core.microflowCall("AppMain.ACT_UnassignEngineer").withParams(params).execute(context);
	}
	public static boolean aCT_UpdateBillsWithoutDownloads(IContext context, appmain.proxies.BillsWithoutDownloads _billsWithoutDownloads)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BillsWithoutDownloads", _billsWithoutDownloads == null ? null : _billsWithoutDownloads.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AppMain.ACT_UpdateBillsWithoutDownloads").withParams(params).execute(context);
	}
	public static void aSU_EnsureCart(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.ASU_EnsureCart").withParams(params).execute(context);
	}
	public static java.util.List<iot.proxies.Scene> createScene(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("AppMain.CreateScene").withParams(params).execute(context);
		java.util.List<iot.proxies.Scene> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(iot.proxies.Scene.initialize(context, obj));
		}
		return result;
	}
	public static appmain.proxies.BillsWithoutDownloads dS_CreateBillsWithoutDownloads(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_CreateBillsWithoutDownloads").withParams(params).execute(context);
		return result == null ? null : appmain.proxies.BillsWithoutDownloads.initialize(context, result);
	}
	public static masterdata.proxies.Customer dS_Customer_GetCurrent(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_Customer_GetCurrent").withParams(params).execute(context);
		return result == null ? null : masterdata.proxies.Customer.initialize(context, result);
	}
	public static administration.proxies.Account dS_GetCurrentAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_GetCurrentAccount").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static void dS_GetUserData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.DS_GetUserData").withParams(params).execute(context);
	}
	public static masterdata.proxies.IncidentReportPhoto dS_IncidentPhoto(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_IncidentPhoto").withParams(params).execute(context);
		return result == null ? null : masterdata.proxies.IncidentReportPhoto.initialize(context, result);
	}
	public static java.util.List<masterdata.proxies.Map> dS_MapList(IContext context, masterdata.proxies.Incident _incidentReport)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IncidentReport", _incidentReport == null ? null : _incidentReport.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("AppMain.DS_MapList").withParams(params).execute(context);
		java.util.List<masterdata.proxies.Map> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(masterdata.proxies.Map.initialize(context, obj));
		}
		return result;
	}
	public static masterdata.proxies.Incident dS_NextInspection(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_NextInspection").withParams(params).execute(context);
		return result == null ? null : masterdata.proxies.Incident.initialize(context, result);
	}
	public static java.util.List<sap_integration.proxies.Product> dS_Products(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("AppMain.DS_Products").withParams(params).execute(context);
		java.util.List<sap_integration.proxies.Product> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(sap_integration.proxies.Product.initialize(context, obj));
		}
		return result;
	}
	public static salesforce_connector.proxies.Contact dS_Salesforce_ContactInfo(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.DS_Salesforce_ContactInfo").withParams(params).execute(context);
		return result == null ? null : salesforce_connector.proxies.Contact.initialize(context, result);
	}
	public static java.util.List<workflowessentialsprivate.proxies.UserTaskTimeLine> dS_UserTaskTimeline_2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("AppMain.DS_UserTaskTimeline_2").withParams(params).execute(context);
		java.util.List<workflowessentialsprivate.proxies.UserTaskTimeLine> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(workflowessentialsprivate.proxies.UserTaskTimeLine.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<sap_integration.proxies.Product> formatProducts(IContext context, java.util.List<sap_integration.proxies.Product> _productList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_productList = null;
		if (_productList != null)
		{
			listparam_productList = new java.util.ArrayList<>();
			for (sap_integration.proxies.Product obj : _productList)
				listparam_productList.add(obj.getMendixObject());
		}
		params.put("ProductList", listparam_productList);

		java.util.List<IMendixObject> objs = Core.microflowCall("AppMain.FormatProducts").withParams(params).execute(context);
		java.util.List<sap_integration.proxies.Product> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(sap_integration.proxies.Product.initialize(context, obj));
		}
		return result;
	}
	public static appmain.proxies.SensorValue iNV_GetSensorValues(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.INV_GetSensorValues").withParams(params).execute(context);
		return result == null ? null : appmain.proxies.SensorValue.initialize(context, result);
	}
	public static sap_integration.proxies.ProductRoot rS_GetProducts(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AppMain.RS_GetProducts").withParams(params).execute(context);
		return result == null ? null : sap_integration.proxies.ProductRoot.initialize(context, result);
	}
	public static void sUB_GenerateAllBillDownloads(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AppMain.SUB_GenerateAllBillDownloads").withParams(params).execute(context);
	}
	public static void sUB_GenerateBillDOCX(IContext context, masterdata.proxies.Bill _bill)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bill", _bill == null ? null : _bill.getMendixObject());
		Core.microflowCall("AppMain.SUB_GenerateBillDOCX").withParams(params).execute(context);
	}
	public static void sUB_GenerateBillPDF(IContext context, masterdata.proxies.Bill _bill)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Bill", _bill == null ? null : _bill.getMendixObject());
		Core.microflowCall("AppMain.SUB_GenerateBillPDF").withParams(params).execute(context);
	}
	public static void sUB_Incident_Submit(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		Core.microflowCall("AppMain.SUB_Incident_Submit").withParams(params).execute(context);
	}
	public static boolean sUB_IncidentReportPhoto_Validation(IContext context, java.util.List<masterdata.proxies.IncidentReportPhoto> _incidentReportPhotoList)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_incidentReportPhotoList = null;
		if (_incidentReportPhotoList != null)
		{
			listparam_incidentReportPhotoList = new java.util.ArrayList<>();
			for (masterdata.proxies.IncidentReportPhoto obj : _incidentReportPhotoList)
				listparam_incidentReportPhotoList.add(obj.getMendixObject());
		}
		params.put("IncidentReportPhotoList", listparam_incidentReportPhotoList);

		return (java.lang.Boolean) Core.microflowCall("AppMain.SUB_IncidentReportPhoto_Validation").withParams(params).execute(context);
	}
	public static void sUB_JAVA_callReverse(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("AppMain.SUB_JAVA_callReverse").withParams(params).execute(context);
	}
	public static void sUB_NewCase(IContext context, masterdata.proxies.Customer _customer, java.lang.String _description, masterdata.proxies.DeviceType _deviceType, java.lang.String _address, java.lang.String _image, java.math.BigDecimal _longitude, java.math.BigDecimal _latitude, masterdata.proxies.Priority _priority)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Customer", _customer == null ? null : _customer.getMendixObject());
		params.put("Description", _description);
		params.put("DeviceType", _deviceType == null ? null : _deviceType.name());
		params.put("Address", _address);
		params.put("Image", _image);
		params.put("Longitude", _longitude);
		params.put("Latitude", _latitude);
		params.put("Priority", _priority == null ? null : _priority.name());
		Core.microflowCall("AppMain.SUB_NewCase").withParams(params).execute(context);
	}
	public static boolean sUB_ServiceEngineer(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("AppMain.SUB_ServiceEngineer").withParams(params).execute(context);
	}
	public static void sUB_StartWorkflow(IContext context, masterdata.proxies.Incident _incident)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Incident", _incident == null ? null : _incident.getMendixObject());
		Core.microflowCall("AppMain.SUB_StartWorkflow").withParams(params).execute(context);
	}
	public static masterdata.proxies.IncidentReportStatus sUB_WorkflowStatus_Value(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.lang.String result = (java.lang.String) Core.microflowCall("AppMain.SUB_WorkflowStatus_Value").withParams(params).execute(context);
		return result == null ? null : masterdata.proxies.IncidentReportStatus.valueOf(result);
	}
}