// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class APNSToken extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.APNSToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TeamId("TeamId"),
		KeyId("KeyId"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		APNSSettings_APNSToken("PushNotifications.APNSSettings_APNSToken");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public APNSToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.APNSToken"));
	}

	protected APNSToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aPNSTokenMendixObject)
	{
		super(context, aPNSTokenMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.APNSToken", aPNSTokenMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.APNSToken");
	}

	/**
	 * @deprecated Use 'APNSToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static pushnotifications.proxies.APNSToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.APNSToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.APNSToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.APNSToken(context, mendixObject);
	}

	public static pushnotifications.proxies.APNSToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.APNSToken.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.APNSToken> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pushnotifications.proxies.APNSToken> result = new java.util.ArrayList<pushnotifications.proxies.APNSToken>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PushNotifications.APNSToken" + xpathConstraint))
			result.add(pushnotifications.proxies.APNSToken.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of TeamId
	 */
	public final java.lang.String getTeamId()
	{
		return getTeamId(getContext());
	}

	/**
	 * @param context
	 * @return value of TeamId
	 */
	public final java.lang.String getTeamId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TeamId.toString());
	}

	/**
	 * Set value of TeamId
	 * @param teamid
	 */
	public final void setTeamId(java.lang.String teamid)
	{
		setTeamId(getContext(), teamid);
	}

	/**
	 * Set value of TeamId
	 * @param context
	 * @param teamid
	 */
	public final void setTeamId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String teamid)
	{
		getMendixObject().setValue(context, MemberNames.TeamId.toString(), teamid);
	}

	/**
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId()
	{
		return getKeyId(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyId
	 */
	public final java.lang.String getKeyId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KeyId.toString());
	}

	/**
	 * Set value of KeyId
	 * @param keyid
	 */
	public final void setKeyId(java.lang.String keyid)
	{
		setKeyId(getContext(), keyid);
	}

	/**
	 * Set value of KeyId
	 * @param context
	 * @param keyid
	 */
	public final void setKeyId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String keyid)
	{
		getMendixObject().setValue(context, MemberNames.KeyId.toString(), keyid);
	}

	/**
	 * @return value of APNSSettings_APNSToken
	 */
	public final pushnotifications.proxies.APNSSettings getAPNSSettings_APNSToken() throws com.mendix.core.CoreException
	{
		return getAPNSSettings_APNSToken(getContext());
	}

	/**
	 * @param context
	 * @return value of APNSSettings_APNSToken
	 */
	public final pushnotifications.proxies.APNSSettings getAPNSSettings_APNSToken(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.APNSSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.APNSSettings_APNSToken.toString());
		if (identifier != null)
			result = pushnotifications.proxies.APNSSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of APNSSettings_APNSToken
	 * @param apnssettings_apnstoken
	 */
	public final void setAPNSSettings_APNSToken(pushnotifications.proxies.APNSSettings apnssettings_apnstoken)
	{
		setAPNSSettings_APNSToken(getContext(), apnssettings_apnstoken);
	}

	/**
	 * Set value of APNSSettings_APNSToken
	 * @param context
	 * @param apnssettings_apnstoken
	 */
	public final void setAPNSSettings_APNSToken(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.APNSSettings apnssettings_apnstoken)
	{
		if (apnssettings_apnstoken == null)
			getMendixObject().setValue(context, MemberNames.APNSSettings_APNSToken.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.APNSSettings_APNSToken.toString(), apnssettings_apnstoken.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.APNSToken that = (pushnotifications.proxies.APNSToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.APNSToken";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
