// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class FCMPrivateKey extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.FCMPrivateKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FCMSettings_FCMPrivateKey("PushNotifications.FCMSettings_FCMPrivateKey");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FCMPrivateKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.FCMPrivateKey"));
	}

	protected FCMPrivateKey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fCMPrivateKeyMendixObject)
	{
		super(context, fCMPrivateKeyMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.FCMPrivateKey", fCMPrivateKeyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.FCMPrivateKey");
	}

	/**
	 * @deprecated Use 'FCMPrivateKey.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static pushnotifications.proxies.FCMPrivateKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.FCMPrivateKey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.FCMPrivateKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.FCMPrivateKey(context, mendixObject);
	}

	public static pushnotifications.proxies.FCMPrivateKey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.FCMPrivateKey.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.FCMPrivateKey> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pushnotifications.proxies.FCMPrivateKey> result = new java.util.ArrayList<pushnotifications.proxies.FCMPrivateKey>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PushNotifications.FCMPrivateKey" + xpathConstraint))
			result.add(pushnotifications.proxies.FCMPrivateKey.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FCMSettings_FCMPrivateKey
	 */
	public final pushnotifications.proxies.FCMSettings getFCMSettings_FCMPrivateKey() throws com.mendix.core.CoreException
	{
		return getFCMSettings_FCMPrivateKey(getContext());
	}

	/**
	 * @param context
	 * @return value of FCMSettings_FCMPrivateKey
	 */
	public final pushnotifications.proxies.FCMSettings getFCMSettings_FCMPrivateKey(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.FCMSettings result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FCMSettings_FCMPrivateKey.toString());
		if (identifier != null)
			result = pushnotifications.proxies.FCMSettings.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FCMSettings_FCMPrivateKey
	 * @param fcmsettings_fcmprivatekey
	 */
	public final void setFCMSettings_FCMPrivateKey(pushnotifications.proxies.FCMSettings fcmsettings_fcmprivatekey)
	{
		setFCMSettings_FCMPrivateKey(getContext(), fcmsettings_fcmprivatekey);
	}

	/**
	 * Set value of FCMSettings_FCMPrivateKey
	 * @param context
	 * @param fcmsettings_fcmprivatekey
	 */
	public final void setFCMSettings_FCMPrivateKey(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.FCMSettings fcmsettings_fcmprivatekey)
	{
		if (fcmsettings_fcmprivatekey == null)
			getMendixObject().setValue(context, MemberNames.FCMSettings_FCMPrivateKey.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FCMSettings_FCMPrivateKey.toString(), fcmsettings_fcmprivatekey.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.FCMPrivateKey that = (pushnotifications.proxies.FCMPrivateKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.FCMPrivateKey";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
