// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class MessageView
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.MessageView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MessageView_MessageData("PushNotifications.MessageView_MessageData"),
		MessageView_Device("PushNotifications.MessageView_Device");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessageView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.MessageView"));
	}

	protected MessageView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageViewMendixObject)
	{
		if (messageViewMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.MessageView", messageViewMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.MessageView");

		this.messageViewMendixObject = messageViewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MessageView.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static pushnotifications.proxies.MessageView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.MessageView.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.MessageView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.MessageView(context, mendixObject);
	}

	public static pushnotifications.proxies.MessageView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.MessageView.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MessageView_MessageData
	 */
	public final pushnotifications.proxies.MessageData getMessageView_MessageData() throws com.mendix.core.CoreException
	{
		return getMessageView_MessageData(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageView_MessageData
	 */
	public final pushnotifications.proxies.MessageData getMessageView_MessageData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.MessageData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MessageView_MessageData.toString());
		if (identifier != null)
			result = pushnotifications.proxies.MessageData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MessageView_MessageData
	 * @param messageview_messagedata
	 */
	public final void setMessageView_MessageData(pushnotifications.proxies.MessageData messageview_messagedata)
	{
		setMessageView_MessageData(getContext(), messageview_messagedata);
	}

	/**
	 * Set value of MessageView_MessageData
	 * @param context
	 * @param messageview_messagedata
	 */
	public final void setMessageView_MessageData(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.MessageData messageview_messagedata)
	{
		if (messageview_messagedata == null)
			getMendixObject().setValue(context, MemberNames.MessageView_MessageData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MessageView_MessageData.toString(), messageview_messagedata.getMendixObject().getId());
	}

	/**
	 * @return value of MessageView_Device
	 */
	public final java.util.List<pushnotifications.proxies.Device> getMessageView_Device() throws com.mendix.core.CoreException
	{
		return getMessageView_Device(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageView_Device
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<pushnotifications.proxies.Device> getMessageView_Device(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<pushnotifications.proxies.Device> result = new java.util.ArrayList<pushnotifications.proxies.Device>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MessageView_Device.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(pushnotifications.proxies.Device.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MessageView_Device
	 * @param messageview_device
	 */
	public final void setMessageView_Device(java.util.List<pushnotifications.proxies.Device> messageview_device)
	{
		setMessageView_Device(getContext(), messageview_device);
	}

	/**
	 * Set value of MessageView_Device
	 * @param context
	 * @param messageview_device
	 */
	public final void setMessageView_Device(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<pushnotifications.proxies.Device> messageview_device)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (pushnotifications.proxies.Device proxyObject : messageview_device)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MessageView_Device.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageViewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.MessageView that = (pushnotifications.proxies.MessageView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.MessageView";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
