// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies;

public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PushNotifications.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Body("Body"),
		TimeToLive("TimeToLive"),
		Badge("Badge"),
		ActionName("ActionName"),
		ContextObjectGuid("ContextObjectGuid"),
		SendDateTime("SendDateTime"),
		Status("Status"),
		FailureReason("FailureReason"),
		FailureCount("FailureCount"),
		DeviceType("DeviceType"),
		MessageId("MessageId"),
		To("To"),
		PlaySound("PlaySound"),
		Message_Device("PushNotifications.Message_Device");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "PushNotifications.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("PushNotifications.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a PushNotifications.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static pushnotifications.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return pushnotifications.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static pushnotifications.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new pushnotifications.proxies.Message(context, mendixObject);
	}

	public static pushnotifications.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return pushnotifications.proxies.Message.initialize(context, mendixObject);
	}

	public static java.util.List<pushnotifications.proxies.Message> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<pushnotifications.proxies.Message> result = new java.util.ArrayList<pushnotifications.proxies.Message>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//PushNotifications.Message" + xpathConstraint))
			result.add(pushnotifications.proxies.Message.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of TimeToLive
	 */
	public final java.lang.Long getTimeToLive()
	{
		return getTimeToLive(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeToLive
	 */
	public final java.lang.Long getTimeToLive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TimeToLive.toString());
	}

	/**
	 * Set value of TimeToLive
	 * @param timetolive
	 */
	public final void setTimeToLive(java.lang.Long timetolive)
	{
		setTimeToLive(getContext(), timetolive);
	}

	/**
	 * Set value of TimeToLive
	 * @param context
	 * @param timetolive
	 */
	public final void setTimeToLive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long timetolive)
	{
		getMendixObject().setValue(context, MemberNames.TimeToLive.toString(), timetolive);
	}

	/**
	 * @return value of Badge
	 */
	public final java.lang.Integer getBadge()
	{
		return getBadge(getContext());
	}

	/**
	 * @param context
	 * @return value of Badge
	 */
	public final java.lang.Integer getBadge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Badge.toString());
	}

	/**
	 * Set value of Badge
	 * @param badge
	 */
	public final void setBadge(java.lang.Integer badge)
	{
		setBadge(getContext(), badge);
	}

	/**
	 * Set value of Badge
	 * @param context
	 * @param badge
	 */
	public final void setBadge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer badge)
	{
		getMendixObject().setValue(context, MemberNames.Badge.toString(), badge);
	}

	/**
	 * @return value of ActionName
	 */
	public final java.lang.String getActionName()
	{
		return getActionName(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionName
	 */
	public final java.lang.String getActionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionName.toString());
	}

	/**
	 * Set value of ActionName
	 * @param actionname
	 */
	public final void setActionName(java.lang.String actionname)
	{
		setActionName(getContext(), actionname);
	}

	/**
	 * Set value of ActionName
	 * @param context
	 * @param actionname
	 */
	public final void setActionName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actionname)
	{
		getMendixObject().setValue(context, MemberNames.ActionName.toString(), actionname);
	}

	/**
	 * @return value of ContextObjectGuid
	 */
	public final java.lang.Long getContextObjectGuid()
	{
		return getContextObjectGuid(getContext());
	}

	/**
	 * @param context
	 * @return value of ContextObjectGuid
	 */
	public final java.lang.Long getContextObjectGuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ContextObjectGuid.toString());
	}

	/**
	 * Set value of ContextObjectGuid
	 * @param contextobjectguid
	 */
	public final void setContextObjectGuid(java.lang.Long contextobjectguid)
	{
		setContextObjectGuid(getContext(), contextobjectguid);
	}

	/**
	 * Set value of ContextObjectGuid
	 * @param context
	 * @param contextobjectguid
	 */
	public final void setContextObjectGuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long contextobjectguid)
	{
		getMendixObject().setValue(context, MemberNames.ContextObjectGuid.toString(), contextobjectguid);
	}

	/**
	 * @return value of SendDateTime
	 */
	public final java.util.Date getSendDateTime()
	{
		return getSendDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of SendDateTime
	 */
	public final java.util.Date getSendDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SendDateTime.toString());
	}

	/**
	 * Set value of SendDateTime
	 * @param senddatetime
	 */
	public final void setSendDateTime(java.util.Date senddatetime)
	{
		setSendDateTime(getContext(), senddatetime);
	}

	/**
	 * Set value of SendDateTime
	 * @param context
	 * @param senddatetime
	 */
	public final void setSendDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date senddatetime)
	{
		getMendixObject().setValue(context, MemberNames.SendDateTime.toString(), senddatetime);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final pushnotifications.proxies.MessageStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final pushnotifications.proxies.MessageStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return pushnotifications.proxies.MessageStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(pushnotifications.proxies.MessageStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.MessageStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of FailureReason
	 */
	public final java.lang.String getFailureReason()
	{
		return getFailureReason(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureReason
	 */
	public final java.lang.String getFailureReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FailureReason.toString());
	}

	/**
	 * Set value of FailureReason
	 * @param failurereason
	 */
	public final void setFailureReason(java.lang.String failurereason)
	{
		setFailureReason(getContext(), failurereason);
	}

	/**
	 * Set value of FailureReason
	 * @param context
	 * @param failurereason
	 */
	public final void setFailureReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String failurereason)
	{
		getMendixObject().setValue(context, MemberNames.FailureReason.toString(), failurereason);
	}

	/**
	 * @return value of FailureCount
	 */
	public final java.lang.Integer getFailureCount()
	{
		return getFailureCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureCount
	 */
	public final java.lang.Integer getFailureCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FailureCount.toString());
	}

	/**
	 * Set value of FailureCount
	 * @param failurecount
	 */
	public final void setFailureCount(java.lang.Integer failurecount)
	{
		setFailureCount(getContext(), failurecount);
	}

	/**
	 * Set value of FailureCount
	 * @param context
	 * @param failurecount
	 */
	public final void setFailureCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer failurecount)
	{
		getMendixObject().setValue(context, MemberNames.FailureCount.toString(), failurecount);
	}

	/**
	 * Set value of DeviceType
	 * @param devicetype
	 */
	public final pushnotifications.proxies.DeviceType getDeviceType()
	{
		return getDeviceType(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceType
	 */
	public final pushnotifications.proxies.DeviceType getDeviceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DeviceType.toString());
		if (obj == null)
			return null;

		return pushnotifications.proxies.DeviceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DeviceType
	 * @param devicetype
	 */
	public final void setDeviceType(pushnotifications.proxies.DeviceType devicetype)
	{
		setDeviceType(getContext(), devicetype);
	}

	/**
	 * Set value of DeviceType
	 * @param context
	 * @param devicetype
	 */
	public final void setDeviceType(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.DeviceType devicetype)
	{
		if (devicetype != null)
			getMendixObject().setValue(context, MemberNames.DeviceType.toString(), devicetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.DeviceType.toString(), null);
	}

	/**
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId()
	{
		return getMessageId(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageId
	 */
	public final java.lang.String getMessageId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageId.toString());
	}

	/**
	 * Set value of MessageId
	 * @param messageid
	 */
	public final void setMessageId(java.lang.String messageid)
	{
		setMessageId(getContext(), messageid);
	}

	/**
	 * Set value of MessageId
	 * @param context
	 * @param messageid
	 */
	public final void setMessageId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageid)
	{
		getMendixObject().setValue(context, MemberNames.MessageId.toString(), messageid);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of PlaySound
	 */
	public final java.lang.Boolean getPlaySound()
	{
		return getPlaySound(getContext());
	}

	/**
	 * @param context
	 * @return value of PlaySound
	 */
	public final java.lang.Boolean getPlaySound(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PlaySound.toString());
	}

	/**
	 * Set value of PlaySound
	 * @param playsound
	 */
	public final void setPlaySound(java.lang.Boolean playsound)
	{
		setPlaySound(getContext(), playsound);
	}

	/**
	 * Set value of PlaySound
	 * @param context
	 * @param playsound
	 */
	public final void setPlaySound(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean playsound)
	{
		getMendixObject().setValue(context, MemberNames.PlaySound.toString(), playsound);
	}

	/**
	 * @return value of Message_Device
	 */
	public final pushnotifications.proxies.Device getMessage_Device() throws com.mendix.core.CoreException
	{
		return getMessage_Device(getContext());
	}

	/**
	 * @param context
	 * @return value of Message_Device
	 */
	public final pushnotifications.proxies.Device getMessage_Device(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		pushnotifications.proxies.Device result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Message_Device.toString());
		if (identifier != null)
			result = pushnotifications.proxies.Device.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Message_Device
	 * @param message_device
	 */
	public final void setMessage_Device(pushnotifications.proxies.Device message_device)
	{
		setMessage_Device(getContext(), message_device);
	}

	/**
	 * Set value of Message_Device
	 * @param context
	 * @param message_device
	 */
	public final void setMessage_Device(com.mendix.systemwideinterfaces.core.IContext context, pushnotifications.proxies.Device message_device)
	{
		if (message_device == null)
			getMendixObject().setValue(context, MemberNames.Message_Device.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Message_Device.toString(), message_device.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final pushnotifications.proxies.Message that = (pushnotifications.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "PushNotifications.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
