// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowessentialspublic.proxies;

public class WorkflowAttachment extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowEssentialsPublic.WorkflowAttachment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileName("FileName"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		WorkflowAttachment_Workflow("WorkflowEssentialsPublic.WorkflowAttachment_Workflow");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowAttachment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowEssentialsPublic.WorkflowAttachment"));
	}

	protected WorkflowAttachment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowAttachmentMendixObject)
	{
		super(context, workflowAttachmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("WorkflowEssentialsPublic.WorkflowAttachment", workflowAttachmentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowEssentialsPublic.WorkflowAttachment");
	}

	/**
	 * @deprecated Use 'WorkflowAttachment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowessentialspublic.proxies.WorkflowAttachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowessentialspublic.proxies.WorkflowAttachment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowessentialspublic.proxies.WorkflowAttachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowessentialspublic.proxies.WorkflowAttachment(context, mendixObject);
	}

	public static workflowessentialspublic.proxies.WorkflowAttachment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowessentialspublic.proxies.WorkflowAttachment.initialize(context, mendixObject);
	}

	public static java.util.List<workflowessentialspublic.proxies.WorkflowAttachment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<workflowessentialspublic.proxies.WorkflowAttachment> result = new java.util.ArrayList<workflowessentialspublic.proxies.WorkflowAttachment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//WorkflowEssentialsPublic.WorkflowAttachment" + xpathConstraint))
			result.add(workflowessentialspublic.proxies.WorkflowAttachment.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FileName
	 */
	public final java.lang.String getFileName()
	{
		return getFileName(getContext());
	}

	/**
	 * @param context
	 * @return value of FileName
	 */
	public final java.lang.String getFileName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FileName.toString());
	}

	/**
	 * Set value of FileName
	 * @param filename
	 */
	public final void setFileName(java.lang.String filename)
	{
		setFileName(getContext(), filename);
	}

	/**
	 * Set value of FileName
	 * @param context
	 * @param filename
	 */
	public final void setFileName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String filename)
	{
		getMendixObject().setValue(context, MemberNames.FileName.toString(), filename);
	}

	/**
	 * @return value of WorkflowAttachment_Workflow
	 */
	public final system.proxies.WorkflowInstance getWorkflowAttachment_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowAttachment_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowAttachment_Workflow
	 */
	public final system.proxies.WorkflowInstance getWorkflowAttachment_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowInstance result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowAttachment_Workflow.toString());
		if (identifier != null)
			result = system.proxies.WorkflowInstance.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowAttachment_Workflow
	 * @param workflowattachment_workflow
	 */
	public final void setWorkflowAttachment_Workflow(system.proxies.WorkflowInstance workflowattachment_workflow)
	{
		setWorkflowAttachment_Workflow(getContext(), workflowattachment_workflow);
	}

	/**
	 * Set value of WorkflowAttachment_Workflow
	 * @param context
	 * @param workflowattachment_workflow
	 */
	public final void setWorkflowAttachment_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowInstance workflowattachment_workflow)
	{
		if (workflowattachment_workflow == null)
			getMendixObject().setValue(context, MemberNames.WorkflowAttachment_Workflow.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowAttachment_Workflow.toString(), workflowattachment_workflow.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowessentialspublic.proxies.WorkflowAttachment that = (workflowessentialspublic.proxies.WorkflowAttachment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowEssentialsPublic.WorkflowAttachment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
