// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowessentialspublic.proxies;

public class WorkflowNote
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowNoteMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowEssentialsPublic.WorkflowNote";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		WorkflowNote_Workflow("WorkflowEssentialsPublic.WorkflowNote_Workflow");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowEssentialsPublic.WorkflowNote"));
	}

	protected WorkflowNote(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowNoteMendixObject)
	{
		if (workflowNoteMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("WorkflowEssentialsPublic.WorkflowNote", workflowNoteMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowEssentialsPublic.WorkflowNote");

		this.workflowNoteMendixObject = workflowNoteMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowNote.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowessentialspublic.proxies.WorkflowNote initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowessentialspublic.proxies.WorkflowNote.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowessentialspublic.proxies.WorkflowNote initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowessentialspublic.proxies.WorkflowNote(context, mendixObject);
	}

	public static workflowessentialspublic.proxies.WorkflowNote load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowessentialspublic.proxies.WorkflowNote.initialize(context, mendixObject);
	}

	public static java.util.List<workflowessentialspublic.proxies.WorkflowNote> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<workflowessentialspublic.proxies.WorkflowNote> result = new java.util.ArrayList<workflowessentialspublic.proxies.WorkflowNote>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//WorkflowEssentialsPublic.WorkflowNote" + xpathConstraint))
			result.add(workflowessentialspublic.proxies.WorkflowNote.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of WorkflowNote_Workflow
	 */
	public final system.proxies.WorkflowInstance getWorkflowNote_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowNote_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowNote_Workflow
	 */
	public final system.proxies.WorkflowInstance getWorkflowNote_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowInstance result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowNote_Workflow.toString());
		if (identifier != null)
			result = system.proxies.WorkflowInstance.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowNote_Workflow
	 * @param workflownote_workflow
	 */
	public final void setWorkflowNote_Workflow(system.proxies.WorkflowInstance workflownote_workflow)
	{
		setWorkflowNote_Workflow(getContext(), workflownote_workflow);
	}

	/**
	 * Set value of WorkflowNote_Workflow
	 * @param context
	 * @param workflownote_workflow
	 */
	public final void setWorkflowNote_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowInstance workflownote_workflow)
	{
		if (workflownote_workflow == null)
			getMendixObject().setValue(context, MemberNames.WorkflowNote_Workflow.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowNote_Workflow.toString(), workflownote_workflow.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowNoteMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowessentialspublic.proxies.WorkflowNote that = (workflowessentialspublic.proxies.WorkflowNote) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowEssentialsPublic.WorkflowNote";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
