// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datadogapi.proxies;

public class Response
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatadogAPI.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ip("Ip"),
		City("City"),
		Region("Region"),
		Region_code("Region_code"),
		Country("Country"),
		Country_code("Country_code"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Timezone("Timezone"),
		Currency("Currency"),
		Currency_name("Currency_name");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatadogAPI.Response"));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatadogAPI.Response", responseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatadogAPI.Response");

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Response.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datadogapi.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datadogapi.proxies.Response.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datadogapi.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datadogapi.proxies.Response(context, mendixObject);
	}

	public static datadogapi.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datadogapi.proxies.Response.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ip
	 */
	public final java.lang.String getIp()
	{
		return getIp(getContext());
	}

	/**
	 * @param context
	 * @return value of Ip
	 */
	public final java.lang.String getIp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ip.toString());
	}

	/**
	 * Set value of Ip
	 * @param ip
	 */
	public final void setIp(java.lang.String ip)
	{
		setIp(getContext(), ip);
	}

	/**
	 * Set value of Ip
	 * @param context
	 * @param ip
	 */
	public final void setIp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ip)
	{
		getMendixObject().setValue(context, MemberNames.Ip.toString(), ip);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of Region_code
	 */
	public final java.lang.String getRegion_code()
	{
		return getRegion_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Region_code
	 */
	public final java.lang.String getRegion_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region_code.toString());
	}

	/**
	 * Set value of Region_code
	 * @param region_code
	 */
	public final void setRegion_code(java.lang.String region_code)
	{
		setRegion_code(getContext(), region_code);
	}

	/**
	 * Set value of Region_code
	 * @param context
	 * @param region_code
	 */
	public final void setRegion_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region_code)
	{
		getMendixObject().setValue(context, MemberNames.Region_code.toString(), region_code);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Country_code
	 */
	public final java.lang.String getCountry_code()
	{
		return getCountry_code(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_code
	 */
	public final java.lang.String getCountry_code(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country_code.toString());
	}

	/**
	 * Set value of Country_code
	 * @param country_code
	 */
	public final void setCountry_code(java.lang.String country_code)
	{
		setCountry_code(getContext(), country_code);
	}

	/**
	 * Set value of Country_code
	 * @param context
	 * @param country_code
	 */
	public final void setCountry_code(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country_code)
	{
		getMendixObject().setValue(context, MemberNames.Country_code.toString(), country_code);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.String timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @return value of Currency_name
	 */
	public final java.lang.String getCurrency_name()
	{
		return getCurrency_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency_name
	 */
	public final java.lang.String getCurrency_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency_name.toString());
	}

	/**
	 * Set value of Currency_name
	 * @param currency_name
	 */
	public final void setCurrency_name(java.lang.String currency_name)
	{
		setCurrency_name(getContext(), currency_name);
	}

	/**
	 * Set value of Currency_name
	 * @param context
	 * @param currency_name
	 */
	public final void setCurrency_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency_name)
	{
		getMendixObject().setValue(context, MemberNames.Currency_name.toString(), currency_name);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datadogapi.proxies.Response that = (datadogapi.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatadogAPI.Response";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
