// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Salesforce_Connector module

	public static java.lang.String getConsumerKey()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.ConsumerKey");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.LogNode");
	}

	public static java.lang.String getOAuthEndpointAuthorization()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.OAuthEndpointAuthorization");
	}

	public static java.lang.String getOAuthEndPointRevokeOAuthToken()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.OAuthEndPointRevokeOAuthToken");
	}

	public static java.lang.String getOAuthEndPointTokenRequest()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.OAuthEndPointTokenRequest");
	}

	/**
	* The Callback URL from the connected app definition.
	*/
	public static java.lang.String getredirect_uri_WebServer()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.redirect_uri_WebServer");
	}

	/**
	* The Callback URL from the connected app definition.
	*/
	public static java.lang.String getredirect_uri_WebServer_Code()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.redirect_uri_WebServer_Code");
	}

	public static boolean getSalesforceCreateEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Salesforce_Connector.SalesforceCreateEnabled");
	}

	public static boolean getSalesforceUpdateEnabled()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("Salesforce_Connector.SalesforceUpdateEnabled");
	}

	public static java.lang.String getServiceVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Salesforce_Connector.ServiceVersion");
	}
}