// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the SAPODataConnector module

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SAPODataConnector.LogNode");
	}

	public static java.lang.String getLogNode_2()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SAPODataConnector.LogNode_2");
	}

	public static java.lang.String getSAPODataConnector_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SAPODataConnector.SAPODataConnector_Version");
	}
}