// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package taskqueuehelpers.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TaskQueueHelpers module

	public static java.lang.Long getTasksCompletedOlderThanHours()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TaskQueueHelpers.TasksCompletedOlderThanHours");
	}

	public static java.lang.Long getTasksNonCompletedOlderThanHours()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TaskQueueHelpers.TasksNonCompletedOlderThanHours");
	}
}