// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class Contact extends sapodataconnector.proxies.OdataObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.Contact";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContactGuid("ContactGuid"),
		BusinessPartnerID("BusinessPartnerID"),
		Title("Title"),
		FirstName("FirstName"),
		MiddleName("MiddleName"),
		LastName("LastName"),
		Nickname("Nickname"),
		Initials("Initials"),
		Sex("Sex"),
		PhoneNumber("PhoneNumber"),
		FaxNumber("FaxNumber"),
		EmailAddress("EmailAddress"),
		Language("Language"),
		DateOfBirth("DateOfBirth"),
		ToBusinessPartnerDeferred("ToBusinessPartnerDeferred"),
		meta_objectURI("meta_objectURI"),
		meta_etag("meta_etag"),
		ToContacts_BusinessPartner_Contact("SAP_Integration.ToContacts_BusinessPartner_Contact"),
		AddressComplex_Contact_CT_Address("SAP_Integration.AddressComplex_Contact_CT_Address"),
		ToBusinessPartner_Contact_BusinessPartner("SAP_Integration.ToBusinessPartner_Contact_BusinessPartner"),
		OdataObject_ResultInfo("SAPODataConnector.OdataObject_ResultInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Contact(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.Contact"));
	}

	protected Contact(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contactMendixObject)
	{
		super(context, contactMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.Contact", contactMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.Contact");
	}

	/**
	 * @deprecated Use 'Contact.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.Contact initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.Contact.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.Contact initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.Contact(context, mendixObject);
	}

	public static sap_integration.proxies.Contact load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.Contact.initialize(context, mendixObject);
	}

	/**
	 * @return value of ContactGuid
	 */
	public final java.lang.String getContactGuid()
	{
		return getContactGuid(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactGuid
	 */
	public final java.lang.String getContactGuid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactGuid.toString());
	}

	/**
	 * Set value of ContactGuid
	 * @param contactguid
	 */
	public final void setContactGuid(java.lang.String contactguid)
	{
		setContactGuid(getContext(), contactguid);
	}

	/**
	 * Set value of ContactGuid
	 * @param context
	 * @param contactguid
	 */
	public final void setContactGuid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactguid)
	{
		getMendixObject().setValue(context, MemberNames.ContactGuid.toString(), contactguid);
	}

	/**
	 * @return value of BusinessPartnerID
	 */
	public final java.lang.String getBusinessPartnerID()
	{
		return getBusinessPartnerID(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPartnerID
	 */
	public final java.lang.String getBusinessPartnerID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BusinessPartnerID.toString());
	}

	/**
	 * Set value of BusinessPartnerID
	 * @param businesspartnerid
	 */
	public final void setBusinessPartnerID(java.lang.String businesspartnerid)
	{
		setBusinessPartnerID(getContext(), businesspartnerid);
	}

	/**
	 * Set value of BusinessPartnerID
	 * @param context
	 * @param businesspartnerid
	 */
	public final void setBusinessPartnerID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String businesspartnerid)
	{
		getMendixObject().setValue(context, MemberNames.BusinessPartnerID.toString(), businesspartnerid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of MiddleName
	 */
	public final java.lang.String getMiddleName()
	{
		return getMiddleName(getContext());
	}

	/**
	 * @param context
	 * @return value of MiddleName
	 */
	public final java.lang.String getMiddleName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MiddleName.toString());
	}

	/**
	 * Set value of MiddleName
	 * @param middlename
	 */
	public final void setMiddleName(java.lang.String middlename)
	{
		setMiddleName(getContext(), middlename);
	}

	/**
	 * Set value of MiddleName
	 * @param context
	 * @param middlename
	 */
	public final void setMiddleName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String middlename)
	{
		getMendixObject().setValue(context, MemberNames.MiddleName.toString(), middlename);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of Nickname
	 */
	public final java.lang.String getNickname()
	{
		return getNickname(getContext());
	}

	/**
	 * @param context
	 * @return value of Nickname
	 */
	public final java.lang.String getNickname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nickname.toString());
	}

	/**
	 * Set value of Nickname
	 * @param nickname
	 */
	public final void setNickname(java.lang.String nickname)
	{
		setNickname(getContext(), nickname);
	}

	/**
	 * Set value of Nickname
	 * @param context
	 * @param nickname
	 */
	public final void setNickname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nickname)
	{
		getMendixObject().setValue(context, MemberNames.Nickname.toString(), nickname);
	}

	/**
	 * @return value of Initials
	 */
	public final java.lang.String getInitials()
	{
		return getInitials(getContext());
	}

	/**
	 * @param context
	 * @return value of Initials
	 */
	public final java.lang.String getInitials(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Initials.toString());
	}

	/**
	 * Set value of Initials
	 * @param initials
	 */
	public final void setInitials(java.lang.String initials)
	{
		setInitials(getContext(), initials);
	}

	/**
	 * Set value of Initials
	 * @param context
	 * @param initials
	 */
	public final void setInitials(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String initials)
	{
		getMendixObject().setValue(context, MemberNames.Initials.toString(), initials);
	}

	/**
	 * @return value of Sex
	 */
	public final java.lang.String getSex()
	{
		return getSex(getContext());
	}

	/**
	 * @param context
	 * @return value of Sex
	 */
	public final java.lang.String getSex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sex.toString());
	}

	/**
	 * Set value of Sex
	 * @param sex
	 */
	public final void setSex(java.lang.String sex)
	{
		setSex(getContext(), sex);
	}

	/**
	 * Set value of Sex
	 * @param context
	 * @param sex
	 */
	public final void setSex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sex)
	{
		getMendixObject().setValue(context, MemberNames.Sex.toString(), sex);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of FaxNumber
	 */
	public final java.lang.String getFaxNumber()
	{
		return getFaxNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of FaxNumber
	 */
	public final java.lang.String getFaxNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FaxNumber.toString());
	}

	/**
	 * Set value of FaxNumber
	 * @param faxnumber
	 */
	public final void setFaxNumber(java.lang.String faxnumber)
	{
		setFaxNumber(getContext(), faxnumber);
	}

	/**
	 * Set value of FaxNumber
	 * @param context
	 * @param faxnumber
	 */
	public final void setFaxNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String faxnumber)
	{
		getMendixObject().setValue(context, MemberNames.FaxNumber.toString(), faxnumber);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Language
	 */
	public final java.lang.String getLanguage()
	{
		return getLanguage(getContext());
	}

	/**
	 * @param context
	 * @return value of Language
	 */
	public final java.lang.String getLanguage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Language.toString());
	}

	/**
	 * Set value of Language
	 * @param language
	 */
	public final void setLanguage(java.lang.String language)
	{
		setLanguage(getContext(), language);
	}

	/**
	 * Set value of Language
	 * @param context
	 * @param language
	 */
	public final void setLanguage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String language)
	{
		getMendixObject().setValue(context, MemberNames.Language.toString(), language);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of ToBusinessPartnerDeferred
	 */
	public final java.lang.String getToBusinessPartnerDeferred()
	{
		return getToBusinessPartnerDeferred(getContext());
	}

	/**
	 * @param context
	 * @return value of ToBusinessPartnerDeferred
	 */
	public final java.lang.String getToBusinessPartnerDeferred(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ToBusinessPartnerDeferred.toString());
	}

	/**
	 * Set value of ToBusinessPartnerDeferred
	 * @param tobusinesspartnerdeferred
	 */
	public final void setToBusinessPartnerDeferred(java.lang.String tobusinesspartnerdeferred)
	{
		setToBusinessPartnerDeferred(getContext(), tobusinesspartnerdeferred);
	}

	/**
	 * Set value of ToBusinessPartnerDeferred
	 * @param context
	 * @param tobusinesspartnerdeferred
	 */
	public final void setToBusinessPartnerDeferred(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tobusinesspartnerdeferred)
	{
		getMendixObject().setValue(context, MemberNames.ToBusinessPartnerDeferred.toString(), tobusinesspartnerdeferred);
	}

	/**
	 * @return value of ToContacts_BusinessPartner_Contact
	 */
	public final sap_integration.proxies.BusinessPartner getToContacts_BusinessPartner_Contact() throws com.mendix.core.CoreException
	{
		return getToContacts_BusinessPartner_Contact(getContext());
	}

	/**
	 * @param context
	 * @return value of ToContacts_BusinessPartner_Contact
	 */
	public final sap_integration.proxies.BusinessPartner getToContacts_BusinessPartner_Contact(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sap_integration.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ToContacts_BusinessPartner_Contact.toString());
		if (identifier != null)
			result = sap_integration.proxies.BusinessPartner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ToContacts_BusinessPartner_Contact
	 * @param tocontacts_businesspartner_contact
	 */
	public final void setToContacts_BusinessPartner_Contact(sap_integration.proxies.BusinessPartner tocontacts_businesspartner_contact)
	{
		setToContacts_BusinessPartner_Contact(getContext(), tocontacts_businesspartner_contact);
	}

	/**
	 * Set value of ToContacts_BusinessPartner_Contact
	 * @param context
	 * @param tocontacts_businesspartner_contact
	 */
	public final void setToContacts_BusinessPartner_Contact(com.mendix.systemwideinterfaces.core.IContext context, sap_integration.proxies.BusinessPartner tocontacts_businesspartner_contact)
	{
		if (tocontacts_businesspartner_contact == null)
			getMendixObject().setValue(context, MemberNames.ToContacts_BusinessPartner_Contact.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ToContacts_BusinessPartner_Contact.toString(), tocontacts_businesspartner_contact.getMendixObject().getId());
	}

	/**
	 * @return value of AddressComplex_Contact_CT_Address
	 */
	public final sap_integration.proxies.CT_Address getAddressComplex_Contact_CT_Address() throws com.mendix.core.CoreException
	{
		return getAddressComplex_Contact_CT_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressComplex_Contact_CT_Address
	 */
	public final sap_integration.proxies.CT_Address getAddressComplex_Contact_CT_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sap_integration.proxies.CT_Address result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString());
		if (identifier != null)
			result = sap_integration.proxies.CT_Address.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AddressComplex_Contact_CT_Address
	 * @param addresscomplex_contact_ct_address
	 */
	public final void setAddressComplex_Contact_CT_Address(sap_integration.proxies.CT_Address addresscomplex_contact_ct_address)
	{
		setAddressComplex_Contact_CT_Address(getContext(), addresscomplex_contact_ct_address);
	}

	/**
	 * Set value of AddressComplex_Contact_CT_Address
	 * @param context
	 * @param addresscomplex_contact_ct_address
	 */
	public final void setAddressComplex_Contact_CT_Address(com.mendix.systemwideinterfaces.core.IContext context, sap_integration.proxies.CT_Address addresscomplex_contact_ct_address)
	{
		if (addresscomplex_contact_ct_address == null)
			getMendixObject().setValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString(), addresscomplex_contact_ct_address.getMendixObject().getId());
	}

	/**
	 * @return value of ToBusinessPartner_Contact_BusinessPartner
	 */
	public final sap_integration.proxies.BusinessPartner getToBusinessPartner_Contact_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getToBusinessPartner_Contact_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of ToBusinessPartner_Contact_BusinessPartner
	 */
	public final sap_integration.proxies.BusinessPartner getToBusinessPartner_Contact_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sap_integration.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ToBusinessPartner_Contact_BusinessPartner.toString());
		if (identifier != null)
			result = sap_integration.proxies.BusinessPartner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ToBusinessPartner_Contact_BusinessPartner
	 * @param tobusinesspartner_contact_businesspartner
	 */
	public final void setToBusinessPartner_Contact_BusinessPartner(sap_integration.proxies.BusinessPartner tobusinesspartner_contact_businesspartner)
	{
		setToBusinessPartner_Contact_BusinessPartner(getContext(), tobusinesspartner_contact_businesspartner);
	}

	/**
	 * Set value of ToBusinessPartner_Contact_BusinessPartner
	 * @param context
	 * @param tobusinesspartner_contact_businesspartner
	 */
	public final void setToBusinessPartner_Contact_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, sap_integration.proxies.BusinessPartner tobusinesspartner_contact_businesspartner)
	{
		if (tobusinesspartner_contact_businesspartner == null)
			getMendixObject().setValue(context, MemberNames.ToBusinessPartner_Contact_BusinessPartner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ToBusinessPartner_Contact_BusinessPartner.toString(), tobusinesspartner_contact_businesspartner.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.Contact that = (sap_integration.proxies.Contact) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.Contact";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
