// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class CT_Address extends sapodataconnector.proxies.ComplexType
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.CT_Address";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		City("City"),
		PostalCode("PostalCode"),
		Street("Street"),
		Building("Building"),
		Country("Country"),
		AddressType("AddressType"),
		AddressComplex_BusinessPartner_CT_Address("SAP_Integration.AddressComplex_BusinessPartner_CT_Address"),
		AddressComplex_Contact_CT_Address("SAP_Integration.AddressComplex_Contact_CT_Address");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CT_Address(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.CT_Address"));
	}

	protected CT_Address(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cT_AddressMendixObject)
	{
		super(context, cT_AddressMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.CT_Address", cT_AddressMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.CT_Address");
	}

	/**
	 * @deprecated Use 'CT_Address.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.CT_Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.CT_Address.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.CT_Address initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.CT_Address(context, mendixObject);
	}

	public static sap_integration.proxies.CT_Address load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.CT_Address.initialize(context, mendixObject);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode()
	{
		return getPostalCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PostalCode
	 */
	public final java.lang.String getPostalCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PostalCode.toString());
	}

	/**
	 * Set value of PostalCode
	 * @param postalcode
	 */
	public final void setPostalCode(java.lang.String postalcode)
	{
		setPostalCode(getContext(), postalcode);
	}

	/**
	 * Set value of PostalCode
	 * @param context
	 * @param postalcode
	 */
	public final void setPostalCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postalcode)
	{
		getMendixObject().setValue(context, MemberNames.PostalCode.toString(), postalcode);
	}

	/**
	 * @return value of Street
	 */
	public final java.lang.String getStreet()
	{
		return getStreet(getContext());
	}

	/**
	 * @param context
	 * @return value of Street
	 */
	public final java.lang.String getStreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Street.toString());
	}

	/**
	 * Set value of Street
	 * @param street
	 */
	public final void setStreet(java.lang.String street)
	{
		setStreet(getContext(), street);
	}

	/**
	 * Set value of Street
	 * @param context
	 * @param street
	 */
	public final void setStreet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String street)
	{
		getMendixObject().setValue(context, MemberNames.Street.toString(), street);
	}

	/**
	 * @return value of Building
	 */
	public final java.lang.String getBuilding()
	{
		return getBuilding(getContext());
	}

	/**
	 * @param context
	 * @return value of Building
	 */
	public final java.lang.String getBuilding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Building.toString());
	}

	/**
	 * Set value of Building
	 * @param building
	 */
	public final void setBuilding(java.lang.String building)
	{
		setBuilding(getContext(), building);
	}

	/**
	 * Set value of Building
	 * @param context
	 * @param building
	 */
	public final void setBuilding(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String building)
	{
		getMendixObject().setValue(context, MemberNames.Building.toString(), building);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of AddressType
	 */
	public final java.lang.String getAddressType()
	{
		return getAddressType(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressType
	 */
	public final java.lang.String getAddressType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressType.toString());
	}

	/**
	 * Set value of AddressType
	 * @param addresstype
	 */
	public final void setAddressType(java.lang.String addresstype)
	{
		setAddressType(getContext(), addresstype);
	}

	/**
	 * Set value of AddressType
	 * @param context
	 * @param addresstype
	 */
	public final void setAddressType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addresstype)
	{
		getMendixObject().setValue(context, MemberNames.AddressType.toString(), addresstype);
	}

	/**
	 * @return value of AddressComplex_BusinessPartner_CT_Address
	 */
	public final sap_integration.proxies.BusinessPartner getAddressComplex_BusinessPartner_CT_Address() throws com.mendix.core.CoreException
	{
		return getAddressComplex_BusinessPartner_CT_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressComplex_BusinessPartner_CT_Address
	 */
	public final sap_integration.proxies.BusinessPartner getAddressComplex_BusinessPartner_CT_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sap_integration.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AddressComplex_BusinessPartner_CT_Address.toString());
		if (identifier != null)
			result = sap_integration.proxies.BusinessPartner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AddressComplex_BusinessPartner_CT_Address
	 * @param addresscomplex_businesspartner_ct_address
	 */
	public final void setAddressComplex_BusinessPartner_CT_Address(sap_integration.proxies.BusinessPartner addresscomplex_businesspartner_ct_address)
	{
		setAddressComplex_BusinessPartner_CT_Address(getContext(), addresscomplex_businesspartner_ct_address);
	}

	/**
	 * Set value of AddressComplex_BusinessPartner_CT_Address
	 * @param context
	 * @param addresscomplex_businesspartner_ct_address
	 */
	public final void setAddressComplex_BusinessPartner_CT_Address(com.mendix.systemwideinterfaces.core.IContext context, sap_integration.proxies.BusinessPartner addresscomplex_businesspartner_ct_address)
	{
		if (addresscomplex_businesspartner_ct_address == null)
			getMendixObject().setValue(context, MemberNames.AddressComplex_BusinessPartner_CT_Address.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AddressComplex_BusinessPartner_CT_Address.toString(), addresscomplex_businesspartner_ct_address.getMendixObject().getId());
	}

	/**
	 * @return value of AddressComplex_Contact_CT_Address
	 */
	public final sap_integration.proxies.Contact getAddressComplex_Contact_CT_Address() throws com.mendix.core.CoreException
	{
		return getAddressComplex_Contact_CT_Address(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressComplex_Contact_CT_Address
	 */
	public final sap_integration.proxies.Contact getAddressComplex_Contact_CT_Address(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sap_integration.proxies.Contact result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString());
		if (identifier != null)
			result = sap_integration.proxies.Contact.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AddressComplex_Contact_CT_Address
	 * @param addresscomplex_contact_ct_address
	 */
	public final void setAddressComplex_Contact_CT_Address(sap_integration.proxies.Contact addresscomplex_contact_ct_address)
	{
		setAddressComplex_Contact_CT_Address(getContext(), addresscomplex_contact_ct_address);
	}

	/**
	 * Set value of AddressComplex_Contact_CT_Address
	 * @param context
	 * @param addresscomplex_contact_ct_address
	 */
	public final void setAddressComplex_Contact_CT_Address(com.mendix.systemwideinterfaces.core.IContext context, sap_integration.proxies.Contact addresscomplex_contact_ct_address)
	{
		if (addresscomplex_contact_ct_address == null)
			getMendixObject().setValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AddressComplex_Contact_CT_Address.toString(), addresscomplex_contact_ct_address.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.CT_Address that = (sap_integration.proxies.CT_Address) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.CT_Address";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
