// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public enum EntitySetNames
{
	BusinessPartnerSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "BusinessPartner" } }),
	ProductSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "Product" } }),
	SalesOrderSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrder" } }),
	SalesOrderLineItemSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrderLineItem" } }),
	ContactSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "Contact" } }),
	VH_SexSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_Sex" } }),
	VH_CountrySet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_Country" } }),
	VH_AddressTypeSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_AddressType" } }),
	VH_CategorySet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_Category" } }),
	VH_CurrencySet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_Currency" } }),
	VH_UnitQuantitySet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_UnitQuantity" } }),
	VH_UnitWeightSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_UnitWeight" } }),
	VH_UnitLengthSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_UnitLength" } }),
	VH_ProductTypeCodeSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_ProductTypeCode" } }),
	VH_BPRoleSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_BPRole" } }),
	VH_LanguageSet(new java.lang.String[][] { new java.lang.String[] { "en_US", "VH_Language" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EntitySetNames(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
