// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public enum FunctionNames
{
	RegenerateAllData(new java.lang.String[][] { new java.lang.String[] { "en_US", "RegenerateAllData" } }),
	SalesOrder_Confirm(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrder_Confirm" } }),
	SalesOrder_Cancel(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrder_Cancel" } }),
	SalesOrder_InvoiceCreated(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrder_InvoiceCreated" } }),
	SalesOrder_GoodsIssueCreated(new java.lang.String[][] { new java.lang.String[] { "en_US", "SalesOrder_GoodsIssueCreated" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private FunctionNames(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
