// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class RegenerateAllDataParameters extends sapodataconnector.proxies.FunctionParameters
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.RegenerateAllDataParameters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NoOfSalesOrders("NoOfSalesOrders"),
		postParameterInline("postParameterInline");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RegenerateAllDataParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.RegenerateAllDataParameters"));
	}

	protected RegenerateAllDataParameters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject regenerateAllDataParametersMendixObject)
	{
		super(context, regenerateAllDataParametersMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.RegenerateAllDataParameters", regenerateAllDataParametersMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.RegenerateAllDataParameters");
	}

	/**
	 * @deprecated Use 'RegenerateAllDataParameters.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.RegenerateAllDataParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.RegenerateAllDataParameters.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.RegenerateAllDataParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.RegenerateAllDataParameters(context, mendixObject);
	}

	public static sap_integration.proxies.RegenerateAllDataParameters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.RegenerateAllDataParameters.initialize(context, mendixObject);
	}

	/**
	 * @return value of NoOfSalesOrders
	 */
	public final java.lang.Integer getNoOfSalesOrders()
	{
		return getNoOfSalesOrders(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfSalesOrders
	 */
	public final java.lang.Integer getNoOfSalesOrders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfSalesOrders.toString());
	}

	/**
	 * Set value of NoOfSalesOrders
	 * @param noofsalesorders
	 */
	public final void setNoOfSalesOrders(java.lang.Integer noofsalesorders)
	{
		setNoOfSalesOrders(getContext(), noofsalesorders);
	}

	/**
	 * Set value of NoOfSalesOrders
	 * @param context
	 * @param noofsalesorders
	 */
	public final void setNoOfSalesOrders(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofsalesorders)
	{
		getMendixObject().setValue(context, MemberNames.NoOfSalesOrders.toString(), noofsalesorders);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.RegenerateAllDataParameters that = (sap_integration.proxies.RegenerateAllDataParameters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.RegenerateAllDataParameters";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
