// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class SalesOrder_CancelParameters extends sapodataconnector.proxies.FunctionParameters
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.SalesOrder_CancelParameters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SalesOrderID("SalesOrderID"),
		postParameterInline("postParameterInline");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesOrder_CancelParameters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.SalesOrder_CancelParameters"));
	}

	protected SalesOrder_CancelParameters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesOrder_CancelParametersMendixObject)
	{
		super(context, salesOrder_CancelParametersMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.SalesOrder_CancelParameters", salesOrder_CancelParametersMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.SalesOrder_CancelParameters");
	}

	/**
	 * @deprecated Use 'SalesOrder_CancelParameters.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.SalesOrder_CancelParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.SalesOrder_CancelParameters.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.SalesOrder_CancelParameters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.SalesOrder_CancelParameters(context, mendixObject);
	}

	public static sap_integration.proxies.SalesOrder_CancelParameters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.SalesOrder_CancelParameters.initialize(context, mendixObject);
	}

	/**
	 * @return value of SalesOrderID
	 */
	public final java.lang.String getSalesOrderID()
	{
		return getSalesOrderID(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesOrderID
	 */
	public final java.lang.String getSalesOrderID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SalesOrderID.toString());
	}

	/**
	 * Set value of SalesOrderID
	 * @param salesorderid
	 */
	public final void setSalesOrderID(java.lang.String salesorderid)
	{
		setSalesOrderID(getContext(), salesorderid);
	}

	/**
	 * Set value of SalesOrderID
	 * @param context
	 * @param salesorderid
	 */
	public final void setSalesOrderID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String salesorderid)
	{
		getMendixObject().setValue(context, MemberNames.SalesOrderID.toString(), salesorderid);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.SalesOrder_CancelParameters that = (sap_integration.proxies.SalesOrder_CancelParameters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.SalesOrder_CancelParameters";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
