// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class VH_AddressType extends sapodataconnector.proxies.OdataObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.VH_AddressType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AddressType("AddressType"),
		Shorttext("Shorttext"),
		meta_objectURI("meta_objectURI"),
		meta_etag("meta_etag"),
		OdataObject_ResultInfo("SAPODataConnector.OdataObject_ResultInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VH_AddressType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.VH_AddressType"));
	}

	protected VH_AddressType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vH_AddressTypeMendixObject)
	{
		super(context, vH_AddressTypeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.VH_AddressType", vH_AddressTypeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.VH_AddressType");
	}

	/**
	 * @deprecated Use 'VH_AddressType.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.VH_AddressType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.VH_AddressType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.VH_AddressType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.VH_AddressType(context, mendixObject);
	}

	public static sap_integration.proxies.VH_AddressType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.VH_AddressType.initialize(context, mendixObject);
	}

	/**
	 * @return value of AddressType
	 */
	public final java.lang.String getAddressType()
	{
		return getAddressType(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressType
	 */
	public final java.lang.String getAddressType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressType.toString());
	}

	/**
	 * Set value of AddressType
	 * @param addresstype
	 */
	public final void setAddressType(java.lang.String addresstype)
	{
		setAddressType(getContext(), addresstype);
	}

	/**
	 * Set value of AddressType
	 * @param context
	 * @param addresstype
	 */
	public final void setAddressType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addresstype)
	{
		getMendixObject().setValue(context, MemberNames.AddressType.toString(), addresstype);
	}

	/**
	 * @return value of Shorttext
	 */
	public final java.lang.String getShorttext()
	{
		return getShorttext(getContext());
	}

	/**
	 * @param context
	 * @return value of Shorttext
	 */
	public final java.lang.String getShorttext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Shorttext.toString());
	}

	/**
	 * Set value of Shorttext
	 * @param shorttext
	 */
	public final void setShorttext(java.lang.String shorttext)
	{
		setShorttext(getContext(), shorttext);
	}

	/**
	 * Set value of Shorttext
	 * @param context
	 * @param shorttext
	 */
	public final void setShorttext(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shorttext)
	{
		getMendixObject().setValue(context, MemberNames.Shorttext.toString(), shorttext);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.VH_AddressType that = (sap_integration.proxies.VH_AddressType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.VH_AddressType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
