// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies;

public class VH_Language extends sapodataconnector.proxies.OdataObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAP_Integration.VH_Language";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Spras("Spras"),
		Sptxt("Sptxt"),
		meta_objectURI("meta_objectURI"),
		meta_etag("meta_etag"),
		OdataObject_ResultInfo("SAPODataConnector.OdataObject_ResultInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VH_Language(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAP_Integration.VH_Language"));
	}

	protected VH_Language(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vH_LanguageMendixObject)
	{
		super(context, vH_LanguageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("SAP_Integration.VH_Language", vH_LanguageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAP_Integration.VH_Language");
	}

	/**
	 * @deprecated Use 'VH_Language.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sap_integration.proxies.VH_Language initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sap_integration.proxies.VH_Language.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sap_integration.proxies.VH_Language initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sap_integration.proxies.VH_Language(context, mendixObject);
	}

	public static sap_integration.proxies.VH_Language load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sap_integration.proxies.VH_Language.initialize(context, mendixObject);
	}

	/**
	 * @return value of Spras
	 */
	public final java.lang.String getSpras()
	{
		return getSpras(getContext());
	}

	/**
	 * @param context
	 * @return value of Spras
	 */
	public final java.lang.String getSpras(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Spras.toString());
	}

	/**
	 * Set value of Spras
	 * @param spras
	 */
	public final void setSpras(java.lang.String spras)
	{
		setSpras(getContext(), spras);
	}

	/**
	 * Set value of Spras
	 * @param context
	 * @param spras
	 */
	public final void setSpras(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spras)
	{
		getMendixObject().setValue(context, MemberNames.Spras.toString(), spras);
	}

	/**
	 * @return value of Sptxt
	 */
	public final java.lang.String getSptxt()
	{
		return getSptxt(getContext());
	}

	/**
	 * @param context
	 * @return value of Sptxt
	 */
	public final java.lang.String getSptxt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sptxt.toString());
	}

	/**
	 * Set value of Sptxt
	 * @param sptxt
	 */
	public final void setSptxt(java.lang.String sptxt)
	{
		setSptxt(getContext(), sptxt);
	}

	/**
	 * Set value of Sptxt
	 * @param context
	 * @param sptxt
	 */
	public final void setSptxt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sptxt)
	{
		getMendixObject().setValue(context, MemberNames.Sptxt.toString(), sptxt);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sap_integration.proxies.VH_Language that = (sap_integration.proxies.VH_Language) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAP_Integration.VH_Language";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
