// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class BillPDF extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.BillPDF";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		BillPDF_Bill("MasterData.BillPDF_Bill");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BillPDF(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.BillPDF"));
	}

	protected BillPDF(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billPDFMendixObject)
	{
		super(context, billPDFMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MasterData.BillPDF", billPDFMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.BillPDF");
	}

	/**
	 * @deprecated Use 'BillPDF.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.BillPDF initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.BillPDF.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.BillPDF initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.BillPDF(context, mendixObject);
	}

	public static masterdata.proxies.BillPDF load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.BillPDF.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.BillPDF> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.BillPDF> result = new java.util.ArrayList<masterdata.proxies.BillPDF>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.BillPDF" + xpathConstraint))
			result.add(masterdata.proxies.BillPDF.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of BillPDF_Bill
	 */
	public final masterdata.proxies.Bill getBillPDF_Bill() throws com.mendix.core.CoreException
	{
		return getBillPDF_Bill(getContext());
	}

	/**
	 * @param context
	 * @return value of BillPDF_Bill
	 */
	public final masterdata.proxies.Bill getBillPDF_Bill(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Bill result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillPDF_Bill.toString());
		if (identifier != null)
			result = masterdata.proxies.Bill.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillPDF_Bill
	 * @param billpdf_bill
	 */
	public final void setBillPDF_Bill(masterdata.proxies.Bill billpdf_bill)
	{
		setBillPDF_Bill(getContext(), billpdf_bill);
	}

	/**
	 * Set value of BillPDF_Bill
	 * @param context
	 * @param billpdf_bill
	 */
	public final void setBillPDF_Bill(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Bill billpdf_bill)
	{
		if (billpdf_bill == null)
			getMendixObject().setValue(context, MemberNames.BillPDF_Bill.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillPDF_Bill.toString(), billpdf_bill.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.BillPDF that = (masterdata.proxies.BillPDF) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.BillPDF";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
