// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Bill
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject billMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Bill";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Amount("Amount"),
		Status("Status"),
		Date("Date"),
		PDFAvailable("PDFAvailable"),
		NetAmount("NetAmount"),
		VATAmount("VATAmount"),
		Bill_Customer("MasterData.Bill_Customer"),
		BillPDF_Bill("MasterData.BillPDF_Bill"),
		BillDOCX_Bill("MasterData.BillDOCX_Bill");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Bill(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.Bill"));
	}

	protected Bill(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billMendixObject)
	{
		if (billMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MasterData.Bill", billMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.Bill");

		this.billMendixObject = billMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Bill.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.Bill initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.Bill.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.Bill initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Bill(context, mendixObject);
	}

	public static masterdata.proxies.Bill load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Bill.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Bill> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.Bill> result = new java.util.ArrayList<masterdata.proxies.Bill>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.Bill" + xpathConstraint))
			result.add(masterdata.proxies.Bill.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final masterdata.proxies.ENUM_BillingStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final masterdata.proxies.ENUM_BillingStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return masterdata.proxies.ENUM_BillingStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(masterdata.proxies.ENUM_BillingStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.ENUM_BillingStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of PDFAvailable
	 */
	public final java.lang.Boolean getPDFAvailable()
	{
		return getPDFAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of PDFAvailable
	 */
	public final java.lang.Boolean getPDFAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PDFAvailable.toString());
	}

	/**
	 * Set value of PDFAvailable
	 * @param pdfavailable
	 */
	public final void setPDFAvailable(java.lang.Boolean pdfavailable)
	{
		setPDFAvailable(getContext(), pdfavailable);
	}

	/**
	 * Set value of PDFAvailable
	 * @param context
	 * @param pdfavailable
	 */
	public final void setPDFAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean pdfavailable)
	{
		getMendixObject().setValue(context, MemberNames.PDFAvailable.toString(), pdfavailable);
	}

	/**
	 * @return value of NetAmount
	 */
	public final java.math.BigDecimal getNetAmount()
	{
		return getNetAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of NetAmount
	 */
	public final java.math.BigDecimal getNetAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetAmount.toString());
	}

	/**
	 * Set value of NetAmount
	 * @param netamount
	 */
	public final void setNetAmount(java.math.BigDecimal netamount)
	{
		setNetAmount(getContext(), netamount);
	}

	/**
	 * Set value of NetAmount
	 * @param context
	 * @param netamount
	 */
	public final void setNetAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal netamount)
	{
		getMendixObject().setValue(context, MemberNames.NetAmount.toString(), netamount);
	}

	/**
	 * @return value of VATAmount
	 */
	public final java.math.BigDecimal getVATAmount()
	{
		return getVATAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of VATAmount
	 */
	public final java.math.BigDecimal getVATAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.VATAmount.toString());
	}

	/**
	 * Set value of VATAmount
	 * @param vatamount
	 */
	public final void setVATAmount(java.math.BigDecimal vatamount)
	{
		setVATAmount(getContext(), vatamount);
	}

	/**
	 * Set value of VATAmount
	 * @param context
	 * @param vatamount
	 */
	public final void setVATAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal vatamount)
	{
		getMendixObject().setValue(context, MemberNames.VATAmount.toString(), vatamount);
	}

	/**
	 * @return value of Bill_Customer
	 */
	public final masterdata.proxies.Customer getBill_Customer() throws com.mendix.core.CoreException
	{
		return getBill_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of Bill_Customer
	 */
	public final masterdata.proxies.Customer getBill_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Bill_Customer.toString());
		if (identifier != null)
			result = masterdata.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Bill_Customer
	 * @param bill_customer
	 */
	public final void setBill_Customer(masterdata.proxies.Customer bill_customer)
	{
		setBill_Customer(getContext(), bill_customer);
	}

	/**
	 * Set value of Bill_Customer
	 * @param context
	 * @param bill_customer
	 */
	public final void setBill_Customer(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Customer bill_customer)
	{
		if (bill_customer == null)
			getMendixObject().setValue(context, MemberNames.Bill_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Bill_Customer.toString(), bill_customer.getMendixObject().getId());
	}

	/**
	 * @return value of BillPDF_Bill
	 */
	public final masterdata.proxies.BillPDF getBillPDF_Bill() throws com.mendix.core.CoreException
	{
		return getBillPDF_Bill(getContext());
	}

	/**
	 * @param context
	 * @return value of BillPDF_Bill
	 */
	public final masterdata.proxies.BillPDF getBillPDF_Bill(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.BillPDF result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillPDF_Bill.toString());
		if (identifier != null)
			result = masterdata.proxies.BillPDF.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillPDF_Bill
	 * @param billpdf_bill
	 */
	public final void setBillPDF_Bill(masterdata.proxies.BillPDF billpdf_bill)
	{
		setBillPDF_Bill(getContext(), billpdf_bill);
	}

	/**
	 * Set value of BillPDF_Bill
	 * @param context
	 * @param billpdf_bill
	 */
	public final void setBillPDF_Bill(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.BillPDF billpdf_bill)
	{
		if (billpdf_bill == null)
			getMendixObject().setValue(context, MemberNames.BillPDF_Bill.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillPDF_Bill.toString(), billpdf_bill.getMendixObject().getId());
	}

	/**
	 * @return value of BillDOCX_Bill
	 */
	public final masterdata.proxies.BillDOCX getBillDOCX_Bill() throws com.mendix.core.CoreException
	{
		return getBillDOCX_Bill(getContext());
	}

	/**
	 * @param context
	 * @return value of BillDOCX_Bill
	 */
	public final masterdata.proxies.BillDOCX getBillDOCX_Bill(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.BillDOCX result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillDOCX_Bill.toString());
		if (identifier != null)
			result = masterdata.proxies.BillDOCX.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillDOCX_Bill
	 * @param billdocx_bill
	 */
	public final void setBillDOCX_Bill(masterdata.proxies.BillDOCX billdocx_bill)
	{
		setBillDOCX_Bill(getContext(), billdocx_bill);
	}

	/**
	 * Set value of BillDOCX_Bill
	 * @param context
	 * @param billdocx_bill
	 */
	public final void setBillDOCX_Bill(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.BillDOCX billdocx_bill)
	{
		if (billdocx_bill == null)
			getMendixObject().setValue(context, MemberNames.BillDOCX_Bill.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillDOCX_Bill.toString(), billdocx_bill.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return billMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Bill that = (masterdata.proxies.Bill) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.Bill";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
