// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class BillItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject billItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.BillItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ProductID("ProductID"),
		Quantity("Quantity"),
		NetPrice("NetPrice"),
		VAT("VAT"),
		TotalPrice("TotalPrice"),
		NetPriceEach("NetPriceEach"),
		Name("Name"),
		BillItem_Bill("MasterData.BillItem_Bill");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BillItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.BillItem"));
	}

	protected BillItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billItemMendixObject)
	{
		if (billItemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MasterData.BillItem", billItemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.BillItem");

		this.billItemMendixObject = billItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BillItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.BillItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.BillItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.BillItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.BillItem(context, mendixObject);
	}

	public static masterdata.proxies.BillItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.BillItem.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.BillItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.BillItem> result = new java.util.ArrayList<masterdata.proxies.BillItem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.BillItem" + xpathConstraint))
			result.add(masterdata.proxies.BillItem.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ProductID
	 */
	public final java.lang.String getProductID()
	{
		return getProductID(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductID
	 */
	public final java.lang.String getProductID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProductID.toString());
	}

	/**
	 * Set value of ProductID
	 * @param productid
	 */
	public final void setProductID(java.lang.String productid)
	{
		setProductID(getContext(), productid);
	}

	/**
	 * Set value of ProductID
	 * @param context
	 * @param productid
	 */
	public final void setProductID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String productid)
	{
		getMendixObject().setValue(context, MemberNames.ProductID.toString(), productid);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of NetPrice
	 */
	public final java.math.BigDecimal getNetPrice()
	{
		return getNetPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of NetPrice
	 */
	public final java.math.BigDecimal getNetPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetPrice.toString());
	}

	/**
	 * Set value of NetPrice
	 * @param netprice
	 */
	public final void setNetPrice(java.math.BigDecimal netprice)
	{
		setNetPrice(getContext(), netprice);
	}

	/**
	 * Set value of NetPrice
	 * @param context
	 * @param netprice
	 */
	public final void setNetPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal netprice)
	{
		getMendixObject().setValue(context, MemberNames.NetPrice.toString(), netprice);
	}

	/**
	 * @return value of VAT
	 */
	public final java.math.BigDecimal getVAT()
	{
		return getVAT(getContext());
	}

	/**
	 * @param context
	 * @return value of VAT
	 */
	public final java.math.BigDecimal getVAT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.VAT.toString());
	}

	/**
	 * Set value of VAT
	 * @param vat
	 */
	public final void setVAT(java.math.BigDecimal vat)
	{
		setVAT(getContext(), vat);
	}

	/**
	 * Set value of VAT
	 * @param context
	 * @param vat
	 */
	public final void setVAT(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal vat)
	{
		getMendixObject().setValue(context, MemberNames.VAT.toString(), vat);
	}

	/**
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice()
	{
		return getTotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPrice.toString());
	}

	/**
	 * Set value of TotalPrice
	 * @param totalprice
	 */
	public final void setTotalPrice(java.math.BigDecimal totalprice)
	{
		setTotalPrice(getContext(), totalprice);
	}

	/**
	 * Set value of TotalPrice
	 * @param context
	 * @param totalprice
	 */
	public final void setTotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalprice)
	{
		getMendixObject().setValue(context, MemberNames.TotalPrice.toString(), totalprice);
	}

	/**
	 * @return value of NetPriceEach
	 */
	public final java.math.BigDecimal getNetPriceEach()
	{
		return getNetPriceEach(getContext());
	}

	/**
	 * @param context
	 * @return value of NetPriceEach
	 */
	public final java.math.BigDecimal getNetPriceEach(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NetPriceEach.toString());
	}

	/**
	 * Set value of NetPriceEach
	 * @param netpriceeach
	 */
	public final void setNetPriceEach(java.math.BigDecimal netpriceeach)
	{
		setNetPriceEach(getContext(), netpriceeach);
	}

	/**
	 * Set value of NetPriceEach
	 * @param context
	 * @param netpriceeach
	 */
	public final void setNetPriceEach(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal netpriceeach)
	{
		getMendixObject().setValue(context, MemberNames.NetPriceEach.toString(), netpriceeach);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of BillItem_Bill
	 */
	public final masterdata.proxies.Bill getBillItem_Bill() throws com.mendix.core.CoreException
	{
		return getBillItem_Bill(getContext());
	}

	/**
	 * @param context
	 * @return value of BillItem_Bill
	 */
	public final masterdata.proxies.Bill getBillItem_Bill(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Bill result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillItem_Bill.toString());
		if (identifier != null)
			result = masterdata.proxies.Bill.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillItem_Bill
	 * @param billitem_bill
	 */
	public final void setBillItem_Bill(masterdata.proxies.Bill billitem_bill)
	{
		setBillItem_Bill(getContext(), billitem_bill);
	}

	/**
	 * Set value of BillItem_Bill
	 * @param context
	 * @param billitem_bill
	 */
	public final void setBillItem_Bill(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Bill billitem_bill)
	{
		if (billitem_bill == null)
			getMendixObject().setValue(context, MemberNames.BillItem_Bill.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillItem_Bill.toString(), billitem_bill.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return billItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.BillItem that = (masterdata.proxies.BillItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.BillItem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
