// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class BillDOCX extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.BillDOCX";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		BillDOCX_Bill("MasterData.BillDOCX_Bill");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BillDOCX(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.BillDOCX"));
	}

	protected BillDOCX(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject billDOCXMendixObject)
	{
		super(context, billDOCXMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MasterData.BillDOCX", billDOCXMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.BillDOCX");
	}

	/**
	 * @deprecated Use 'BillDOCX.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.BillDOCX initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.BillDOCX.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.BillDOCX initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.BillDOCX(context, mendixObject);
	}

	public static masterdata.proxies.BillDOCX load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.BillDOCX.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.BillDOCX> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.BillDOCX> result = new java.util.ArrayList<masterdata.proxies.BillDOCX>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.BillDOCX" + xpathConstraint))
			result.add(masterdata.proxies.BillDOCX.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of BillDOCX_Bill
	 */
	public final masterdata.proxies.Bill getBillDOCX_Bill() throws com.mendix.core.CoreException
	{
		return getBillDOCX_Bill(getContext());
	}

	/**
	 * @param context
	 * @return value of BillDOCX_Bill
	 */
	public final masterdata.proxies.Bill getBillDOCX_Bill(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Bill result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BillDOCX_Bill.toString());
		if (identifier != null)
			result = masterdata.proxies.Bill.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BillDOCX_Bill
	 * @param billdocx_bill
	 */
	public final void setBillDOCX_Bill(masterdata.proxies.Bill billdocx_bill)
	{
		setBillDOCX_Bill(getContext(), billdocx_bill);
	}

	/**
	 * Set value of BillDOCX_Bill
	 * @param context
	 * @param billdocx_bill
	 */
	public final void setBillDOCX_Bill(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Bill billdocx_bill)
	{
		if (billdocx_bill == null)
			getMendixObject().setValue(context, MemberNames.BillDOCX_Bill.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BillDOCX_Bill.toString(), billdocx_bill.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.BillDOCX that = (masterdata.proxies.BillDOCX) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.BillDOCX";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
