// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class IncidentReportPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.IncidentReportPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FoundObjects("FoundObjects"),
		Labels("Labels"),
		Brand("Brand"),
		AIUsed("AIUsed"),
		BestHit("BestHit"),
		HasWatermark("HasWatermark"),
		ContainsFixableItems("ContainsFixableItems"),
		DemoData("DemoData"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		IncidentReportPhoto_Incident("MasterData.IncidentReportPhoto_Incident");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IncidentReportPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.IncidentReportPhoto"));
	}

	protected IncidentReportPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject incidentReportPhotoMendixObject)
	{
		super(context, incidentReportPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MasterData.IncidentReportPhoto", incidentReportPhotoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.IncidentReportPhoto");
	}

	/**
	 * @deprecated Use 'IncidentReportPhoto.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.IncidentReportPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.IncidentReportPhoto.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.IncidentReportPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.IncidentReportPhoto(context, mendixObject);
	}

	public static masterdata.proxies.IncidentReportPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.IncidentReportPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.IncidentReportPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.IncidentReportPhoto> result = new java.util.ArrayList<masterdata.proxies.IncidentReportPhoto>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.IncidentReportPhoto" + xpathConstraint))
			result.add(masterdata.proxies.IncidentReportPhoto.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FoundObjects
	 */
	public final java.lang.String getFoundObjects()
	{
		return getFoundObjects(getContext());
	}

	/**
	 * @param context
	 * @return value of FoundObjects
	 */
	public final java.lang.String getFoundObjects(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FoundObjects.toString());
	}

	/**
	 * Set value of FoundObjects
	 * @param foundobjects
	 */
	public final void setFoundObjects(java.lang.String foundobjects)
	{
		setFoundObjects(getContext(), foundobjects);
	}

	/**
	 * Set value of FoundObjects
	 * @param context
	 * @param foundobjects
	 */
	public final void setFoundObjects(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String foundobjects)
	{
		getMendixObject().setValue(context, MemberNames.FoundObjects.toString(), foundobjects);
	}

	/**
	 * @return value of Labels
	 */
	public final java.lang.String getLabels()
	{
		return getLabels(getContext());
	}

	/**
	 * @param context
	 * @return value of Labels
	 */
	public final java.lang.String getLabels(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Labels.toString());
	}

	/**
	 * Set value of Labels
	 * @param labels
	 */
	public final void setLabels(java.lang.String labels)
	{
		setLabels(getContext(), labels);
	}

	/**
	 * Set value of Labels
	 * @param context
	 * @param labels
	 */
	public final void setLabels(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String labels)
	{
		getMendixObject().setValue(context, MemberNames.Labels.toString(), labels);
	}

	/**
	 * @return value of Brand
	 */
	public final java.lang.String getBrand()
	{
		return getBrand(getContext());
	}

	/**
	 * @param context
	 * @return value of Brand
	 */
	public final java.lang.String getBrand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Brand.toString());
	}

	/**
	 * Set value of Brand
	 * @param brand
	 */
	public final void setBrand(java.lang.String brand)
	{
		setBrand(getContext(), brand);
	}

	/**
	 * Set value of Brand
	 * @param context
	 * @param brand
	 */
	public final void setBrand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brand)
	{
		getMendixObject().setValue(context, MemberNames.Brand.toString(), brand);
	}

	/**
	 * @return value of AIUsed
	 */
	public final java.lang.Boolean getAIUsed()
	{
		return getAIUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of AIUsed
	 */
	public final java.lang.Boolean getAIUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AIUsed.toString());
	}

	/**
	 * Set value of AIUsed
	 * @param aiused
	 */
	public final void setAIUsed(java.lang.Boolean aiused)
	{
		setAIUsed(getContext(), aiused);
	}

	/**
	 * Set value of AIUsed
	 * @param context
	 * @param aiused
	 */
	public final void setAIUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean aiused)
	{
		getMendixObject().setValue(context, MemberNames.AIUsed.toString(), aiused);
	}

	/**
	 * @return value of BestHit
	 */
	public final java.math.BigDecimal getBestHit()
	{
		return getBestHit(getContext());
	}

	/**
	 * @param context
	 * @return value of BestHit
	 */
	public final java.math.BigDecimal getBestHit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BestHit.toString());
	}

	/**
	 * Set value of BestHit
	 * @param besthit
	 */
	public final void setBestHit(java.math.BigDecimal besthit)
	{
		setBestHit(getContext(), besthit);
	}

	/**
	 * Set value of BestHit
	 * @param context
	 * @param besthit
	 */
	public final void setBestHit(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal besthit)
	{
		getMendixObject().setValue(context, MemberNames.BestHit.toString(), besthit);
	}

	/**
	 * @return value of HasWatermark
	 */
	public final java.lang.Boolean getHasWatermark()
	{
		return getHasWatermark(getContext());
	}

	/**
	 * @param context
	 * @return value of HasWatermark
	 */
	public final java.lang.Boolean getHasWatermark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasWatermark.toString());
	}

	/**
	 * Set value of HasWatermark
	 * @param haswatermark
	 */
	public final void setHasWatermark(java.lang.Boolean haswatermark)
	{
		setHasWatermark(getContext(), haswatermark);
	}

	/**
	 * Set value of HasWatermark
	 * @param context
	 * @param haswatermark
	 */
	public final void setHasWatermark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haswatermark)
	{
		getMendixObject().setValue(context, MemberNames.HasWatermark.toString(), haswatermark);
	}

	/**
	 * @return value of ContainsFixableItems
	 */
	public final java.lang.Boolean getContainsFixableItems()
	{
		return getContainsFixableItems(getContext());
	}

	/**
	 * @param context
	 * @return value of ContainsFixableItems
	 */
	public final java.lang.Boolean getContainsFixableItems(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ContainsFixableItems.toString());
	}

	/**
	 * Set value of ContainsFixableItems
	 * @param containsfixableitems
	 */
	public final void setContainsFixableItems(java.lang.Boolean containsfixableitems)
	{
		setContainsFixableItems(getContext(), containsfixableitems);
	}

	/**
	 * Set value of ContainsFixableItems
	 * @param context
	 * @param containsfixableitems
	 */
	public final void setContainsFixableItems(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean containsfixableitems)
	{
		getMendixObject().setValue(context, MemberNames.ContainsFixableItems.toString(), containsfixableitems);
	}

	/**
	 * @return value of DemoData
	 */
	public final java.lang.Boolean getDemoData()
	{
		return getDemoData(getContext());
	}

	/**
	 * @param context
	 * @return value of DemoData
	 */
	public final java.lang.Boolean getDemoData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DemoData.toString());
	}

	/**
	 * Set value of DemoData
	 * @param demodata
	 */
	public final void setDemoData(java.lang.Boolean demodata)
	{
		setDemoData(getContext(), demodata);
	}

	/**
	 * Set value of DemoData
	 * @param context
	 * @param demodata
	 */
	public final void setDemoData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean demodata)
	{
		getMendixObject().setValue(context, MemberNames.DemoData.toString(), demodata);
	}

	/**
	 * @return value of IncidentReportPhoto_Incident
	 */
	public final masterdata.proxies.Incident getIncidentReportPhoto_Incident() throws com.mendix.core.CoreException
	{
		return getIncidentReportPhoto_Incident(getContext());
	}

	/**
	 * @param context
	 * @return value of IncidentReportPhoto_Incident
	 */
	public final masterdata.proxies.Incident getIncidentReportPhoto_Incident(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Incident result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IncidentReportPhoto_Incident.toString());
		if (identifier != null)
			result = masterdata.proxies.Incident.load(context, identifier);
		return result;
	}

	/**
	 * Set value of IncidentReportPhoto_Incident
	 * @param incidentreportphoto_incident
	 */
	public final void setIncidentReportPhoto_Incident(masterdata.proxies.Incident incidentreportphoto_incident)
	{
		setIncidentReportPhoto_Incident(getContext(), incidentreportphoto_incident);
	}

	/**
	 * Set value of IncidentReportPhoto_Incident
	 * @param context
	 * @param incidentreportphoto_incident
	 */
	public final void setIncidentReportPhoto_Incident(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Incident incidentreportphoto_incident)
	{
		if (incidentreportphoto_incident == null)
			getMendixObject().setValue(context, MemberNames.IncidentReportPhoto_Incident.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.IncidentReportPhoto_Incident.toString(), incidentreportphoto_incident.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.IncidentReportPhoto that = (masterdata.proxies.IncidentReportPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.IncidentReportPhoto";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
