// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Incident extends system.proxies.WorkflowContext
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Incident";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IncidentNumber("IncidentNumber"),
		Description("Description"),
		Priority("Priority"),
		SubmittedDate("SubmittedDate"),
		Device("Device"),
		Notified("Notified"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Address("Address"),
		Rating("Rating"),
		LeftRating("LeftRating"),
		RepairCost("RepairCost"),
		ShowMap("ShowMap"),
		DateCreated("DateCreated"),
		Incident_Customer("MasterData.Incident_Customer"),
		Incident_ServiceEngineer("MasterData.Incident_ServiceEngineer"),
		WorkflowInstance_WorkflowContext("System.WorkflowInstance_WorkflowContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Incident(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.Incident"));
	}

	protected Incident(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject incidentMendixObject)
	{
		super(context, incidentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MasterData.Incident", incidentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.Incident");
	}

	/**
	 * @deprecated Use 'Incident.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.Incident initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.Incident.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.Incident initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Incident(context, mendixObject);
	}

	public static masterdata.proxies.Incident load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Incident.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Incident> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.Incident> result = new java.util.ArrayList<masterdata.proxies.Incident>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.Incident" + xpathConstraint))
			result.add(masterdata.proxies.Incident.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of IncidentNumber
	 */
	public final java.lang.String getIncidentNumber()
	{
		return getIncidentNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of IncidentNumber
	 */
	public final java.lang.String getIncidentNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IncidentNumber.toString());
	}

	/**
	 * Set value of IncidentNumber
	 * @param incidentnumber
	 */
	public final void setIncidentNumber(java.lang.String incidentnumber)
	{
		setIncidentNumber(getContext(), incidentnumber);
	}

	/**
	 * Set value of IncidentNumber
	 * @param context
	 * @param incidentnumber
	 */
	public final void setIncidentNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String incidentnumber)
	{
		getMendixObject().setValue(context, MemberNames.IncidentNumber.toString(), incidentnumber);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final masterdata.proxies.Priority getPriority()
	{
		return getPriority(getContext());
	}

	/**
	 * @param context
	 * @return value of Priority
	 */
	public final masterdata.proxies.Priority getPriority(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Priority.toString());
		if (obj == null)
			return null;

		return masterdata.proxies.Priority.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Priority
	 * @param priority
	 */
	public final void setPriority(masterdata.proxies.Priority priority)
	{
		setPriority(getContext(), priority);
	}

	/**
	 * Set value of Priority
	 * @param context
	 * @param priority
	 */
	public final void setPriority(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Priority priority)
	{
		if (priority != null)
			getMendixObject().setValue(context, MemberNames.Priority.toString(), priority.toString());
		else
			getMendixObject().setValue(context, MemberNames.Priority.toString(), null);
	}

	/**
	 * @return value of SubmittedDate
	 */
	public final java.util.Date getSubmittedDate()
	{
		return getSubmittedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmittedDate
	 */
	public final java.util.Date getSubmittedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SubmittedDate.toString());
	}

	/**
	 * Set value of SubmittedDate
	 * @param submitteddate
	 */
	public final void setSubmittedDate(java.util.Date submitteddate)
	{
		setSubmittedDate(getContext(), submitteddate);
	}

	/**
	 * Set value of SubmittedDate
	 * @param context
	 * @param submitteddate
	 */
	public final void setSubmittedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date submitteddate)
	{
		getMendixObject().setValue(context, MemberNames.SubmittedDate.toString(), submitteddate);
	}

	/**
	 * Set value of Device
	 * @param device
	 */
	public final masterdata.proxies.DeviceType getDevice()
	{
		return getDevice(getContext());
	}

	/**
	 * @param context
	 * @return value of Device
	 */
	public final masterdata.proxies.DeviceType getDevice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Device.toString());
		if (obj == null)
			return null;

		return masterdata.proxies.DeviceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Device
	 * @param device
	 */
	public final void setDevice(masterdata.proxies.DeviceType device)
	{
		setDevice(getContext(), device);
	}

	/**
	 * Set value of Device
	 * @param context
	 * @param device
	 */
	public final void setDevice(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.DeviceType device)
	{
		if (device != null)
			getMendixObject().setValue(context, MemberNames.Device.toString(), device.toString());
		else
			getMendixObject().setValue(context, MemberNames.Device.toString(), null);
	}

	/**
	 * @return value of Notified
	 */
	public final java.lang.Boolean getNotified()
	{
		return getNotified(getContext());
	}

	/**
	 * @param context
	 * @return value of Notified
	 */
	public final java.lang.Boolean getNotified(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Notified.toString());
	}

	/**
	 * Set value of Notified
	 * @param notified
	 */
	public final void setNotified(java.lang.Boolean notified)
	{
		setNotified(getContext(), notified);
	}

	/**
	 * Set value of Notified
	 * @param context
	 * @param notified
	 */
	public final void setNotified(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notified)
	{
		getMendixObject().setValue(context, MemberNames.Notified.toString(), notified);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating()
	{
		return getRating(getContext());
	}

	/**
	 * @param context
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Rating.toString());
	}

	/**
	 * Set value of Rating
	 * @param rating
	 */
	public final void setRating(java.math.BigDecimal rating)
	{
		setRating(getContext(), rating);
	}

	/**
	 * Set value of Rating
	 * @param context
	 * @param rating
	 */
	public final void setRating(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rating)
	{
		getMendixObject().setValue(context, MemberNames.Rating.toString(), rating);
	}

	/**
	 * @return value of LeftRating
	 */
	public final java.lang.Boolean getLeftRating()
	{
		return getLeftRating(getContext());
	}

	/**
	 * @param context
	 * @return value of LeftRating
	 */
	public final java.lang.Boolean getLeftRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.LeftRating.toString());
	}

	/**
	 * Set value of LeftRating
	 * @param leftrating
	 */
	public final void setLeftRating(java.lang.Boolean leftrating)
	{
		setLeftRating(getContext(), leftrating);
	}

	/**
	 * Set value of LeftRating
	 * @param context
	 * @param leftrating
	 */
	public final void setLeftRating(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean leftrating)
	{
		getMendixObject().setValue(context, MemberNames.LeftRating.toString(), leftrating);
	}

	/**
	 * @return value of RepairCost
	 */
	public final java.math.BigDecimal getRepairCost()
	{
		return getRepairCost(getContext());
	}

	/**
	 * @param context
	 * @return value of RepairCost
	 */
	public final java.math.BigDecimal getRepairCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RepairCost.toString());
	}

	/**
	 * Set value of RepairCost
	 * @param repaircost
	 */
	public final void setRepairCost(java.math.BigDecimal repaircost)
	{
		setRepairCost(getContext(), repaircost);
	}

	/**
	 * Set value of RepairCost
	 * @param context
	 * @param repaircost
	 */
	public final void setRepairCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal repaircost)
	{
		getMendixObject().setValue(context, MemberNames.RepairCost.toString(), repaircost);
	}

	/**
	 * @return value of ShowMap
	 */
	public final java.lang.Boolean getShowMap()
	{
		return getShowMap(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowMap
	 */
	public final java.lang.Boolean getShowMap(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowMap.toString());
	}

	/**
	 * Set value of ShowMap
	 * @param showmap
	 */
	public final void setShowMap(java.lang.Boolean showmap)
	{
		setShowMap(getContext(), showmap);
	}

	/**
	 * Set value of ShowMap
	 * @param context
	 * @param showmap
	 */
	public final void setShowMap(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showmap)
	{
		getMendixObject().setValue(context, MemberNames.ShowMap.toString(), showmap);
	}

	/**
	 * @return value of DateCreated
	 */
	public final java.util.Date getDateCreated()
	{
		return getDateCreated(getContext());
	}

	/**
	 * @param context
	 * @return value of DateCreated
	 */
	public final java.util.Date getDateCreated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateCreated.toString());
	}

	/**
	 * Set value of DateCreated
	 * @param datecreated
	 */
	public final void setDateCreated(java.util.Date datecreated)
	{
		setDateCreated(getContext(), datecreated);
	}

	/**
	 * Set value of DateCreated
	 * @param context
	 * @param datecreated
	 */
	public final void setDateCreated(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datecreated)
	{
		getMendixObject().setValue(context, MemberNames.DateCreated.toString(), datecreated);
	}

	/**
	 * @return value of Incident_Customer
	 */
	public final masterdata.proxies.Customer getIncident_Customer() throws com.mendix.core.CoreException
	{
		return getIncident_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of Incident_Customer
	 */
	public final masterdata.proxies.Customer getIncident_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Incident_Customer.toString());
		if (identifier != null)
			result = masterdata.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Incident_Customer
	 * @param incident_customer
	 */
	public final void setIncident_Customer(masterdata.proxies.Customer incident_customer)
	{
		setIncident_Customer(getContext(), incident_customer);
	}

	/**
	 * Set value of Incident_Customer
	 * @param context
	 * @param incident_customer
	 */
	public final void setIncident_Customer(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Customer incident_customer)
	{
		if (incident_customer == null)
			getMendixObject().setValue(context, MemberNames.Incident_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Incident_Customer.toString(), incident_customer.getMendixObject().getId());
	}

	/**
	 * @return value of Incident_ServiceEngineer
	 */
	public final masterdata.proxies.ServiceEngineer getIncident_ServiceEngineer() throws com.mendix.core.CoreException
	{
		return getIncident_ServiceEngineer(getContext());
	}

	/**
	 * @param context
	 * @return value of Incident_ServiceEngineer
	 */
	public final masterdata.proxies.ServiceEngineer getIncident_ServiceEngineer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.ServiceEngineer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Incident_ServiceEngineer.toString());
		if (identifier != null)
			result = masterdata.proxies.ServiceEngineer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Incident_ServiceEngineer
	 * @param incident_serviceengineer
	 */
	public final void setIncident_ServiceEngineer(masterdata.proxies.ServiceEngineer incident_serviceengineer)
	{
		setIncident_ServiceEngineer(getContext(), incident_serviceengineer);
	}

	/**
	 * Set value of Incident_ServiceEngineer
	 * @param context
	 * @param incident_serviceengineer
	 */
	public final void setIncident_ServiceEngineer(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.ServiceEngineer incident_serviceengineer)
	{
		if (incident_serviceengineer == null)
			getMendixObject().setValue(context, MemberNames.Incident_ServiceEngineer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Incident_ServiceEngineer.toString(), incident_serviceengineer.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Incident that = (masterdata.proxies.Incident) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.Incident";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
