// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public enum MarkerImage
{
	Incident(new java.lang.String[][] { new java.lang.String[] { "en_US", "Incident" } }),
	ServicePerson1(new java.lang.String[][] { new java.lang.String[] { "en_US", "ServicePerson1" } }),
	ServicePerson2(new java.lang.String[][] { new java.lang.String[] { "en_US", "ServicePerson2" } }),
	ServicePerson3(new java.lang.String[][] { new java.lang.String[] { "en_US", "ServicePerson3" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private MarkerImage(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
