// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class ServiceEngineer extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.ServiceEngineer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		Available("Available"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Address("Address"),
		Image("Image"),
		Role("Role"),
		ProfilePicture("ProfilePicture"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ServiceEngineer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.ServiceEngineer"));
	}

	protected ServiceEngineer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceEngineerMendixObject)
	{
		super(context, serviceEngineerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MasterData.ServiceEngineer", serviceEngineerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.ServiceEngineer");
	}

	/**
	 * @deprecated Use 'ServiceEngineer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.ServiceEngineer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.ServiceEngineer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.ServiceEngineer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.ServiceEngineer(context, mendixObject);
	}

	public static masterdata.proxies.ServiceEngineer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.ServiceEngineer.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.ServiceEngineer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.ServiceEngineer> result = new java.util.ArrayList<masterdata.proxies.ServiceEngineer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.ServiceEngineer" + xpathConstraint))
			result.add(masterdata.proxies.ServiceEngineer.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of Available
	 */
	public final java.lang.Boolean getAvailable()
	{
		return getAvailable(getContext());
	}

	/**
	 * @param context
	 * @return value of Available
	 */
	public final java.lang.Boolean getAvailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Available.toString());
	}

	/**
	 * Set value of Available
	 * @param available
	 */
	public final void setAvailable(java.lang.Boolean available)
	{
		setAvailable(getContext(), available);
	}

	/**
	 * Set value of Available
	 * @param context
	 * @param available
	 */
	public final void setAvailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean available)
	{
		getMendixObject().setValue(context, MemberNames.Available.toString(), available);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * Set value of Image
	 * @param image
	 */
	public final masterdata.proxies.MarkerImage getImage()
	{
		return getImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Image
	 */
	public final masterdata.proxies.MarkerImage getImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Image.toString());
		if (obj == null)
			return null;

		return masterdata.proxies.MarkerImage.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Image
	 * @param image
	 */
	public final void setImage(masterdata.proxies.MarkerImage image)
	{
		setImage(getContext(), image);
	}

	/**
	 * Set value of Image
	 * @param context
	 * @param image
	 */
	public final void setImage(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.MarkerImage image)
	{
		if (image != null)
			getMendixObject().setValue(context, MemberNames.Image.toString(), image.toString());
		else
			getMendixObject().setValue(context, MemberNames.Image.toString(), null);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @return value of ProfilePicture
	 */
	public final java.lang.String getProfilePicture()
	{
		return getProfilePicture(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfilePicture
	 */
	public final java.lang.String getProfilePicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProfilePicture.toString());
	}

	/**
	 * Set value of ProfilePicture
	 * @param profilepicture
	 */
	public final void setProfilePicture(java.lang.String profilepicture)
	{
		setProfilePicture(getContext(), profilepicture);
	}

	/**
	 * Set value of ProfilePicture
	 * @param context
	 * @param profilepicture
	 */
	public final void setProfilePicture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profilepicture)
	{
		getMendixObject().setValue(context, MemberNames.ProfilePicture.toString(), profilepicture);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.ServiceEngineer that = (masterdata.proxies.ServiceEngineer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.ServiceEngineer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
