// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class UserData
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.UserData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Dataplan("Dataplan"),
		DataUsed("DataUsed"),
		DeltaUsedAndPlan("DeltaUsedAndPlan"),
		NewCreditInDays("NewCreditInDays"),
		CostOutsideBundle("CostOutsideBundle"),
		OutstandingBills("OutstandingBills"),
		UserData_Customer("MasterData.UserData_Customer");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MasterData.UserData"));
	}

	protected UserData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userDataMendixObject)
	{
		if (userDataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MasterData.UserData", userDataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MasterData.UserData");

		this.userDataMendixObject = userDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserData.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.UserData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.UserData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static masterdata.proxies.UserData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.UserData(context, mendixObject);
	}

	public static masterdata.proxies.UserData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.UserData.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.UserData> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.UserData> result = new java.util.ArrayList<masterdata.proxies.UserData>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MasterData.UserData" + xpathConstraint))
			result.add(masterdata.proxies.UserData.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Dataplan
	 */
	public final java.math.BigDecimal getDataplan()
	{
		return getDataplan(getContext());
	}

	/**
	 * @param context
	 * @return value of Dataplan
	 */
	public final java.math.BigDecimal getDataplan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Dataplan.toString());
	}

	/**
	 * Set value of Dataplan
	 * @param dataplan
	 */
	public final void setDataplan(java.math.BigDecimal dataplan)
	{
		setDataplan(getContext(), dataplan);
	}

	/**
	 * Set value of Dataplan
	 * @param context
	 * @param dataplan
	 */
	public final void setDataplan(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dataplan)
	{
		getMendixObject().setValue(context, MemberNames.Dataplan.toString(), dataplan);
	}

	/**
	 * @return value of DataUsed
	 */
	public final java.math.BigDecimal getDataUsed()
	{
		return getDataUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of DataUsed
	 */
	public final java.math.BigDecimal getDataUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DataUsed.toString());
	}

	/**
	 * Set value of DataUsed
	 * @param dataused
	 */
	public final void setDataUsed(java.math.BigDecimal dataused)
	{
		setDataUsed(getContext(), dataused);
	}

	/**
	 * Set value of DataUsed
	 * @param context
	 * @param dataused
	 */
	public final void setDataUsed(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dataused)
	{
		getMendixObject().setValue(context, MemberNames.DataUsed.toString(), dataused);
	}

	/**
	 * @return value of DeltaUsedAndPlan
	 */
	public final java.lang.String getDeltaUsedAndPlan()
	{
		return getDeltaUsedAndPlan(getContext());
	}

	/**
	 * @param context
	 * @return value of DeltaUsedAndPlan
	 */
	public final java.lang.String getDeltaUsedAndPlan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeltaUsedAndPlan.toString());
	}

	/**
	 * Set value of DeltaUsedAndPlan
	 * @param deltausedandplan
	 */
	public final void setDeltaUsedAndPlan(java.lang.String deltausedandplan)
	{
		setDeltaUsedAndPlan(getContext(), deltausedandplan);
	}

	/**
	 * Set value of DeltaUsedAndPlan
	 * @param context
	 * @param deltausedandplan
	 */
	public final void setDeltaUsedAndPlan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deltausedandplan)
	{
		getMendixObject().setValue(context, MemberNames.DeltaUsedAndPlan.toString(), deltausedandplan);
	}

	/**
	 * @return value of NewCreditInDays
	 */
	public final java.lang.Integer getNewCreditInDays()
	{
		return getNewCreditInDays(getContext());
	}

	/**
	 * @param context
	 * @return value of NewCreditInDays
	 */
	public final java.lang.Integer getNewCreditInDays(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NewCreditInDays.toString());
	}

	/**
	 * Set value of NewCreditInDays
	 * @param newcreditindays
	 */
	public final void setNewCreditInDays(java.lang.Integer newcreditindays)
	{
		setNewCreditInDays(getContext(), newcreditindays);
	}

	/**
	 * Set value of NewCreditInDays
	 * @param context
	 * @param newcreditindays
	 */
	public final void setNewCreditInDays(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer newcreditindays)
	{
		getMendixObject().setValue(context, MemberNames.NewCreditInDays.toString(), newcreditindays);
	}

	/**
	 * @return value of CostOutsideBundle
	 */
	public final java.math.BigDecimal getCostOutsideBundle()
	{
		return getCostOutsideBundle(getContext());
	}

	/**
	 * @param context
	 * @return value of CostOutsideBundle
	 */
	public final java.math.BigDecimal getCostOutsideBundle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CostOutsideBundle.toString());
	}

	/**
	 * Set value of CostOutsideBundle
	 * @param costoutsidebundle
	 */
	public final void setCostOutsideBundle(java.math.BigDecimal costoutsidebundle)
	{
		setCostOutsideBundle(getContext(), costoutsidebundle);
	}

	/**
	 * Set value of CostOutsideBundle
	 * @param context
	 * @param costoutsidebundle
	 */
	public final void setCostOutsideBundle(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal costoutsidebundle)
	{
		getMendixObject().setValue(context, MemberNames.CostOutsideBundle.toString(), costoutsidebundle);
	}

	/**
	 * @return value of OutstandingBills
	 */
	public final java.math.BigDecimal getOutstandingBills()
	{
		return getOutstandingBills(getContext());
	}

	/**
	 * @param context
	 * @return value of OutstandingBills
	 */
	public final java.math.BigDecimal getOutstandingBills(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OutstandingBills.toString());
	}

	/**
	 * Set value of OutstandingBills
	 * @param outstandingbills
	 */
	public final void setOutstandingBills(java.math.BigDecimal outstandingbills)
	{
		setOutstandingBills(getContext(), outstandingbills);
	}

	/**
	 * Set value of OutstandingBills
	 * @param context
	 * @param outstandingbills
	 */
	public final void setOutstandingBills(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal outstandingbills)
	{
		getMendixObject().setValue(context, MemberNames.OutstandingBills.toString(), outstandingbills);
	}

	/**
	 * @return value of UserData_Customer
	 */
	public final masterdata.proxies.Customer getUserData_Customer() throws com.mendix.core.CoreException
	{
		return getUserData_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of UserData_Customer
	 */
	public final masterdata.proxies.Customer getUserData_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserData_Customer.toString());
		if (identifier != null)
			result = masterdata.proxies.Customer.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserData_Customer
	 * @param userdata_customer
	 */
	public final void setUserData_Customer(masterdata.proxies.Customer userdata_customer)
	{
		setUserData_Customer(getContext(), userdata_customer);
	}

	/**
	 * Set value of UserData_Customer
	 * @param context
	 * @param userdata_customer
	 */
	public final void setUserData_Customer(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Customer userdata_customer)
	{
		if (userdata_customer == null)
			getMendixObject().setValue(context, MemberNames.UserData_Customer.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserData_Customer.toString(), userdata_customer.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.UserData that = (masterdata.proxies.UserData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MasterData.UserData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
