// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PushNotifications module

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PushNotifications.LogNode");
	}

	/**
	* Number of characters of the registration ids to write in log messages.
	*/
	public static java.lang.Long getRegistrationIdCutoff()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("PushNotifications.RegistrationIdCutoff");
	}
}