// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package homeautomationconnector.proxies;

public enum ColorTemperature
{
	Amber(new java.lang.String[][] { new java.lang.String[] { "en_US", "Amber" } }),
	Soft_White(new java.lang.String[][] { new java.lang.String[] { "en_US", "Soft White" } }),
	Bright_White(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bright White" } }),
	Neutral_White(new java.lang.String[][] { new java.lang.String[] { "en_US", "Neutral White" } }),
	Cool_White(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cool White" } }),
	Daylight(new java.lang.String[][] { new java.lang.String[] { "en_US", "Daylight" } }),
	Daylight_Deluxe(new java.lang.String[][] { new java.lang.String[] { "en_US", "Daylight Deluxe" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ColorTemperature(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
