// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package homeautomationconnector.proxies;

public enum Color
{
	Crimson(new java.lang.String[][] { new java.lang.String[] { "en_US", "Crimson" } }),
	Dark_Orange(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dark Orange" } }),
	Gold(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gold" } }),
	Violet(new java.lang.String[][] { new java.lang.String[] { "en_US", "Violet" } }),
	Light_Green(new java.lang.String[][] { new java.lang.String[] { "en_US", "Light Green" } }),
	Deep_Sky_Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Deep Sky Blue" } }),
	Navy_Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Navy Blue" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Color(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
