// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package homeautomationconnector.proxies;

public class StateRequestAll_XY
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stateRequestAll_XYMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HomeAutomationConnector.StateRequestAll_XY";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		on("on"),
		bri("bri"),
		alert("alert"),
		XY_StateRequestAll_XY("HomeAutomationConnector.XY_StateRequestAll_XY");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StateRequestAll_XY(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "HomeAutomationConnector.StateRequestAll_XY"));
	}

	protected StateRequestAll_XY(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stateRequestAll_XYMendixObject)
	{
		if (stateRequestAll_XYMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("HomeAutomationConnector.StateRequestAll_XY", stateRequestAll_XYMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a HomeAutomationConnector.StateRequestAll_XY");

		this.stateRequestAll_XYMendixObject = stateRequestAll_XYMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StateRequestAll_XY.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static homeautomationconnector.proxies.StateRequestAll_XY initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return homeautomationconnector.proxies.StateRequestAll_XY.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static homeautomationconnector.proxies.StateRequestAll_XY initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new homeautomationconnector.proxies.StateRequestAll_XY(context, mendixObject);
	}

	public static homeautomationconnector.proxies.StateRequestAll_XY load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return homeautomationconnector.proxies.StateRequestAll_XY.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of on
	 */
	public final java.lang.Boolean geton()
	{
		return geton(getContext());
	}

	/**
	 * @param context
	 * @return value of on
	 */
	public final java.lang.Boolean geton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.on.toString());
	}

	/**
	 * Set value of on
	 * @param on
	 */
	public final void seton(java.lang.Boolean on)
	{
		seton(getContext(), on);
	}

	/**
	 * Set value of on
	 * @param context
	 * @param on
	 */
	public final void seton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean on)
	{
		getMendixObject().setValue(context, MemberNames.on.toString(), on);
	}

	/**
	 * @return value of bri
	 */
	public final java.lang.Integer getbri()
	{
		return getbri(getContext());
	}

	/**
	 * @param context
	 * @return value of bri
	 */
	public final java.lang.Integer getbri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.bri.toString());
	}

	/**
	 * Set value of bri
	 * @param bri
	 */
	public final void setbri(java.lang.Integer bri)
	{
		setbri(getContext(), bri);
	}

	/**
	 * Set value of bri
	 * @param context
	 * @param bri
	 */
	public final void setbri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bri)
	{
		getMendixObject().setValue(context, MemberNames.bri.toString(), bri);
	}

	/**
	 * Set value of alert
	 * @param alert
	 */
	public final homeautomationconnector.proxies.alert getalert()
	{
		return getalert(getContext());
	}

	/**
	 * @param context
	 * @return value of alert
	 */
	public final homeautomationconnector.proxies.alert getalert(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.alert.toString());
		if (obj == null)
			return null;

		return homeautomationconnector.proxies.alert.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of alert
	 * @param alert
	 */
	public final void setalert(homeautomationconnector.proxies.alert alert)
	{
		setalert(getContext(), alert);
	}

	/**
	 * Set value of alert
	 * @param context
	 * @param alert
	 */
	public final void setalert(com.mendix.systemwideinterfaces.core.IContext context, homeautomationconnector.proxies.alert alert)
	{
		if (alert != null)
			getMendixObject().setValue(context, MemberNames.alert.toString(), alert.toString());
		else
			getMendixObject().setValue(context, MemberNames.alert.toString(), null);
	}

	/**
	 * @return value of XY_StateRequestAll_XY
	 */
	public final homeautomationconnector.proxies.XY getXY_StateRequestAll_XY() throws com.mendix.core.CoreException
	{
		return getXY_StateRequestAll_XY(getContext());
	}

	/**
	 * @param context
	 * @return value of XY_StateRequestAll_XY
	 */
	public final homeautomationconnector.proxies.XY getXY_StateRequestAll_XY(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		homeautomationconnector.proxies.XY result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XY_StateRequestAll_XY.toString());
		if (identifier != null)
			result = homeautomationconnector.proxies.XY.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XY_StateRequestAll_XY
	 * @param xy_staterequestall_xy
	 */
	public final void setXY_StateRequestAll_XY(homeautomationconnector.proxies.XY xy_staterequestall_xy)
	{
		setXY_StateRequestAll_XY(getContext(), xy_staterequestall_xy);
	}

	/**
	 * Set value of XY_StateRequestAll_XY
	 * @param context
	 * @param xy_staterequestall_xy
	 */
	public final void setXY_StateRequestAll_XY(com.mendix.systemwideinterfaces.core.IContext context, homeautomationconnector.proxies.XY xy_staterequestall_xy)
	{
		if (xy_staterequestall_xy == null)
			getMendixObject().setValue(context, MemberNames.XY_StateRequestAll_XY.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XY_StateRequestAll_XY.toString(), xy_staterequestall_xy.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stateRequestAll_XYMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final homeautomationconnector.proxies.StateRequestAll_XY that = (homeautomationconnector.proxies.StateRequestAll_XY) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "HomeAutomationConnector.StateRequestAll_XY";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
