// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package homeautomationconnector.proxies;

public class StateRequestColorModeHS
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stateRequestColorModeHSMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "HomeAutomationConnector.StateRequestColorModeHS";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		on("on"),
		hue("hue"),
		sat("sat");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StateRequestColorModeHS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "HomeAutomationConnector.StateRequestColorModeHS"));
	}

	protected StateRequestColorModeHS(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stateRequestColorModeHSMendixObject)
	{
		if (stateRequestColorModeHSMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("HomeAutomationConnector.StateRequestColorModeHS", stateRequestColorModeHSMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a HomeAutomationConnector.StateRequestColorModeHS");

		this.stateRequestColorModeHSMendixObject = stateRequestColorModeHSMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StateRequestColorModeHS.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static homeautomationconnector.proxies.StateRequestColorModeHS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return homeautomationconnector.proxies.StateRequestColorModeHS.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static homeautomationconnector.proxies.StateRequestColorModeHS initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new homeautomationconnector.proxies.StateRequestColorModeHS(context, mendixObject);
	}

	public static homeautomationconnector.proxies.StateRequestColorModeHS load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return homeautomationconnector.proxies.StateRequestColorModeHS.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of on
	 */
	public final java.lang.Boolean geton()
	{
		return geton(getContext());
	}

	/**
	 * @param context
	 * @return value of on
	 */
	public final java.lang.Boolean geton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.on.toString());
	}

	/**
	 * Set value of on
	 * @param on
	 */
	public final void seton(java.lang.Boolean on)
	{
		seton(getContext(), on);
	}

	/**
	 * Set value of on
	 * @param context
	 * @param on
	 */
	public final void seton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean on)
	{
		getMendixObject().setValue(context, MemberNames.on.toString(), on);
	}

	/**
	 * @return value of hue
	 */
	public final java.lang.Integer gethue()
	{
		return gethue(getContext());
	}

	/**
	 * @param context
	 * @return value of hue
	 */
	public final java.lang.Integer gethue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.hue.toString());
	}

	/**
	 * Set value of hue
	 * @param hue
	 */
	public final void sethue(java.lang.Integer hue)
	{
		sethue(getContext(), hue);
	}

	/**
	 * Set value of hue
	 * @param context
	 * @param hue
	 */
	public final void sethue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hue)
	{
		getMendixObject().setValue(context, MemberNames.hue.toString(), hue);
	}

	/**
	 * @return value of sat
	 */
	public final java.lang.Integer getsat()
	{
		return getsat(getContext());
	}

	/**
	 * @param context
	 * @return value of sat
	 */
	public final java.lang.Integer getsat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.sat.toString());
	}

	/**
	 * Set value of sat
	 * @param sat
	 */
	public final void setsat(java.lang.Integer sat)
	{
		setsat(getContext(), sat);
	}

	/**
	 * Set value of sat
	 * @param context
	 * @param sat
	 */
	public final void setsat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sat)
	{
		getMendixObject().setValue(context, MemberNames.sat.toString(), sat);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stateRequestColorModeHSMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final homeautomationconnector.proxies.StateRequestColorModeHS that = (homeautomationconnector.proxies.StateRequestColorModeHS) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "HomeAutomationConnector.StateRequestColorModeHS";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
