// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appmain.proxies;

public class SensorValue
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sensorValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AppMain.SensorValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Temperature("Temperature"),
		Pressure("Pressure"),
		Humidity("Humidity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SensorValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AppMain.SensorValue"));
	}

	protected SensorValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sensorValueMendixObject)
	{
		if (sensorValueMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AppMain.SensorValue", sensorValueMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AppMain.SensorValue");

		this.sensorValueMendixObject = sensorValueMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SensorValue.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static appmain.proxies.SensorValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return appmain.proxies.SensorValue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static appmain.proxies.SensorValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new appmain.proxies.SensorValue(context, mendixObject);
	}

	public static appmain.proxies.SensorValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return appmain.proxies.SensorValue.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return value of Pressure
	 */
	public final java.math.BigDecimal getPressure()
	{
		return getPressure(getContext());
	}

	/**
	 * @param context
	 * @return value of Pressure
	 */
	public final java.math.BigDecimal getPressure(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Pressure.toString());
	}

	/**
	 * Set value of Pressure
	 * @param pressure
	 */
	public final void setPressure(java.math.BigDecimal pressure)
	{
		setPressure(getContext(), pressure);
	}

	/**
	 * Set value of Pressure
	 * @param context
	 * @param pressure
	 */
	public final void setPressure(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal pressure)
	{
		getMendixObject().setValue(context, MemberNames.Pressure.toString(), pressure);
	}

	/**
	 * @return value of Humidity
	 */
	public final java.lang.Integer getHumidity()
	{
		return getHumidity(getContext());
	}

	/**
	 * @param context
	 * @return value of Humidity
	 */
	public final java.lang.Integer getHumidity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Humidity.toString());
	}

	/**
	 * Set value of Humidity
	 * @param humidity
	 */
	public final void setHumidity(java.lang.Integer humidity)
	{
		setHumidity(getContext(), humidity);
	}

	/**
	 * Set value of Humidity
	 * @param context
	 * @param humidity
	 */
	public final void setHumidity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer humidity)
	{
		getMendixObject().setValue(context, MemberNames.Humidity.toString(), humidity);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sensorValueMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final appmain.proxies.SensorValue that = (appmain.proxies.SensorValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AppMain.SensorValue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
