// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sap_integration.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the SAP_Integration module

	public static java.lang.String getGWSAMPLE_BASIC()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SAP_Integration.GWSAMPLE_BASIC");
	}
}