// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlevisionapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the GoogleVisionAPI module
	public static void analizeWithGoogleVision(IContext context, masterdata.proxies.IncidentReportPhoto _incidentReportPhoto)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("IncidentReportPhoto", _incidentReportPhoto == null ? null : _incidentReportPhoto.getMendixObject());
		Core.microflowCall("GoogleVisionAPI.AnalizeWithGoogleVision").withParams(params).execute(context);
	}
	public static java.lang.String sUB_Brand(IContext context, googlevisionapi.proxies.Responses _result)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Result", _result == null ? null : _result.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleVisionAPI.SUB_Brand").withParams(params).execute(context);
	}
	public static java.lang.String sUB_FoundObjects(IContext context, googlevisionapi.proxies.Responses _result, masterdata.proxies.IncidentReportPhoto _incidentReportPhoto)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Result", _result == null ? null : _result.getMendixObject());
		params.put("IncidentReportPhoto", _incidentReportPhoto == null ? null : _incidentReportPhoto.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleVisionAPI.SUB_FoundObjects").withParams(params).execute(context);
	}
	public static java.lang.String sUB_GetLabels(IContext context, googlevisionapi.proxies.Responses _result)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Result", _result == null ? null : _result.getMendixObject());
		return (java.lang.String) Core.microflowCall("GoogleVisionAPI.SUB_GetLabels").withParams(params).execute(context);
	}
}