// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Characteristic
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject characteristicMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Characteristic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UUID("UUID"),
		Mode("Mode"),
		Name("Name"),
		Description("Description"),
		Read("Read"),
		Write("Write"),
		Notify("Notify"),
		TypeValue01("TypeValue01"),
		TypeValue02("TypeValue02"),
		TypeValue03("TypeValue03"),
		TypeValue04("TypeValue04"),
		TypeValue05("TypeValue05"),
		TypeValue06("TypeValue06"),
		TypeValue07("TypeValue07"),
		TypeValue08("TypeValue08"),
		TypeValue09("TypeValue09"),
		StringValue("StringValue"),
		AutoNotify("AutoNotify"),
		Characteristic_Service("IoT.Characteristic_Service"),
		Measurement_Characteristic("IoT.Measurement_Characteristic"),
		Characteristic_Characteristics("IoT.Characteristic_Characteristics");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Characteristic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Characteristic"));
	}

	protected Characteristic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject characteristicMendixObject)
	{
		if (characteristicMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Characteristic", characteristicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Characteristic");

		this.characteristicMendixObject = characteristicMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Characteristic.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Characteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Characteristic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Characteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Characteristic(context, mendixObject);
	}

	public static iot.proxies.Characteristic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Characteristic.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Characteristic> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Characteristic> result = new java.util.ArrayList<iot.proxies.Characteristic>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Characteristic" + xpathConstraint))
			result.add(iot.proxies.Characteristic.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of Mode
	 */
	public final java.lang.Integer getMode()
	{
		return getMode(getContext());
	}

	/**
	 * @param context
	 * @return value of Mode
	 */
	public final java.lang.Integer getMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Mode.toString());
	}

	/**
	 * Set value of Mode
	 * @param mode
	 */
	public final void setMode(java.lang.Integer mode)
	{
		setMode(getContext(), mode);
	}

	/**
	 * Set value of Mode
	 * @param context
	 * @param mode
	 */
	public final void setMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer mode)
	{
		getMendixObject().setValue(context, MemberNames.Mode.toString(), mode);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Read
	 */
	public final java.lang.Boolean getRead()
	{
		return getRead(getContext());
	}

	/**
	 * @param context
	 * @return value of Read
	 */
	public final java.lang.Boolean getRead(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Read.toString());
	}

	/**
	 * Set value of Read
	 * @param read
	 */
	public final void setRead(java.lang.Boolean read)
	{
		setRead(getContext(), read);
	}

	/**
	 * Set value of Read
	 * @param context
	 * @param read
	 */
	public final void setRead(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean read)
	{
		getMendixObject().setValue(context, MemberNames.Read.toString(), read);
	}

	/**
	 * @return value of Write
	 */
	public final java.lang.Boolean getWrite()
	{
		return getWrite(getContext());
	}

	/**
	 * @param context
	 * @return value of Write
	 */
	public final java.lang.Boolean getWrite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Write.toString());
	}

	/**
	 * Set value of Write
	 * @param write
	 */
	public final void setWrite(java.lang.Boolean write)
	{
		setWrite(getContext(), write);
	}

	/**
	 * Set value of Write
	 * @param context
	 * @param write
	 */
	public final void setWrite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean write)
	{
		getMendixObject().setValue(context, MemberNames.Write.toString(), write);
	}

	/**
	 * @return value of Notify
	 */
	public final java.lang.Boolean getNotify()
	{
		return getNotify(getContext());
	}

	/**
	 * @param context
	 * @return value of Notify
	 */
	public final java.lang.Boolean getNotify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Notify.toString());
	}

	/**
	 * Set value of Notify
	 * @param notify
	 */
	public final void setNotify(java.lang.Boolean notify)
	{
		setNotify(getContext(), notify);
	}

	/**
	 * Set value of Notify
	 * @param context
	 * @param notify
	 */
	public final void setNotify(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notify)
	{
		getMendixObject().setValue(context, MemberNames.Notify.toString(), notify);
	}

	/**
	 * Set value of TypeValue01
	 * @param typevalue01
	 */
	public final iot.proxies.NumberType getTypeValue01()
	{
		return getTypeValue01(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue01
	 */
	public final iot.proxies.NumberType getTypeValue01(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue01.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue01
	 * @param typevalue01
	 */
	public final void setTypeValue01(iot.proxies.NumberType typevalue01)
	{
		setTypeValue01(getContext(), typevalue01);
	}

	/**
	 * Set value of TypeValue01
	 * @param context
	 * @param typevalue01
	 */
	public final void setTypeValue01(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue01)
	{
		if (typevalue01 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue01.toString(), typevalue01.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue01.toString(), null);
	}

	/**
	 * Set value of TypeValue02
	 * @param typevalue02
	 */
	public final iot.proxies.NumberType getTypeValue02()
	{
		return getTypeValue02(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue02
	 */
	public final iot.proxies.NumberType getTypeValue02(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue02.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue02
	 * @param typevalue02
	 */
	public final void setTypeValue02(iot.proxies.NumberType typevalue02)
	{
		setTypeValue02(getContext(), typevalue02);
	}

	/**
	 * Set value of TypeValue02
	 * @param context
	 * @param typevalue02
	 */
	public final void setTypeValue02(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue02)
	{
		if (typevalue02 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue02.toString(), typevalue02.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue02.toString(), null);
	}

	/**
	 * Set value of TypeValue03
	 * @param typevalue03
	 */
	public final iot.proxies.NumberType getTypeValue03()
	{
		return getTypeValue03(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue03
	 */
	public final iot.proxies.NumberType getTypeValue03(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue03.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue03
	 * @param typevalue03
	 */
	public final void setTypeValue03(iot.proxies.NumberType typevalue03)
	{
		setTypeValue03(getContext(), typevalue03);
	}

	/**
	 * Set value of TypeValue03
	 * @param context
	 * @param typevalue03
	 */
	public final void setTypeValue03(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue03)
	{
		if (typevalue03 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue03.toString(), typevalue03.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue03.toString(), null);
	}

	/**
	 * Set value of TypeValue04
	 * @param typevalue04
	 */
	public final iot.proxies.NumberType getTypeValue04()
	{
		return getTypeValue04(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue04
	 */
	public final iot.proxies.NumberType getTypeValue04(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue04.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue04
	 * @param typevalue04
	 */
	public final void setTypeValue04(iot.proxies.NumberType typevalue04)
	{
		setTypeValue04(getContext(), typevalue04);
	}

	/**
	 * Set value of TypeValue04
	 * @param context
	 * @param typevalue04
	 */
	public final void setTypeValue04(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue04)
	{
		if (typevalue04 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue04.toString(), typevalue04.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue04.toString(), null);
	}

	/**
	 * Set value of TypeValue05
	 * @param typevalue05
	 */
	public final iot.proxies.NumberType getTypeValue05()
	{
		return getTypeValue05(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue05
	 */
	public final iot.proxies.NumberType getTypeValue05(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue05.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue05
	 * @param typevalue05
	 */
	public final void setTypeValue05(iot.proxies.NumberType typevalue05)
	{
		setTypeValue05(getContext(), typevalue05);
	}

	/**
	 * Set value of TypeValue05
	 * @param context
	 * @param typevalue05
	 */
	public final void setTypeValue05(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue05)
	{
		if (typevalue05 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue05.toString(), typevalue05.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue05.toString(), null);
	}

	/**
	 * Set value of TypeValue06
	 * @param typevalue06
	 */
	public final iot.proxies.NumberType getTypeValue06()
	{
		return getTypeValue06(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue06
	 */
	public final iot.proxies.NumberType getTypeValue06(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue06.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue06
	 * @param typevalue06
	 */
	public final void setTypeValue06(iot.proxies.NumberType typevalue06)
	{
		setTypeValue06(getContext(), typevalue06);
	}

	/**
	 * Set value of TypeValue06
	 * @param context
	 * @param typevalue06
	 */
	public final void setTypeValue06(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue06)
	{
		if (typevalue06 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue06.toString(), typevalue06.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue06.toString(), null);
	}

	/**
	 * Set value of TypeValue07
	 * @param typevalue07
	 */
	public final iot.proxies.NumberType getTypeValue07()
	{
		return getTypeValue07(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue07
	 */
	public final iot.proxies.NumberType getTypeValue07(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue07.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue07
	 * @param typevalue07
	 */
	public final void setTypeValue07(iot.proxies.NumberType typevalue07)
	{
		setTypeValue07(getContext(), typevalue07);
	}

	/**
	 * Set value of TypeValue07
	 * @param context
	 * @param typevalue07
	 */
	public final void setTypeValue07(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue07)
	{
		if (typevalue07 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue07.toString(), typevalue07.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue07.toString(), null);
	}

	/**
	 * Set value of TypeValue08
	 * @param typevalue08
	 */
	public final iot.proxies.NumberType getTypeValue08()
	{
		return getTypeValue08(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue08
	 */
	public final iot.proxies.NumberType getTypeValue08(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue08.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue08
	 * @param typevalue08
	 */
	public final void setTypeValue08(iot.proxies.NumberType typevalue08)
	{
		setTypeValue08(getContext(), typevalue08);
	}

	/**
	 * Set value of TypeValue08
	 * @param context
	 * @param typevalue08
	 */
	public final void setTypeValue08(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue08)
	{
		if (typevalue08 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue08.toString(), typevalue08.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue08.toString(), null);
	}

	/**
	 * Set value of TypeValue09
	 * @param typevalue09
	 */
	public final iot.proxies.NumberType getTypeValue09()
	{
		return getTypeValue09(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeValue09
	 */
	public final iot.proxies.NumberType getTypeValue09(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TypeValue09.toString());
		if (obj == null)
			return null;

		return iot.proxies.NumberType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TypeValue09
	 * @param typevalue09
	 */
	public final void setTypeValue09(iot.proxies.NumberType typevalue09)
	{
		setTypeValue09(getContext(), typevalue09);
	}

	/**
	 * Set value of TypeValue09
	 * @param context
	 * @param typevalue09
	 */
	public final void setTypeValue09(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.NumberType typevalue09)
	{
		if (typevalue09 != null)
			getMendixObject().setValue(context, MemberNames.TypeValue09.toString(), typevalue09.toString());
		else
			getMendixObject().setValue(context, MemberNames.TypeValue09.toString(), null);
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.Boolean getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.Boolean getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.Boolean stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return value of AutoNotify
	 */
	public final java.lang.Boolean getAutoNotify()
	{
		return getAutoNotify(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNotify
	 */
	public final java.lang.Boolean getAutoNotify(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoNotify.toString());
	}

	/**
	 * Set value of AutoNotify
	 * @param autonotify
	 */
	public final void setAutoNotify(java.lang.Boolean autonotify)
	{
		setAutoNotify(getContext(), autonotify);
	}

	/**
	 * Set value of AutoNotify
	 * @param context
	 * @param autonotify
	 */
	public final void setAutoNotify(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autonotify)
	{
		getMendixObject().setValue(context, MemberNames.AutoNotify.toString(), autonotify);
	}

	/**
	 * @return value of Characteristic_Service
	 */
	public final iot.proxies.Service getCharacteristic_Service() throws com.mendix.core.CoreException
	{
		return getCharacteristic_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of Characteristic_Service
	 */
	public final iot.proxies.Service getCharacteristic_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Characteristic_Service.toString());
		if (identifier != null)
			result = iot.proxies.Service.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Characteristic_Service
	 * @param characteristic_service
	 */
	public final void setCharacteristic_Service(iot.proxies.Service characteristic_service)
	{
		setCharacteristic_Service(getContext(), characteristic_service);
	}

	/**
	 * Set value of Characteristic_Service
	 * @param context
	 * @param characteristic_service
	 */
	public final void setCharacteristic_Service(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Service characteristic_service)
	{
		if (characteristic_service == null)
			getMendixObject().setValue(context, MemberNames.Characteristic_Service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Characteristic_Service.toString(), characteristic_service.getMendixObject().getId());
	}

	/**
	 * @return value of Measurement_Characteristic
	 */
	public final iot.proxies.Measurement getMeasurement_Characteristic() throws com.mendix.core.CoreException
	{
		return getMeasurement_Characteristic(getContext());
	}

	/**
	 * @param context
	 * @return value of Measurement_Characteristic
	 */
	public final iot.proxies.Measurement getMeasurement_Characteristic(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Measurement result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Measurement_Characteristic.toString());
		if (identifier != null)
			result = iot.proxies.Measurement.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Measurement_Characteristic
	 * @param measurement_characteristic
	 */
	public final void setMeasurement_Characteristic(iot.proxies.Measurement measurement_characteristic)
	{
		setMeasurement_Characteristic(getContext(), measurement_characteristic);
	}

	/**
	 * Set value of Measurement_Characteristic
	 * @param context
	 * @param measurement_characteristic
	 */
	public final void setMeasurement_Characteristic(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Measurement measurement_characteristic)
	{
		if (measurement_characteristic == null)
			getMendixObject().setValue(context, MemberNames.Measurement_Characteristic.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Measurement_Characteristic.toString(), measurement_characteristic.getMendixObject().getId());
	}

	/**
	 * @return value of Characteristic_Characteristics
	 */
	public final iot.proxies.Characteristics getCharacteristic_Characteristics() throws com.mendix.core.CoreException
	{
		return getCharacteristic_Characteristics(getContext());
	}

	/**
	 * @param context
	 * @return value of Characteristic_Characteristics
	 */
	public final iot.proxies.Characteristics getCharacteristic_Characteristics(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Characteristics result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Characteristic_Characteristics.toString());
		if (identifier != null)
			result = iot.proxies.Characteristics.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Characteristic_Characteristics
	 * @param characteristic_characteristics
	 */
	public final void setCharacteristic_Characteristics(iot.proxies.Characteristics characteristic_characteristics)
	{
		setCharacteristic_Characteristics(getContext(), characteristic_characteristics);
	}

	/**
	 * Set value of Characteristic_Characteristics
	 * @param context
	 * @param characteristic_characteristics
	 */
	public final void setCharacteristic_Characteristics(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Characteristics characteristic_characteristics)
	{
		if (characteristic_characteristics == null)
			getMendixObject().setValue(context, MemberNames.Characteristic_Characteristics.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Characteristic_Characteristics.toString(), characteristic_characteristics.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return characteristicMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Characteristic that = (iot.proxies.Characteristic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Characteristic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
