// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Characteristics
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject characteristicsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Characteristics";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Characteristics_Service("IoT.Characteristics_Service");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Characteristics(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Characteristics"));
	}

	protected Characteristics(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject characteristicsMendixObject)
	{
		if (characteristicsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Characteristics", characteristicsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Characteristics");

		this.characteristicsMendixObject = characteristicsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Characteristics.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Characteristics initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Characteristics.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Characteristics initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Characteristics(context, mendixObject);
	}

	public static iot.proxies.Characteristics load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Characteristics.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Characteristics> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Characteristics> result = new java.util.ArrayList<iot.proxies.Characteristics>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Characteristics" + xpathConstraint))
			result.add(iot.proxies.Characteristics.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Characteristics_Service
	 */
	public final iot.proxies.Service getCharacteristics_Service() throws com.mendix.core.CoreException
	{
		return getCharacteristics_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of Characteristics_Service
	 */
	public final iot.proxies.Service getCharacteristics_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Characteristics_Service.toString());
		if (identifier != null)
			result = iot.proxies.Service.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Characteristics_Service
	 * @param characteristics_service
	 */
	public final void setCharacteristics_Service(iot.proxies.Service characteristics_service)
	{
		setCharacteristics_Service(getContext(), characteristics_service);
	}

	/**
	 * Set value of Characteristics_Service
	 * @param context
	 * @param characteristics_service
	 */
	public final void setCharacteristics_Service(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Service characteristics_service)
	{
		if (characteristics_service == null)
			getMendixObject().setValue(context, MemberNames.Characteristics_Service.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Characteristics_Service.toString(), characteristics_service.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return characteristicsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Characteristics that = (iot.proxies.Characteristics) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Characteristics";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
