// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Config
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Config";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ipaddress("Ipaddress"),
		Zigbeechannel("Zigbeechannel"),
		Bridgeid("Bridgeid"),
		Name("Name"),
		Gateway("Gateway"),
		Config_Root("IoT.Config_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Config(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Config"));
	}

	protected Config(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configMendixObject)
	{
		if (configMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Config", configMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Config");

		this.configMendixObject = configMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Config.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Config.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Config initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Config(context, mendixObject);
	}

	public static iot.proxies.Config load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Config.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ipaddress
	 */
	public final java.lang.String getIpaddress()
	{
		return getIpaddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Ipaddress
	 */
	public final java.lang.String getIpaddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ipaddress.toString());
	}

	/**
	 * Set value of Ipaddress
	 * @param ipaddress
	 */
	public final void setIpaddress(java.lang.String ipaddress)
	{
		setIpaddress(getContext(), ipaddress);
	}

	/**
	 * Set value of Ipaddress
	 * @param context
	 * @param ipaddress
	 */
	public final void setIpaddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ipaddress)
	{
		getMendixObject().setValue(context, MemberNames.Ipaddress.toString(), ipaddress);
	}

	/**
	 * @return value of Zigbeechannel
	 */
	public final java.lang.Integer getZigbeechannel()
	{
		return getZigbeechannel(getContext());
	}

	/**
	 * @param context
	 * @return value of Zigbeechannel
	 */
	public final java.lang.Integer getZigbeechannel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Zigbeechannel.toString());
	}

	/**
	 * Set value of Zigbeechannel
	 * @param zigbeechannel
	 */
	public final void setZigbeechannel(java.lang.Integer zigbeechannel)
	{
		setZigbeechannel(getContext(), zigbeechannel);
	}

	/**
	 * Set value of Zigbeechannel
	 * @param context
	 * @param zigbeechannel
	 */
	public final void setZigbeechannel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer zigbeechannel)
	{
		getMendixObject().setValue(context, MemberNames.Zigbeechannel.toString(), zigbeechannel);
	}

	/**
	 * @return value of Bridgeid
	 */
	public final java.lang.String getBridgeid()
	{
		return getBridgeid(getContext());
	}

	/**
	 * @param context
	 * @return value of Bridgeid
	 */
	public final java.lang.String getBridgeid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bridgeid.toString());
	}

	/**
	 * Set value of Bridgeid
	 * @param bridgeid
	 */
	public final void setBridgeid(java.lang.String bridgeid)
	{
		setBridgeid(getContext(), bridgeid);
	}

	/**
	 * Set value of Bridgeid
	 * @param context
	 * @param bridgeid
	 */
	public final void setBridgeid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bridgeid)
	{
		getMendixObject().setValue(context, MemberNames.Bridgeid.toString(), bridgeid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Gateway
	 */
	public final java.lang.String getGateway()
	{
		return getGateway(getContext());
	}

	/**
	 * @param context
	 * @return value of Gateway
	 */
	public final java.lang.String getGateway(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Gateway.toString());
	}

	/**
	 * Set value of Gateway
	 * @param gateway
	 */
	public final void setGateway(java.lang.String gateway)
	{
		setGateway(getContext(), gateway);
	}

	/**
	 * Set value of Gateway
	 * @param context
	 * @param gateway
	 */
	public final void setGateway(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gateway)
	{
		getMendixObject().setValue(context, MemberNames.Gateway.toString(), gateway);
	}

	/**
	 * @return value of Config_Root
	 */
	public final iot.proxies.Root getConfig_Root() throws com.mendix.core.CoreException
	{
		return getConfig_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Config_Root
	 */
	public final iot.proxies.Root getConfig_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Config_Root.toString());
		if (identifier != null)
			result = iot.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Config_Root
	 * @param config_root
	 */
	public final void setConfig_Root(iot.proxies.Root config_root)
	{
		setConfig_Root(getContext(), config_root);
	}

	/**
	 * Set value of Config_Root
	 * @param context
	 * @param config_root
	 */
	public final void setConfig_Root(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Root config_root)
	{
		if (config_root == null)
			getMendixObject().setValue(context, MemberNames.Config_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Config_Root.toString(), config_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Config that = (iot.proxies.Config) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Config";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
