// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class GasCharacteristic extends iot.proxies.CharacteristicValue
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.GasCharacteristic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		eCO2_ppm("eCO2_ppm"),
		TVOC_ppb("TVOC_ppb"),
		DateTimeCreated("DateTimeCreated");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GasCharacteristic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.GasCharacteristic"));
	}

	protected GasCharacteristic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gasCharacteristicMendixObject)
	{
		super(context, gasCharacteristicMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("IoT.GasCharacteristic", gasCharacteristicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.GasCharacteristic");
	}

	/**
	 * @deprecated Use 'GasCharacteristic.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.GasCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.GasCharacteristic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.GasCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.GasCharacteristic(context, mendixObject);
	}

	public static iot.proxies.GasCharacteristic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.GasCharacteristic.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.GasCharacteristic> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.GasCharacteristic> result = new java.util.ArrayList<iot.proxies.GasCharacteristic>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.GasCharacteristic" + xpathConstraint))
			result.add(iot.proxies.GasCharacteristic.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of eCO2_ppm
	 */
	public final java.lang.Integer geteCO2_ppm()
	{
		return geteCO2_ppm(getContext());
	}

	/**
	 * @param context
	 * @return value of eCO2_ppm
	 */
	public final java.lang.Integer geteCO2_ppm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.eCO2_ppm.toString());
	}

	/**
	 * Set value of eCO2_ppm
	 * @param eco2_ppm
	 */
	public final void seteCO2_ppm(java.lang.Integer eco2_ppm)
	{
		seteCO2_ppm(getContext(), eco2_ppm);
	}

	/**
	 * Set value of eCO2_ppm
	 * @param context
	 * @param eco2_ppm
	 */
	public final void seteCO2_ppm(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer eco2_ppm)
	{
		getMendixObject().setValue(context, MemberNames.eCO2_ppm.toString(), eco2_ppm);
	}

	/**
	 * @return value of TVOC_ppb
	 */
	public final java.lang.Integer getTVOC_ppb()
	{
		return getTVOC_ppb(getContext());
	}

	/**
	 * @param context
	 * @return value of TVOC_ppb
	 */
	public final java.lang.Integer getTVOC_ppb(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TVOC_ppb.toString());
	}

	/**
	 * Set value of TVOC_ppb
	 * @param tvoc_ppb
	 */
	public final void setTVOC_ppb(java.lang.Integer tvoc_ppb)
	{
		setTVOC_ppb(getContext(), tvoc_ppb);
	}

	/**
	 * Set value of TVOC_ppb
	 * @param context
	 * @param tvoc_ppb
	 */
	public final void setTVOC_ppb(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tvoc_ppb)
	{
		getMendixObject().setValue(context, MemberNames.TVOC_ppb.toString(), tvoc_ppb);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.GasCharacteristic that = (iot.proxies.GasCharacteristic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.GasCharacteristic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
