// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class HumidityCharacteristic extends iot.proxies.CharacteristicValue
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.HumidityCharacteristic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Humidity("Humidity"),
		DateTimeCreated("DateTimeCreated");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HumidityCharacteristic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.HumidityCharacteristic"));
	}

	protected HumidityCharacteristic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject humidityCharacteristicMendixObject)
	{
		super(context, humidityCharacteristicMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("IoT.HumidityCharacteristic", humidityCharacteristicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.HumidityCharacteristic");
	}

	/**
	 * @deprecated Use 'HumidityCharacteristic.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.HumidityCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.HumidityCharacteristic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.HumidityCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.HumidityCharacteristic(context, mendixObject);
	}

	public static iot.proxies.HumidityCharacteristic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.HumidityCharacteristic.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.HumidityCharacteristic> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.HumidityCharacteristic> result = new java.util.ArrayList<iot.proxies.HumidityCharacteristic>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.HumidityCharacteristic" + xpathConstraint))
			result.add(iot.proxies.HumidityCharacteristic.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Humidity
	 */
	public final java.lang.Integer getHumidity()
	{
		return getHumidity(getContext());
	}

	/**
	 * @param context
	 * @return value of Humidity
	 */
	public final java.lang.Integer getHumidity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Humidity.toString());
	}

	/**
	 * Set value of Humidity
	 * @param humidity
	 */
	public final void setHumidity(java.lang.Integer humidity)
	{
		setHumidity(getContext(), humidity);
	}

	/**
	 * Set value of Humidity
	 * @param context
	 * @param humidity
	 */
	public final void setHumidity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer humidity)
	{
		getMendixObject().setValue(context, MemberNames.Humidity.toString(), humidity);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.HumidityCharacteristic that = (iot.proxies.HumidityCharacteristic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.HumidityCharacteristic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
