// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Measurement
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject measurementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Measurement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value01("Value01"),
		Value02("Value02"),
		Value03("Value03"),
		Value04("Value04"),
		Value05("Value05"),
		Value06("Value06"),
		Value07("Value07"),
		Value08("Value08"),
		Value09("Value09"),
		ValueString("ValueString"),
		Measurement_Characteristic("IoT.Measurement_Characteristic");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Measurement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Measurement"));
	}

	protected Measurement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject measurementMendixObject)
	{
		if (measurementMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Measurement", measurementMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Measurement");

		this.measurementMendixObject = measurementMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Measurement.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Measurement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Measurement.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Measurement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Measurement(context, mendixObject);
	}

	public static iot.proxies.Measurement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Measurement.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Measurement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Measurement> result = new java.util.ArrayList<iot.proxies.Measurement>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Measurement" + xpathConstraint))
			result.add(iot.proxies.Measurement.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value01
	 */
	public final java.lang.String getValue01()
	{
		return getValue01(getContext());
	}

	/**
	 * @param context
	 * @return value of Value01
	 */
	public final java.lang.String getValue01(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value01.toString());
	}

	/**
	 * Set value of Value01
	 * @param value01
	 */
	public final void setValue01(java.lang.String value01)
	{
		setValue01(getContext(), value01);
	}

	/**
	 * Set value of Value01
	 * @param context
	 * @param value01
	 */
	public final void setValue01(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value01)
	{
		getMendixObject().setValue(context, MemberNames.Value01.toString(), value01);
	}

	/**
	 * @return value of Value02
	 */
	public final java.lang.String getValue02()
	{
		return getValue02(getContext());
	}

	/**
	 * @param context
	 * @return value of Value02
	 */
	public final java.lang.String getValue02(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value02.toString());
	}

	/**
	 * Set value of Value02
	 * @param value02
	 */
	public final void setValue02(java.lang.String value02)
	{
		setValue02(getContext(), value02);
	}

	/**
	 * Set value of Value02
	 * @param context
	 * @param value02
	 */
	public final void setValue02(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value02)
	{
		getMendixObject().setValue(context, MemberNames.Value02.toString(), value02);
	}

	/**
	 * @return value of Value03
	 */
	public final java.lang.String getValue03()
	{
		return getValue03(getContext());
	}

	/**
	 * @param context
	 * @return value of Value03
	 */
	public final java.lang.String getValue03(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value03.toString());
	}

	/**
	 * Set value of Value03
	 * @param value03
	 */
	public final void setValue03(java.lang.String value03)
	{
		setValue03(getContext(), value03);
	}

	/**
	 * Set value of Value03
	 * @param context
	 * @param value03
	 */
	public final void setValue03(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value03)
	{
		getMendixObject().setValue(context, MemberNames.Value03.toString(), value03);
	}

	/**
	 * @return value of Value04
	 */
	public final java.lang.String getValue04()
	{
		return getValue04(getContext());
	}

	/**
	 * @param context
	 * @return value of Value04
	 */
	public final java.lang.String getValue04(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value04.toString());
	}

	/**
	 * Set value of Value04
	 * @param value04
	 */
	public final void setValue04(java.lang.String value04)
	{
		setValue04(getContext(), value04);
	}

	/**
	 * Set value of Value04
	 * @param context
	 * @param value04
	 */
	public final void setValue04(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value04)
	{
		getMendixObject().setValue(context, MemberNames.Value04.toString(), value04);
	}

	/**
	 * @return value of Value05
	 */
	public final java.lang.String getValue05()
	{
		return getValue05(getContext());
	}

	/**
	 * @param context
	 * @return value of Value05
	 */
	public final java.lang.String getValue05(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value05.toString());
	}

	/**
	 * Set value of Value05
	 * @param value05
	 */
	public final void setValue05(java.lang.String value05)
	{
		setValue05(getContext(), value05);
	}

	/**
	 * Set value of Value05
	 * @param context
	 * @param value05
	 */
	public final void setValue05(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value05)
	{
		getMendixObject().setValue(context, MemberNames.Value05.toString(), value05);
	}

	/**
	 * @return value of Value06
	 */
	public final java.lang.String getValue06()
	{
		return getValue06(getContext());
	}

	/**
	 * @param context
	 * @return value of Value06
	 */
	public final java.lang.String getValue06(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value06.toString());
	}

	/**
	 * Set value of Value06
	 * @param value06
	 */
	public final void setValue06(java.lang.String value06)
	{
		setValue06(getContext(), value06);
	}

	/**
	 * Set value of Value06
	 * @param context
	 * @param value06
	 */
	public final void setValue06(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value06)
	{
		getMendixObject().setValue(context, MemberNames.Value06.toString(), value06);
	}

	/**
	 * @return value of Value07
	 */
	public final java.lang.String getValue07()
	{
		return getValue07(getContext());
	}

	/**
	 * @param context
	 * @return value of Value07
	 */
	public final java.lang.String getValue07(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value07.toString());
	}

	/**
	 * Set value of Value07
	 * @param value07
	 */
	public final void setValue07(java.lang.String value07)
	{
		setValue07(getContext(), value07);
	}

	/**
	 * Set value of Value07
	 * @param context
	 * @param value07
	 */
	public final void setValue07(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value07)
	{
		getMendixObject().setValue(context, MemberNames.Value07.toString(), value07);
	}

	/**
	 * @return value of Value08
	 */
	public final java.lang.String getValue08()
	{
		return getValue08(getContext());
	}

	/**
	 * @param context
	 * @return value of Value08
	 */
	public final java.lang.String getValue08(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value08.toString());
	}

	/**
	 * Set value of Value08
	 * @param value08
	 */
	public final void setValue08(java.lang.String value08)
	{
		setValue08(getContext(), value08);
	}

	/**
	 * Set value of Value08
	 * @param context
	 * @param value08
	 */
	public final void setValue08(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value08)
	{
		getMendixObject().setValue(context, MemberNames.Value08.toString(), value08);
	}

	/**
	 * @return value of Value09
	 */
	public final java.lang.String getValue09()
	{
		return getValue09(getContext());
	}

	/**
	 * @param context
	 * @return value of Value09
	 */
	public final java.lang.String getValue09(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value09.toString());
	}

	/**
	 * Set value of Value09
	 * @param value09
	 */
	public final void setValue09(java.lang.String value09)
	{
		setValue09(getContext(), value09);
	}

	/**
	 * Set value of Value09
	 * @param context
	 * @param value09
	 */
	public final void setValue09(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value09)
	{
		getMendixObject().setValue(context, MemberNames.Value09.toString(), value09);
	}

	/**
	 * @return value of ValueString
	 */
	public final java.lang.String getValueString()
	{
		return getValueString(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueString
	 */
	public final java.lang.String getValueString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueString.toString());
	}

	/**
	 * Set value of ValueString
	 * @param valuestring
	 */
	public final void setValueString(java.lang.String valuestring)
	{
		setValueString(getContext(), valuestring);
	}

	/**
	 * Set value of ValueString
	 * @param context
	 * @param valuestring
	 */
	public final void setValueString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuestring)
	{
		getMendixObject().setValue(context, MemberNames.ValueString.toString(), valuestring);
	}

	/**
	 * @return value of Measurement_Characteristic
	 */
	public final iot.proxies.Characteristic getMeasurement_Characteristic() throws com.mendix.core.CoreException
	{
		return getMeasurement_Characteristic(getContext());
	}

	/**
	 * @param context
	 * @return value of Measurement_Characteristic
	 */
	public final iot.proxies.Characteristic getMeasurement_Characteristic(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Characteristic result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Measurement_Characteristic.toString());
		if (identifier != null)
			result = iot.proxies.Characteristic.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Measurement_Characteristic
	 * @param measurement_characteristic
	 */
	public final void setMeasurement_Characteristic(iot.proxies.Characteristic measurement_characteristic)
	{
		setMeasurement_Characteristic(getContext(), measurement_characteristic);
	}

	/**
	 * Set value of Measurement_Characteristic
	 * @param context
	 * @param measurement_characteristic
	 */
	public final void setMeasurement_Characteristic(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Characteristic measurement_characteristic)
	{
		if (measurement_characteristic == null)
			getMendixObject().setValue(context, MemberNames.Measurement_Characteristic.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Measurement_Characteristic.toString(), measurement_characteristic.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return measurementMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Measurement that = (iot.proxies.Measurement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Measurement";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
