// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Room extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Room";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RoomName("RoomName"),
		Lights("Lights"),
		Temperature("Temperature"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Room(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Room"));
	}

	protected Room(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject roomMendixObject)
	{
		super(context, roomMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("IoT.Room", roomMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Room");
	}

	/**
	 * @deprecated Use 'Room.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Room initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Room.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Room initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Room(context, mendixObject);
	}

	public static iot.proxies.Room load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Room.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Room> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Room> result = new java.util.ArrayList<iot.proxies.Room>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Room" + xpathConstraint))
			result.add(iot.proxies.Room.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName()
	{
		return getRoomName(getContext());
	}

	/**
	 * @param context
	 * @return value of RoomName
	 */
	public final java.lang.String getRoomName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RoomName.toString());
	}

	/**
	 * Set value of RoomName
	 * @param roomname
	 */
	public final void setRoomName(java.lang.String roomname)
	{
		setRoomName(getContext(), roomname);
	}

	/**
	 * Set value of RoomName
	 * @param context
	 * @param roomname
	 */
	public final void setRoomName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String roomname)
	{
		getMendixObject().setValue(context, MemberNames.RoomName.toString(), roomname);
	}

	/**
	 * @return value of Lights
	 */
	public final java.math.BigDecimal getLights()
	{
		return getLights(getContext());
	}

	/**
	 * @param context
	 * @return value of Lights
	 */
	public final java.math.BigDecimal getLights(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lights.toString());
	}

	/**
	 * Set value of Lights
	 * @param lights
	 */
	public final void setLights(java.math.BigDecimal lights)
	{
		setLights(getContext(), lights);
	}

	/**
	 * Set value of Lights
	 * @param context
	 * @param lights
	 */
	public final void setLights(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lights)
	{
		getMendixObject().setValue(context, MemberNames.Lights.toString(), lights);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Room that = (iot.proxies.Room) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Room";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
