// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class SoundRoot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject soundRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.SoundRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sounds_SoundRoot("IoT.Sounds_SoundRoot");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SoundRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.SoundRoot"));
	}

	protected SoundRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject soundRootMendixObject)
	{
		if (soundRootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.SoundRoot", soundRootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.SoundRoot");

		this.soundRootMendixObject = soundRootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SoundRoot.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.SoundRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.SoundRoot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.SoundRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.SoundRoot(context, mendixObject);
	}

	public static iot.proxies.SoundRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.SoundRoot.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.SoundRoot> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.SoundRoot> result = new java.util.ArrayList<iot.proxies.SoundRoot>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.SoundRoot" + xpathConstraint))
			result.add(iot.proxies.SoundRoot.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sounds_SoundRoot
	 */
	public final iot.proxies.Sounds getSounds_SoundRoot() throws com.mendix.core.CoreException
	{
		return getSounds_SoundRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Sounds_SoundRoot
	 */
	public final iot.proxies.Sounds getSounds_SoundRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Sounds result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sounds_SoundRoot.toString());
		if (identifier != null)
			result = iot.proxies.Sounds.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sounds_SoundRoot
	 * @param sounds_soundroot
	 */
	public final void setSounds_SoundRoot(iot.proxies.Sounds sounds_soundroot)
	{
		setSounds_SoundRoot(getContext(), sounds_soundroot);
	}

	/**
	 * Set value of Sounds_SoundRoot
	 * @param context
	 * @param sounds_soundroot
	 */
	public final void setSounds_SoundRoot(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Sounds sounds_soundroot)
	{
		if (sounds_soundroot == null)
			getMendixObject().setValue(context, MemberNames.Sounds_SoundRoot.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sounds_SoundRoot.toString(), sounds_soundroot.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return soundRootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.SoundRoot that = (iot.proxies.SoundRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.SoundRoot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
