// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Sound
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject soundMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Sound";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		SampleId("SampleId"),
		Sound_Sounds("IoT.Sound_Sounds");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sound(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Sound"));
	}

	protected Sound(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject soundMendixObject)
	{
		if (soundMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Sound", soundMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Sound");

		this.soundMendixObject = soundMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Sound.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Sound initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Sound.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Sound initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Sound(context, mendixObject);
	}

	public static iot.proxies.Sound load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Sound.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.Sound> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.Sound> result = new java.util.ArrayList<iot.proxies.Sound>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.Sound" + xpathConstraint))
			result.add(iot.proxies.Sound.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of SampleId
	 */
	public final java.lang.Integer getSampleId()
	{
		return getSampleId(getContext());
	}

	/**
	 * @param context
	 * @return value of SampleId
	 */
	public final java.lang.Integer getSampleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SampleId.toString());
	}

	/**
	 * Set value of SampleId
	 * @param sampleid
	 */
	public final void setSampleId(java.lang.Integer sampleid)
	{
		setSampleId(getContext(), sampleid);
	}

	/**
	 * Set value of SampleId
	 * @param context
	 * @param sampleid
	 */
	public final void setSampleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sampleid)
	{
		getMendixObject().setValue(context, MemberNames.SampleId.toString(), sampleid);
	}

	/**
	 * @return value of Sound_Sounds
	 */
	public final iot.proxies.Sounds getSound_Sounds() throws com.mendix.core.CoreException
	{
		return getSound_Sounds(getContext());
	}

	/**
	 * @param context
	 * @return value of Sound_Sounds
	 */
	public final iot.proxies.Sounds getSound_Sounds(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Sounds result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sound_Sounds.toString());
		if (identifier != null)
			result = iot.proxies.Sounds.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sound_Sounds
	 * @param sound_sounds
	 */
	public final void setSound_Sounds(iot.proxies.Sounds sound_sounds)
	{
		setSound_Sounds(getContext(), sound_sounds);
	}

	/**
	 * Set value of Sound_Sounds
	 * @param context
	 * @param sound_sounds
	 */
	public final void setSound_Sounds(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Sounds sound_sounds)
	{
		if (sound_sounds == null)
			getMendixObject().setValue(context, MemberNames.Sound_Sounds.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sound_Sounds.toString(), sound_sounds.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return soundMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Sound that = (iot.proxies.Sound) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Sound";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
