// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class StateRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stateRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.StateRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		on("on"),
		bri("bri"),
		hue("hue"),
		sat("sat"),
		transitiontime("transitiontime");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StateRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.StateRequest"));
	}

	protected StateRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stateRequestMendixObject)
	{
		if (stateRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.StateRequest", stateRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.StateRequest");

		this.stateRequestMendixObject = stateRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'StateRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.StateRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.StateRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.StateRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.StateRequest(context, mendixObject);
	}

	public static iot.proxies.StateRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.StateRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of on
	 */
	public final java.lang.Boolean geton()
	{
		return geton(getContext());
	}

	/**
	 * @param context
	 * @return value of on
	 */
	public final java.lang.Boolean geton(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.on.toString());
	}

	/**
	 * Set value of on
	 * @param on
	 */
	public final void seton(java.lang.Boolean on)
	{
		seton(getContext(), on);
	}

	/**
	 * Set value of on
	 * @param context
	 * @param on
	 */
	public final void seton(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean on)
	{
		getMendixObject().setValue(context, MemberNames.on.toString(), on);
	}

	/**
	 * @return value of bri
	 */
	public final java.lang.Integer getbri()
	{
		return getbri(getContext());
	}

	/**
	 * @param context
	 * @return value of bri
	 */
	public final java.lang.Integer getbri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.bri.toString());
	}

	/**
	 * Set value of bri
	 * @param bri
	 */
	public final void setbri(java.lang.Integer bri)
	{
		setbri(getContext(), bri);
	}

	/**
	 * Set value of bri
	 * @param context
	 * @param bri
	 */
	public final void setbri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bri)
	{
		getMendixObject().setValue(context, MemberNames.bri.toString(), bri);
	}

	/**
	 * @return value of hue
	 */
	public final java.lang.Integer gethue()
	{
		return gethue(getContext());
	}

	/**
	 * @param context
	 * @return value of hue
	 */
	public final java.lang.Integer gethue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.hue.toString());
	}

	/**
	 * Set value of hue
	 * @param hue
	 */
	public final void sethue(java.lang.Integer hue)
	{
		sethue(getContext(), hue);
	}

	/**
	 * Set value of hue
	 * @param context
	 * @param hue
	 */
	public final void sethue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hue)
	{
		getMendixObject().setValue(context, MemberNames.hue.toString(), hue);
	}

	/**
	 * @return value of sat
	 */
	public final java.lang.Integer getsat()
	{
		return getsat(getContext());
	}

	/**
	 * @param context
	 * @return value of sat
	 */
	public final java.lang.Integer getsat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.sat.toString());
	}

	/**
	 * Set value of sat
	 * @param sat
	 */
	public final void setsat(java.lang.Integer sat)
	{
		setsat(getContext(), sat);
	}

	/**
	 * Set value of sat
	 * @param context
	 * @param sat
	 */
	public final void setsat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sat)
	{
		getMendixObject().setValue(context, MemberNames.sat.toString(), sat);
	}

	/**
	 * @return value of transitiontime
	 */
	public final java.lang.Integer gettransitiontime()
	{
		return gettransitiontime(getContext());
	}

	/**
	 * @param context
	 * @return value of transitiontime
	 */
	public final java.lang.Integer gettransitiontime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.transitiontime.toString());
	}

	/**
	 * Set value of transitiontime
	 * @param transitiontime
	 */
	public final void settransitiontime(java.lang.Integer transitiontime)
	{
		settransitiontime(getContext(), transitiontime);
	}

	/**
	 * Set value of transitiontime
	 * @param context
	 * @param transitiontime
	 */
	public final void settransitiontime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transitiontime)
	{
		getMendixObject().setValue(context, MemberNames.transitiontime.toString(), transitiontime);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stateRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.StateRequest that = (iot.proxies.StateRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.StateRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
