// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class TemperatureCharacteristic extends iot.proxies.CharacteristicValue
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.TemperatureCharacteristic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Tempetature("Tempetature"),
		DateTimeCreated("DateTimeCreated");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TemperatureCharacteristic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.TemperatureCharacteristic"));
	}

	protected TemperatureCharacteristic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject temperatureCharacteristicMendixObject)
	{
		super(context, temperatureCharacteristicMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("IoT.TemperatureCharacteristic", temperatureCharacteristicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.TemperatureCharacteristic");
	}

	/**
	 * @deprecated Use 'TemperatureCharacteristic.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.TemperatureCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.TemperatureCharacteristic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.TemperatureCharacteristic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.TemperatureCharacteristic(context, mendixObject);
	}

	public static iot.proxies.TemperatureCharacteristic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.TemperatureCharacteristic.initialize(context, mendixObject);
	}

	public static java.util.List<iot.proxies.TemperatureCharacteristic> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<iot.proxies.TemperatureCharacteristic> result = new java.util.ArrayList<iot.proxies.TemperatureCharacteristic>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//IoT.TemperatureCharacteristic" + xpathConstraint))
			result.add(iot.proxies.TemperatureCharacteristic.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Tempetature
	 */
	public final java.math.BigDecimal getTempetature()
	{
		return getTempetature(getContext());
	}

	/**
	 * @param context
	 * @return value of Tempetature
	 */
	public final java.math.BigDecimal getTempetature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Tempetature.toString());
	}

	/**
	 * Set value of Tempetature
	 * @param tempetature
	 */
	public final void setTempetature(java.math.BigDecimal tempetature)
	{
		setTempetature(getContext(), tempetature);
	}

	/**
	 * Set value of Tempetature
	 * @param context
	 * @param tempetature
	 */
	public final void setTempetature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal tempetature)
	{
		getMendixObject().setValue(context, MemberNames.Tempetature.toString(), tempetature);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.TemperatureCharacteristic that = (iot.proxies.TemperatureCharacteristic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.TemperatureCharacteristic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
