// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies;

public class Whitelist
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject whitelistMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IoT.Whitelist";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Create_date("Create_date"),
		Last_use_date("Last_use_date"),
		Name("Name"),
		_id("_id"),
		Whitelist_Config("IoT.Whitelist_Config");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Whitelist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IoT.Whitelist"));
	}

	protected Whitelist(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject whitelistMendixObject)
	{
		if (whitelistMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IoT.Whitelist", whitelistMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IoT.Whitelist");

		this.whitelistMendixObject = whitelistMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Whitelist.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static iot.proxies.Whitelist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return iot.proxies.Whitelist.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static iot.proxies.Whitelist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new iot.proxies.Whitelist(context, mendixObject);
	}

	public static iot.proxies.Whitelist load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return iot.proxies.Whitelist.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Create_date
	 */
	public final java.util.Date getCreate_date()
	{
		return getCreate_date(getContext());
	}

	/**
	 * @param context
	 * @return value of Create_date
	 */
	public final java.util.Date getCreate_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Create_date.toString());
	}

	/**
	 * Set value of Create_date
	 * @param create_date
	 */
	public final void setCreate_date(java.util.Date create_date)
	{
		setCreate_date(getContext(), create_date);
	}

	/**
	 * Set value of Create_date
	 * @param context
	 * @param create_date
	 */
	public final void setCreate_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date create_date)
	{
		getMendixObject().setValue(context, MemberNames.Create_date.toString(), create_date);
	}

	/**
	 * @return value of Last_use_date
	 */
	public final java.util.Date getLast_use_date()
	{
		return getLast_use_date(getContext());
	}

	/**
	 * @param context
	 * @return value of Last_use_date
	 */
	public final java.util.Date getLast_use_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Last_use_date.toString());
	}

	/**
	 * Set value of Last_use_date
	 * @param last_use_date
	 */
	public final void setLast_use_date(java.util.Date last_use_date)
	{
		setLast_use_date(getContext(), last_use_date);
	}

	/**
	 * Set value of Last_use_date
	 * @param context
	 * @param last_use_date
	 */
	public final void setLast_use_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date last_use_date)
	{
		getMendixObject().setValue(context, MemberNames.Last_use_date.toString(), last_use_date);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Whitelist_Config
	 */
	public final iot.proxies.Config getWhitelist_Config() throws com.mendix.core.CoreException
	{
		return getWhitelist_Config(getContext());
	}

	/**
	 * @param context
	 * @return value of Whitelist_Config
	 */
	public final iot.proxies.Config getWhitelist_Config(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		iot.proxies.Config result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Whitelist_Config.toString());
		if (identifier != null)
			result = iot.proxies.Config.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Whitelist_Config
	 * @param whitelist_config
	 */
	public final void setWhitelist_Config(iot.proxies.Config whitelist_config)
	{
		setWhitelist_Config(getContext(), whitelist_config);
	}

	/**
	 * Set value of Whitelist_Config
	 * @param context
	 * @param whitelist_config
	 */
	public final void setWhitelist_Config(com.mendix.systemwideinterfaces.core.IContext context, iot.proxies.Config whitelist_config)
	{
		if (whitelist_config == null)
			getMendixObject().setValue(context, MemberNames.Whitelist_Config.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Whitelist_Config.toString(), whitelist_config.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return whitelistMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final iot.proxies.Whitelist that = (iot.proxies.Whitelist) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IoT.Whitelist";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
