// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies;

public enum Authentication
{
	AppToAppSSO(new java.lang.String[][] { new java.lang.String[] { "en_US", "AppToAppSSO" } }),
	BasicAuthentication(new java.lang.String[][] { new java.lang.String[] { "en_US", "BasicAuthentication" } }),
	ClientCertificateAuthentication(new java.lang.String[][] { new java.lang.String[] { "en_US", "ClientCertificateAuthentication" } }),
	NoAuthentication(new java.lang.String[][] { new java.lang.String[] { "en_US", "NoAuthentication" } }),
	OAuth2SAMLBearerAssertion(new java.lang.String[][] { new java.lang.String[] { "en_US", "OAuth2SAMLBearerAssertion" } }),
	SAPAssertionSSO(new java.lang.String[][] { new java.lang.String[] { "en_US", "SAPAssertionSSO" } }),
	PrincipalPropagation(new java.lang.String[][] { new java.lang.String[] { "en_US", "PrincipalPropagation" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Authentication(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
