// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies;

public class DestinationConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject destinationConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAPODataConnector.DestinationConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		_Type("_Type"),
		URL("URL"),
		Authentication("Authentication"),
		ProxyType("ProxyType"),
		Audience("Audience"),
		AuthnContextClassRef("AuthnContextClassRef"),
		ClientKey("ClientKey"),
		NameIdFormat("NameIdFormat"),
		TokenServiceUser("TokenServiceUser"),
		TokenServiceURL("TokenServiceURL"),
		TokenServicePassword("TokenServicePassword"),
		User("User"),
		Password("Password"),
		CloudConnectorLocationId("CloudConnectorLocationId"),
		DestinationConfiguration_Root("SAPODataConnector.DestinationConfiguration_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DestinationConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAPODataConnector.DestinationConfiguration"));
	}

	protected DestinationConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject destinationConfigurationMendixObject)
	{
		if (destinationConfigurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAPODataConnector.DestinationConfiguration", destinationConfigurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAPODataConnector.DestinationConfiguration");

		this.destinationConfigurationMendixObject = destinationConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DestinationConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sapodataconnector.proxies.DestinationConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sapodataconnector.proxies.DestinationConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sapodataconnector.proxies.DestinationConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sapodataconnector.proxies.DestinationConfiguration(context, mendixObject);
	}

	public static sapodataconnector.proxies.DestinationConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sapodataconnector.proxies.DestinationConfiguration.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of _Type
	 */
	public final java.lang.String get_Type()
	{
		return get_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of _Type
	 */
	public final java.lang.String get_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._Type.toString());
	}

	/**
	 * Set value of _Type
	 * @param _type
	 */
	public final void set_Type(java.lang.String _type)
	{
		set_Type(getContext(), _type);
	}

	/**
	 * Set value of _Type
	 * @param context
	 * @param _type
	 */
	public final void set_Type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._Type.toString(), _type);
	}

	/**
	 * @return value of URL
	 */
	public final java.lang.String getURL()
	{
		return getURL(getContext());
	}

	/**
	 * @param context
	 * @return value of URL
	 */
	public final java.lang.String getURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.URL.toString());
	}

	/**
	 * Set value of URL
	 * @param url
	 */
	public final void setURL(java.lang.String url)
	{
		setURL(getContext(), url);
	}

	/**
	 * Set value of URL
	 * @param context
	 * @param url
	 */
	public final void setURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String url)
	{
		getMendixObject().setValue(context, MemberNames.URL.toString(), url);
	}

	/**
	 * @return value of Authentication
	 */
	public final java.lang.String getAuthentication()
	{
		return getAuthentication(getContext());
	}

	/**
	 * @param context
	 * @return value of Authentication
	 */
	public final java.lang.String getAuthentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Authentication.toString());
	}

	/**
	 * Set value of Authentication
	 * @param authentication
	 */
	public final void setAuthentication(java.lang.String authentication)
	{
		setAuthentication(getContext(), authentication);
	}

	/**
	 * Set value of Authentication
	 * @param context
	 * @param authentication
	 */
	public final void setAuthentication(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authentication)
	{
		getMendixObject().setValue(context, MemberNames.Authentication.toString(), authentication);
	}

	/**
	 * @return value of ProxyType
	 */
	public final java.lang.String getProxyType()
	{
		return getProxyType(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyType
	 */
	public final java.lang.String getProxyType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProxyType.toString());
	}

	/**
	 * Set value of ProxyType
	 * @param proxytype
	 */
	public final void setProxyType(java.lang.String proxytype)
	{
		setProxyType(getContext(), proxytype);
	}

	/**
	 * Set value of ProxyType
	 * @param context
	 * @param proxytype
	 */
	public final void setProxyType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String proxytype)
	{
		getMendixObject().setValue(context, MemberNames.ProxyType.toString(), proxytype);
	}

	/**
	 * @return value of Audience
	 */
	public final java.lang.String getAudience()
	{
		return getAudience(getContext());
	}

	/**
	 * @param context
	 * @return value of Audience
	 */
	public final java.lang.String getAudience(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Audience.toString());
	}

	/**
	 * Set value of Audience
	 * @param audience
	 */
	public final void setAudience(java.lang.String audience)
	{
		setAudience(getContext(), audience);
	}

	/**
	 * Set value of Audience
	 * @param context
	 * @param audience
	 */
	public final void setAudience(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String audience)
	{
		getMendixObject().setValue(context, MemberNames.Audience.toString(), audience);
	}

	/**
	 * @return value of AuthnContextClassRef
	 */
	public final java.lang.String getAuthnContextClassRef()
	{
		return getAuthnContextClassRef(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthnContextClassRef
	 */
	public final java.lang.String getAuthnContextClassRef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthnContextClassRef.toString());
	}

	/**
	 * Set value of AuthnContextClassRef
	 * @param authncontextclassref
	 */
	public final void setAuthnContextClassRef(java.lang.String authncontextclassref)
	{
		setAuthnContextClassRef(getContext(), authncontextclassref);
	}

	/**
	 * Set value of AuthnContextClassRef
	 * @param context
	 * @param authncontextclassref
	 */
	public final void setAuthnContextClassRef(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authncontextclassref)
	{
		getMendixObject().setValue(context, MemberNames.AuthnContextClassRef.toString(), authncontextclassref);
	}

	/**
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey()
	{
		return getClientKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientKey
	 */
	public final java.lang.String getClientKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientKey.toString());
	}

	/**
	 * Set value of ClientKey
	 * @param clientkey
	 */
	public final void setClientKey(java.lang.String clientkey)
	{
		setClientKey(getContext(), clientkey);
	}

	/**
	 * Set value of ClientKey
	 * @param context
	 * @param clientkey
	 */
	public final void setClientKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientkey)
	{
		getMendixObject().setValue(context, MemberNames.ClientKey.toString(), clientkey);
	}

	/**
	 * @return value of NameIdFormat
	 */
	public final java.lang.String getNameIdFormat()
	{
		return getNameIdFormat(getContext());
	}

	/**
	 * @param context
	 * @return value of NameIdFormat
	 */
	public final java.lang.String getNameIdFormat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameIdFormat.toString());
	}

	/**
	 * Set value of NameIdFormat
	 * @param nameidformat
	 */
	public final void setNameIdFormat(java.lang.String nameidformat)
	{
		setNameIdFormat(getContext(), nameidformat);
	}

	/**
	 * Set value of NameIdFormat
	 * @param context
	 * @param nameidformat
	 */
	public final void setNameIdFormat(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameidformat)
	{
		getMendixObject().setValue(context, MemberNames.NameIdFormat.toString(), nameidformat);
	}

	/**
	 * @return value of TokenServiceUser
	 */
	public final java.lang.String getTokenServiceUser()
	{
		return getTokenServiceUser(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenServiceUser
	 */
	public final java.lang.String getTokenServiceUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenServiceUser.toString());
	}

	/**
	 * Set value of TokenServiceUser
	 * @param tokenserviceuser
	 */
	public final void setTokenServiceUser(java.lang.String tokenserviceuser)
	{
		setTokenServiceUser(getContext(), tokenserviceuser);
	}

	/**
	 * Set value of TokenServiceUser
	 * @param context
	 * @param tokenserviceuser
	 */
	public final void setTokenServiceUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenserviceuser)
	{
		getMendixObject().setValue(context, MemberNames.TokenServiceUser.toString(), tokenserviceuser);
	}

	/**
	 * @return value of TokenServiceURL
	 */
	public final java.lang.String getTokenServiceURL()
	{
		return getTokenServiceURL(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenServiceURL
	 */
	public final java.lang.String getTokenServiceURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenServiceURL.toString());
	}

	/**
	 * Set value of TokenServiceURL
	 * @param tokenserviceurl
	 */
	public final void setTokenServiceURL(java.lang.String tokenserviceurl)
	{
		setTokenServiceURL(getContext(), tokenserviceurl);
	}

	/**
	 * Set value of TokenServiceURL
	 * @param context
	 * @param tokenserviceurl
	 */
	public final void setTokenServiceURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenserviceurl)
	{
		getMendixObject().setValue(context, MemberNames.TokenServiceURL.toString(), tokenserviceurl);
	}

	/**
	 * @return value of TokenServicePassword
	 */
	public final java.lang.String getTokenServicePassword()
	{
		return getTokenServicePassword(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenServicePassword
	 */
	public final java.lang.String getTokenServicePassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenServicePassword.toString());
	}

	/**
	 * Set value of TokenServicePassword
	 * @param tokenservicepassword
	 */
	public final void setTokenServicePassword(java.lang.String tokenservicepassword)
	{
		setTokenServicePassword(getContext(), tokenservicepassword);
	}

	/**
	 * Set value of TokenServicePassword
	 * @param context
	 * @param tokenservicepassword
	 */
	public final void setTokenServicePassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenservicepassword)
	{
		getMendixObject().setValue(context, MemberNames.TokenServicePassword.toString(), tokenservicepassword);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of CloudConnectorLocationId
	 */
	public final java.lang.String getCloudConnectorLocationId()
	{
		return getCloudConnectorLocationId(getContext());
	}

	/**
	 * @param context
	 * @return value of CloudConnectorLocationId
	 */
	public final java.lang.String getCloudConnectorLocationId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CloudConnectorLocationId.toString());
	}

	/**
	 * Set value of CloudConnectorLocationId
	 * @param cloudconnectorlocationid
	 */
	public final void setCloudConnectorLocationId(java.lang.String cloudconnectorlocationid)
	{
		setCloudConnectorLocationId(getContext(), cloudconnectorlocationid);
	}

	/**
	 * Set value of CloudConnectorLocationId
	 * @param context
	 * @param cloudconnectorlocationid
	 */
	public final void setCloudConnectorLocationId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cloudconnectorlocationid)
	{
		getMendixObject().setValue(context, MemberNames.CloudConnectorLocationId.toString(), cloudconnectorlocationid);
	}

	/**
	 * @return value of DestinationConfiguration_Root
	 */
	public final sapodataconnector.proxies.Root getDestinationConfiguration_Root() throws com.mendix.core.CoreException
	{
		return getDestinationConfiguration_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DestinationConfiguration_Root
	 */
	public final sapodataconnector.proxies.Root getDestinationConfiguration_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sapodataconnector.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DestinationConfiguration_Root.toString());
		if (identifier != null)
			result = sapodataconnector.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DestinationConfiguration_Root
	 * @param destinationconfiguration_root
	 */
	public final void setDestinationConfiguration_Root(sapodataconnector.proxies.Root destinationconfiguration_root)
	{
		setDestinationConfiguration_Root(getContext(), destinationconfiguration_root);
	}

	/**
	 * Set value of DestinationConfiguration_Root
	 * @param context
	 * @param destinationconfiguration_root
	 */
	public final void setDestinationConfiguration_Root(com.mendix.systemwideinterfaces.core.IContext context, sapodataconnector.proxies.Root destinationconfiguration_root)
	{
		if (destinationconfiguration_root == null)
			getMendixObject().setValue(context, MemberNames.DestinationConfiguration_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DestinationConfiguration_Root.toString(), destinationconfiguration_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return destinationConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sapodataconnector.proxies.DestinationConfiguration that = (sapodataconnector.proxies.DestinationConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAPODataConnector.DestinationConfiguration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
