// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SAPODataConnector.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DestinationConfiguration_Root("SAPODataConnector.DestinationConfiguration_Root"),
		AuthTokens_Root("SAPODataConnector.AuthTokens_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SAPODataConnector.Root"));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SAPODataConnector.Root", rootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SAPODataConnector.Root");

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sapodataconnector.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sapodataconnector.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sapodataconnector.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sapodataconnector.proxies.Root(context, mendixObject);
	}

	public static sapodataconnector.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sapodataconnector.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DestinationConfiguration_Root
	 */
	public final sapodataconnector.proxies.DestinationConfiguration getDestinationConfiguration_Root() throws com.mendix.core.CoreException
	{
		return getDestinationConfiguration_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of DestinationConfiguration_Root
	 */
	public final sapodataconnector.proxies.DestinationConfiguration getDestinationConfiguration_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sapodataconnector.proxies.DestinationConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DestinationConfiguration_Root.toString());
		if (identifier != null)
			result = sapodataconnector.proxies.DestinationConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DestinationConfiguration_Root
	 * @param destinationconfiguration_root
	 */
	public final void setDestinationConfiguration_Root(sapodataconnector.proxies.DestinationConfiguration destinationconfiguration_root)
	{
		setDestinationConfiguration_Root(getContext(), destinationconfiguration_root);
	}

	/**
	 * Set value of DestinationConfiguration_Root
	 * @param context
	 * @param destinationconfiguration_root
	 */
	public final void setDestinationConfiguration_Root(com.mendix.systemwideinterfaces.core.IContext context, sapodataconnector.proxies.DestinationConfiguration destinationconfiguration_root)
	{
		if (destinationconfiguration_root == null)
			getMendixObject().setValue(context, MemberNames.DestinationConfiguration_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DestinationConfiguration_Root.toString(), destinationconfiguration_root.getMendixObject().getId());
	}

	/**
	 * @return value of AuthTokens_Root
	 */
	public final sapodataconnector.proxies.AuthTokens getAuthTokens_Root() throws com.mendix.core.CoreException
	{
		return getAuthTokens_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthTokens_Root
	 */
	public final sapodataconnector.proxies.AuthTokens getAuthTokens_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sapodataconnector.proxies.AuthTokens result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AuthTokens_Root.toString());
		if (identifier != null)
			result = sapodataconnector.proxies.AuthTokens.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AuthTokens_Root
	 * @param authtokens_root
	 */
	public final void setAuthTokens_Root(sapodataconnector.proxies.AuthTokens authtokens_root)
	{
		setAuthTokens_Root(getContext(), authtokens_root);
	}

	/**
	 * Set value of AuthTokens_Root
	 * @param context
	 * @param authtokens_root
	 */
	public final void setAuthTokens_Root(com.mendix.systemwideinterfaces.core.IContext context, sapodataconnector.proxies.AuthTokens authtokens_root)
	{
		if (authtokens_root == null)
			getMendixObject().setValue(context, MemberNames.AuthTokens_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AuthTokens_Root.toString(), authtokens_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sapodataconnector.proxies.Root that = (sapodataconnector.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SAPODataConnector.Root";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
