// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sapodataconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the SAPODataConnector module
	public static sapodataconnector.proxies.Destination getDestinationInternal(IContext context, java.lang.String _destinationName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DestinationName", _destinationName);
		IMendixObject result = (IMendixObject)Core.microflowCall("SAPODataConnector.GetDestinationInternal").withParams(params).execute(context);
		return result == null ? null : sapodataconnector.proxies.Destination.initialize(context, result);
	}
	public static sapodataconnector.proxies.ConnectivityInfo sUB_ExtractConnectivityInfo(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("SAPODataConnector.SUB_ExtractConnectivityInfo").withParams(params).execute(context);
		return result == null ? null : sapodataconnector.proxies.ConnectivityInfo.initialize(context, result);
	}
	public static sapodataconnector.proxies.JsonObject sUB_ExtractSamlBearer(IContext context, sapodataconnector.proxies.Root _parsedDestinationPayload)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ParsedDestinationPayload", _parsedDestinationPayload == null ? null : _parsedDestinationPayload.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("SAPODataConnector.SUB_ExtractSamlBearer").withParams(params).execute(context);
		return result == null ? null : sapodataconnector.proxies.JsonObject.initialize(context, result);
	}
}