// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package appmain.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AppMain module

	public static java.lang.String getBilling_API_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("AppMain.Billing_API_URL");
	}
}