// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package iot.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the IoT module

	public static java.lang.Long getSecondsPast()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("IoT.SecondsPast");
	}
}