// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datadogapi.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DatadogAPI module

	public static java.lang.String getDATADOG_API_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DatadogAPI.DATADOG_API_KEY");
	}

	public static java.lang.String getDATADOG_API_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DatadogAPI.DATADOG_API_URL");
	}

	public static java.lang.String getIPAPI_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DatadogAPI.IPAPI_URL");
	}
}