// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datadogapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DatadogAPI module
	public static void dD_PostSeries(IContext context, java.lang.String _host, java.lang.String _metric, java.lang.String _timestamp_in_seconds, java.lang.String _value, java.lang.String _tags, java.lang.String _type)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("host", _host);
		params.put("metric", _metric);
		params.put("timestamp_in_seconds", _timestamp_in_seconds);
		params.put("value", _value);
		params.put("tags", _tags);
		params.put("type", _type);
		Core.microflowCall("DatadogAPI.DD_PostSeries").withParams(params).execute(context);
	}
	public static void dD_SubmitCountData(IContext context, java.lang.String _host, java.lang.String _metric, java.lang.String _tags)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Host", _host);
		params.put("Metric", _metric);
		params.put("Tags", _tags);
		Core.microflowCall("DatadogAPI.DD_SubmitCountData").withParams(params).execute(context);
	}
	public static datadogapi.proxies.Response iPAPI(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DatadogAPI.IPAPI").withParams(params).execute(context);
		return result == null ? null : datadogapi.proxies.Response.initialize(context, result);
	}
	public static void windowsUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DatadogAPI.WindowsUser").withParams(params).execute(context);
	}
}