// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class ActivityHistory extends salesforce_connector.proxies.SObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.ActivityHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActivityDate("ActivityDate"),
		Subject("Subject"),
		Description("Description"),
		IsTask("IsTask"),
		ActivityDateTime("ActivityDateTime"),
		Status("Status"),
		ActivityType("ActivityType"),
		IsDeleted("IsDeleted"),
		Activateable("Activateable"),
		Createable("Createable"),
		Custom("Custom"),
		CustomSetting("CustomSetting"),
		Deletable("Deletable"),
		DeprecatedAndHidden("DeprecatedAndHidden"),
		FeedEnabled("FeedEnabled"),
		HasSubtypes("HasSubtypes"),
		IsSubtype("IsSubtype"),
		Label("Label"),
		LabelPlural("LabelPlural"),
		Layoutable("Layoutable"),
		Mergeable("Mergeable"),
		MruEnabled("MruEnabled"),
		SObjectName("SObjectName"),
		Queryable("Queryable"),
		Replicateable("Replicateable"),
		Retrieveable("Retrieveable"),
		Searchable("Searchable"),
		Triggerable("Triggerable"),
		Undeletable("Undeletable"),
		Updateable("Updateable"),
		KeyPrefix("KeyPrefix"),
		_Id("_Id"),
		Name("Name"),
		LastModifiedDate("LastModifiedDate"),
		LastModifiedById("LastModifiedById"),
		_CreatedDate("_CreatedDate"),
		CreatedById("CreatedById"),
		ActivityHistory_Records("Salesforce_Connector.ActivityHistory_Records"),
		Urls_SObject("Salesforce_Connector.Urls_SObject"),
		SObject_Query("Salesforce_Connector.SObject_Query"),
		Attributes_SObject("Salesforce_Connector.Attributes_SObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ActivityHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.ActivityHistory"));
	}

	protected ActivityHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject activityHistoryMendixObject)
	{
		super(context, activityHistoryMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.ActivityHistory", activityHistoryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.ActivityHistory");
	}

	/**
	 * @deprecated Use 'ActivityHistory.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.ActivityHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.ActivityHistory.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.ActivityHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.ActivityHistory(context, mendixObject);
	}

	public static salesforce_connector.proxies.ActivityHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.ActivityHistory.initialize(context, mendixObject);
	}

	/**
	 * @return value of ActivityDate
	 */
	public final java.util.Date getActivityDate()
	{
		return getActivityDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityDate
	 */
	public final java.util.Date getActivityDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActivityDate.toString());
	}

	/**
	 * Set value of ActivityDate
	 * @param activitydate
	 */
	public final void setActivityDate(java.util.Date activitydate)
	{
		setActivityDate(getContext(), activitydate);
	}

	/**
	 * Set value of ActivityDate
	 * @param context
	 * @param activitydate
	 */
	public final void setActivityDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date activitydate)
	{
		getMendixObject().setValue(context, MemberNames.ActivityDate.toString(), activitydate);
	}

	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of IsTask
	 */
	public final java.lang.Boolean getIsTask()
	{
		return getIsTask(getContext());
	}

	/**
	 * @param context
	 * @return value of IsTask
	 */
	public final java.lang.Boolean getIsTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsTask.toString());
	}

	/**
	 * Set value of IsTask
	 * @param istask
	 */
	public final void setIsTask(java.lang.Boolean istask)
	{
		setIsTask(getContext(), istask);
	}

	/**
	 * Set value of IsTask
	 * @param context
	 * @param istask
	 */
	public final void setIsTask(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean istask)
	{
		getMendixObject().setValue(context, MemberNames.IsTask.toString(), istask);
	}

	/**
	 * @return value of ActivityDateTime
	 */
	public final java.util.Date getActivityDateTime()
	{
		return getActivityDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityDateTime
	 */
	public final java.util.Date getActivityDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ActivityDateTime.toString());
	}

	/**
	 * Set value of ActivityDateTime
	 * @param activitydatetime
	 */
	public final void setActivityDateTime(java.util.Date activitydatetime)
	{
		setActivityDateTime(getContext(), activitydatetime);
	}

	/**
	 * Set value of ActivityDateTime
	 * @param context
	 * @param activitydatetime
	 */
	public final void setActivityDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date activitydatetime)
	{
		getMendixObject().setValue(context, MemberNames.ActivityDateTime.toString(), activitydatetime);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of ActivityType
	 */
	public final java.lang.String getActivityType()
	{
		return getActivityType(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityType
	 */
	public final java.lang.String getActivityType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActivityType.toString());
	}

	/**
	 * Set value of ActivityType
	 * @param activitytype
	 */
	public final void setActivityType(java.lang.String activitytype)
	{
		setActivityType(getContext(), activitytype);
	}

	/**
	 * Set value of ActivityType
	 * @param context
	 * @param activitytype
	 */
	public final void setActivityType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String activitytype)
	{
		getMendixObject().setValue(context, MemberNames.ActivityType.toString(), activitytype);
	}

	/**
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted()
	{
		return getIsDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDeleted.toString());
	}

	/**
	 * Set value of IsDeleted
	 * @param isdeleted
	 */
	public final void setIsDeleted(java.lang.Boolean isdeleted)
	{
		setIsDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of IsDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setIsDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.IsDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of ActivityHistory_Records
	 */
	public final salesforce_connector.proxies.Records getActivityHistory_Records() throws com.mendix.core.CoreException
	{
		return getActivityHistory_Records(getContext());
	}

	/**
	 * @param context
	 * @return value of ActivityHistory_Records
	 */
	public final salesforce_connector.proxies.Records getActivityHistory_Records(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Records result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ActivityHistory_Records.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Records.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ActivityHistory_Records
	 * @param activityhistory_records
	 */
	public final void setActivityHistory_Records(salesforce_connector.proxies.Records activityhistory_records)
	{
		setActivityHistory_Records(getContext(), activityhistory_records);
	}

	/**
	 * Set value of ActivityHistory_Records
	 * @param context
	 * @param activityhistory_records
	 */
	public final void setActivityHistory_Records(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Records activityhistory_records)
	{
		if (activityhistory_records == null)
			getMendixObject().setValue(context, MemberNames.ActivityHistory_Records.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ActivityHistory_Records.toString(), activityhistory_records.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.ActivityHistory that = (salesforce_connector.proxies.ActivityHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.ActivityHistory";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
