// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Attachment extends salesforce_connector.proxies.SObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Attachment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsDeleted("IsDeleted"),
		ParentId("ParentId"),
		IsPrivate("IsPrivate"),
		ContentType("ContentType"),
		BodyLength("BodyLength"),
		Body("Body"),
		OwnerId("OwnerId"),
		SystemModstamp("SystemModstamp"),
		Description("Description"),
		Activateable("Activateable"),
		Createable("Createable"),
		Custom("Custom"),
		CustomSetting("CustomSetting"),
		Deletable("Deletable"),
		DeprecatedAndHidden("DeprecatedAndHidden"),
		FeedEnabled("FeedEnabled"),
		HasSubtypes("HasSubtypes"),
		IsSubtype("IsSubtype"),
		Label("Label"),
		LabelPlural("LabelPlural"),
		Layoutable("Layoutable"),
		Mergeable("Mergeable"),
		MruEnabled("MruEnabled"),
		SObjectName("SObjectName"),
		Queryable("Queryable"),
		Replicateable("Replicateable"),
		Retrieveable("Retrieveable"),
		Searchable("Searchable"),
		Triggerable("Triggerable"),
		Undeletable("Undeletable"),
		Updateable("Updateable"),
		KeyPrefix("KeyPrefix"),
		_Id("_Id"),
		Name("Name"),
		LastModifiedDate("LastModifiedDate"),
		LastModifiedById("LastModifiedById"),
		_CreatedDate("_CreatedDate"),
		CreatedById("CreatedById"),
		Attachment_Records("Salesforce_Connector.Attachment_Records"),
		Urls_SObject("Salesforce_Connector.Urls_SObject"),
		SObject_Query("Salesforce_Connector.SObject_Query"),
		Attributes_SObject("Salesforce_Connector.Attributes_SObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attachment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Attachment"));
	}

	protected Attachment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentMendixObject)
	{
		super(context, attachmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Attachment", attachmentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Attachment");
	}

	/**
	 * @deprecated Use 'Attachment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Attachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Attachment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Attachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Attachment(context, mendixObject);
	}

	public static salesforce_connector.proxies.Attachment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Attachment.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted()
	{
		return getIsDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDeleted.toString());
	}

	/**
	 * Set value of IsDeleted
	 * @param isdeleted
	 */
	public final void setIsDeleted(java.lang.Boolean isdeleted)
	{
		setIsDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of IsDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setIsDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.IsDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of ParentId
	 */
	public final java.lang.String getParentId()
	{
		return getParentId(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentId
	 */
	public final java.lang.String getParentId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentId.toString());
	}

	/**
	 * Set value of ParentId
	 * @param parentid
	 */
	public final void setParentId(java.lang.String parentid)
	{
		setParentId(getContext(), parentid);
	}

	/**
	 * Set value of ParentId
	 * @param context
	 * @param parentid
	 */
	public final void setParentId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentid)
	{
		getMendixObject().setValue(context, MemberNames.ParentId.toString(), parentid);
	}

	/**
	 * @return value of IsPrivate
	 */
	public final java.lang.Boolean getIsPrivate()
	{
		return getIsPrivate(getContext());
	}

	/**
	 * @param context
	 * @return value of IsPrivate
	 */
	public final java.lang.Boolean getIsPrivate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsPrivate.toString());
	}

	/**
	 * Set value of IsPrivate
	 * @param isprivate
	 */
	public final void setIsPrivate(java.lang.Boolean isprivate)
	{
		setIsPrivate(getContext(), isprivate);
	}

	/**
	 * Set value of IsPrivate
	 * @param context
	 * @param isprivate
	 */
	public final void setIsPrivate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isprivate)
	{
		getMendixObject().setValue(context, MemberNames.IsPrivate.toString(), isprivate);
	}

	/**
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType()
	{
		return getContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentType
	 */
	public final java.lang.String getContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentType.toString());
	}

	/**
	 * Set value of ContentType
	 * @param contenttype
	 */
	public final void setContentType(java.lang.String contenttype)
	{
		setContentType(getContext(), contenttype);
	}

	/**
	 * Set value of ContentType
	 * @param context
	 * @param contenttype
	 */
	public final void setContentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contenttype)
	{
		getMendixObject().setValue(context, MemberNames.ContentType.toString(), contenttype);
	}

	/**
	 * @return value of BodyLength
	 */
	public final java.lang.Integer getBodyLength()
	{
		return getBodyLength(getContext());
	}

	/**
	 * @param context
	 * @return value of BodyLength
	 */
	public final java.lang.Integer getBodyLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BodyLength.toString());
	}

	/**
	 * Set value of BodyLength
	 * @param bodylength
	 */
	public final void setBodyLength(java.lang.Integer bodylength)
	{
		setBodyLength(getContext(), bodylength);
	}

	/**
	 * Set value of BodyLength
	 * @param context
	 * @param bodylength
	 */
	public final void setBodyLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bodylength)
	{
		getMendixObject().setValue(context, MemberNames.BodyLength.toString(), bodylength);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of OwnerId
	 */
	public final java.lang.String getOwnerId()
	{
		return getOwnerId(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerId
	 */
	public final java.lang.String getOwnerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerId.toString());
	}

	/**
	 * Set value of OwnerId
	 * @param ownerid
	 */
	public final void setOwnerId(java.lang.String ownerid)
	{
		setOwnerId(getContext(), ownerid);
	}

	/**
	 * Set value of OwnerId
	 * @param context
	 * @param ownerid
	 */
	public final void setOwnerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownerid)
	{
		getMendixObject().setValue(context, MemberNames.OwnerId.toString(), ownerid);
	}

	/**
	 * @return value of SystemModstamp
	 */
	public final java.util.Date getSystemModstamp()
	{
		return getSystemModstamp(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemModstamp
	 */
	public final java.util.Date getSystemModstamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SystemModstamp.toString());
	}

	/**
	 * Set value of SystemModstamp
	 * @param systemmodstamp
	 */
	public final void setSystemModstamp(java.util.Date systemmodstamp)
	{
		setSystemModstamp(getContext(), systemmodstamp);
	}

	/**
	 * Set value of SystemModstamp
	 * @param context
	 * @param systemmodstamp
	 */
	public final void setSystemModstamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date systemmodstamp)
	{
		getMendixObject().setValue(context, MemberNames.SystemModstamp.toString(), systemmodstamp);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Attachment_Records
	 */
	public final salesforce_connector.proxies.Records getAttachment_Records() throws com.mendix.core.CoreException
	{
		return getAttachment_Records(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachment_Records
	 */
	public final salesforce_connector.proxies.Records getAttachment_Records(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Records result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachment_Records.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Records.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attachment_Records
	 * @param attachment_records
	 */
	public final void setAttachment_Records(salesforce_connector.proxies.Records attachment_records)
	{
		setAttachment_Records(getContext(), attachment_records);
	}

	/**
	 * Set value of Attachment_Records
	 * @param context
	 * @param attachment_records
	 */
	public final void setAttachment_Records(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Records attachment_records)
	{
		if (attachment_records == null)
			getMendixObject().setValue(context, MemberNames.Attachment_Records.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attachment_Records.toString(), attachment_records.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Attachment that = (salesforce_connector.proxies.Attachment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Attachment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
