// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Authentication
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject authenticationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Authentication";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConnectedApp("ConnectedApp"),
		UserName("UserName"),
		Password("Password"),
		Token("Token"),
		ServiceVersion("ServiceVersion"),
		ConsumerKey("ConsumerKey"),
		ConsumerSecret("ConsumerSecret"),
		IsActive("IsActive"),
		Successful("Successful"),
		Environment("Environment"),
		AuthenticationFlow("AuthenticationFlow");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Authentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Authentication"));
	}

	protected Authentication(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject authenticationMendixObject)
	{
		if (authenticationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Authentication", authenticationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Authentication");

		this.authenticationMendixObject = authenticationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Authentication.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Authentication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Authentication.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Authentication initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Authentication(context, mendixObject);
	}

	public static salesforce_connector.proxies.Authentication load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Authentication.initialize(context, mendixObject);
	}

	public static java.util.List<salesforce_connector.proxies.Authentication> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<salesforce_connector.proxies.Authentication> result = new java.util.ArrayList<salesforce_connector.proxies.Authentication>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Salesforce_Connector.Authentication" + xpathConstraint))
			result.add(salesforce_connector.proxies.Authentication.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ConnectedApp
	 */
	public final java.lang.String getConnectedApp()
	{
		return getConnectedApp(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectedApp
	 */
	public final java.lang.String getConnectedApp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConnectedApp.toString());
	}

	/**
	 * Set value of ConnectedApp
	 * @param connectedapp
	 */
	public final void setConnectedApp(java.lang.String connectedapp)
	{
		setConnectedApp(getContext(), connectedapp);
	}

	/**
	 * Set value of ConnectedApp
	 * @param context
	 * @param connectedapp
	 */
	public final void setConnectedApp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String connectedapp)
	{
		getMendixObject().setValue(context, MemberNames.ConnectedApp.toString(), connectedapp);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Token
	 */
	public final java.lang.String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final java.lang.String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(java.lang.String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of ServiceVersion
	 */
	public final java.lang.String getServiceVersion()
	{
		return getServiceVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceVersion
	 */
	public final java.lang.String getServiceVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceVersion.toString());
	}

	/**
	 * Set value of ServiceVersion
	 * @param serviceversion
	 */
	public final void setServiceVersion(java.lang.String serviceversion)
	{
		setServiceVersion(getContext(), serviceversion);
	}

	/**
	 * Set value of ServiceVersion
	 * @param context
	 * @param serviceversion
	 */
	public final void setServiceVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serviceversion)
	{
		getMendixObject().setValue(context, MemberNames.ServiceVersion.toString(), serviceversion);
	}

	/**
	 * @return value of ConsumerKey
	 */
	public final java.lang.String getConsumerKey()
	{
		return getConsumerKey(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsumerKey
	 */
	public final java.lang.String getConsumerKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConsumerKey.toString());
	}

	/**
	 * Set value of ConsumerKey
	 * @param consumerkey
	 */
	public final void setConsumerKey(java.lang.String consumerkey)
	{
		setConsumerKey(getContext(), consumerkey);
	}

	/**
	 * Set value of ConsumerKey
	 * @param context
	 * @param consumerkey
	 */
	public final void setConsumerKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String consumerkey)
	{
		getMendixObject().setValue(context, MemberNames.ConsumerKey.toString(), consumerkey);
	}

	/**
	 * @return value of ConsumerSecret
	 */
	public final java.lang.String getConsumerSecret()
	{
		return getConsumerSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of ConsumerSecret
	 */
	public final java.lang.String getConsumerSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConsumerSecret.toString());
	}

	/**
	 * Set value of ConsumerSecret
	 * @param consumersecret
	 */
	public final void setConsumerSecret(java.lang.String consumersecret)
	{
		setConsumerSecret(getContext(), consumersecret);
	}

	/**
	 * Set value of ConsumerSecret
	 * @param context
	 * @param consumersecret
	 */
	public final void setConsumerSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String consumersecret)
	{
		getMendixObject().setValue(context, MemberNames.ConsumerSecret.toString(), consumersecret);
	}

	/**
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive()
	{
		return getIsActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsActive
	 */
	public final java.lang.Boolean getIsActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsActive.toString());
	}

	/**
	 * Set value of IsActive
	 * @param isactive
	 */
	public final void setIsActive(java.lang.Boolean isactive)
	{
		setIsActive(getContext(), isactive);
	}

	/**
	 * Set value of IsActive
	 * @param context
	 * @param isactive
	 */
	public final void setIsActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.IsActive.toString(), isactive);
	}

	/**
	 * @return value of Successful
	 */
	public final java.lang.Boolean getSuccessful()
	{
		return getSuccessful(getContext());
	}

	/**
	 * @param context
	 * @return value of Successful
	 */
	public final java.lang.Boolean getSuccessful(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Successful.toString());
	}

	/**
	 * Set value of Successful
	 * @param successful
	 */
	public final void setSuccessful(java.lang.Boolean successful)
	{
		setSuccessful(getContext(), successful);
	}

	/**
	 * Set value of Successful
	 * @param context
	 * @param successful
	 */
	public final void setSuccessful(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean successful)
	{
		getMendixObject().setValue(context, MemberNames.Successful.toString(), successful);
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final salesforce_connector.proxies.Environment getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final salesforce_connector.proxies.Environment getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Environment.toString());
		if (obj == null)
			return null;

		return salesforce_connector.proxies.Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(salesforce_connector.proxies.Environment environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Environment environment)
	{
		if (environment != null)
			getMendixObject().setValue(context, MemberNames.Environment.toString(), environment.toString());
		else
			getMendixObject().setValue(context, MemberNames.Environment.toString(), null);
	}

	/**
	 * Set value of AuthenticationFlow
	 * @param authenticationflow
	 */
	public final salesforce_connector.proxies.AuthenticationFlow getAuthenticationFlow()
	{
		return getAuthenticationFlow(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthenticationFlow
	 */
	public final salesforce_connector.proxies.AuthenticationFlow getAuthenticationFlow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AuthenticationFlow.toString());
		if (obj == null)
			return null;

		return salesforce_connector.proxies.AuthenticationFlow.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AuthenticationFlow
	 * @param authenticationflow
	 */
	public final void setAuthenticationFlow(salesforce_connector.proxies.AuthenticationFlow authenticationflow)
	{
		setAuthenticationFlow(getContext(), authenticationflow);
	}

	/**
	 * Set value of AuthenticationFlow
	 * @param context
	 * @param authenticationflow
	 */
	public final void setAuthenticationFlow(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.AuthenticationFlow authenticationflow)
	{
		if (authenticationflow != null)
			getMendixObject().setValue(context, MemberNames.AuthenticationFlow.toString(), authenticationflow.toString());
		else
			getMendixObject().setValue(context, MemberNames.AuthenticationFlow.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return authenticationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Authentication that = (salesforce_connector.proxies.Authentication) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Authentication";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
