// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Authorization
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject authorizationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Authorization";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Refresh_token("Refresh_token"),
		Instance_url("Instance_url"),
		_id("_id"),
		Id_token("Id_token"),
		Token_type("Token_type"),
		Issued_at("Issued_at"),
		Signature("Signature"),
		Code("Code"),
		State("State"),
		Nonce("Nonce"),
		Scope("Scope"),
		AuthorizationSuccessful("AuthorizationSuccessful"),
		Authorization_Authentication("Salesforce_Connector.Authorization_Authentication"),
		Authorization_User("Salesforce_Connector.Authorization_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Authorization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Authorization"));
	}

	protected Authorization(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject authorizationMendixObject)
	{
		if (authorizationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Authorization", authorizationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Authorization");

		this.authorizationMendixObject = authorizationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Authorization.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Authorization initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Authorization.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Authorization initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Authorization(context, mendixObject);
	}

	public static salesforce_connector.proxies.Authorization load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Authorization.initialize(context, mendixObject);
	}

	public static java.util.List<salesforce_connector.proxies.Authorization> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<salesforce_connector.proxies.Authorization> result = new java.util.ArrayList<salesforce_connector.proxies.Authorization>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Salesforce_Connector.Authorization" + xpathConstraint))
			result.add(salesforce_connector.proxies.Authorization.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token()
	{
		return getRefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Refresh_token
	 */
	public final java.lang.String getRefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Refresh_token.toString());
	}

	/**
	 * Set value of Refresh_token
	 * @param refresh_token
	 */
	public final void setRefresh_token(java.lang.String refresh_token)
	{
		setRefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of Refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setRefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.Refresh_token.toString(), refresh_token);
	}

	/**
	 * @return value of Instance_url
	 */
	public final java.lang.String getInstance_url()
	{
		return getInstance_url(getContext());
	}

	/**
	 * @param context
	 * @return value of Instance_url
	 */
	public final java.lang.String getInstance_url(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instance_url.toString());
	}

	/**
	 * Set value of Instance_url
	 * @param instance_url
	 */
	public final void setInstance_url(java.lang.String instance_url)
	{
		setInstance_url(getContext(), instance_url);
	}

	/**
	 * Set value of Instance_url
	 * @param context
	 * @param instance_url
	 */
	public final void setInstance_url(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instance_url)
	{
		getMendixObject().setValue(context, MemberNames.Instance_url.toString(), instance_url);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token()
	{
		return getId_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Id_token
	 */
	public final java.lang.String getId_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Id_token.toString());
	}

	/**
	 * Set value of Id_token
	 * @param id_token
	 */
	public final void setId_token(java.lang.String id_token)
	{
		setId_token(getContext(), id_token);
	}

	/**
	 * Set value of Id_token
	 * @param context
	 * @param id_token
	 */
	public final void setId_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String id_token)
	{
		getMendixObject().setValue(context, MemberNames.Id_token.toString(), id_token);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Issued_at
	 */
	public final java.lang.String getIssued_at()
	{
		return getIssued_at(getContext());
	}

	/**
	 * @param context
	 * @return value of Issued_at
	 */
	public final java.lang.String getIssued_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Issued_at.toString());
	}

	/**
	 * Set value of Issued_at
	 * @param issued_at
	 */
	public final void setIssued_at(java.lang.String issued_at)
	{
		setIssued_at(getContext(), issued_at);
	}

	/**
	 * Set value of Issued_at
	 * @param context
	 * @param issued_at
	 */
	public final void setIssued_at(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issued_at)
	{
		getMendixObject().setValue(context, MemberNames.Issued_at.toString(), issued_at);
	}

	/**
	 * @return value of Signature
	 */
	public final java.lang.String getSignature()
	{
		return getSignature(getContext());
	}

	/**
	 * @param context
	 * @return value of Signature
	 */
	public final java.lang.String getSignature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Signature.toString());
	}

	/**
	 * Set value of Signature
	 * @param signature
	 */
	public final void setSignature(java.lang.String signature)
	{
		setSignature(getContext(), signature);
	}

	/**
	 * Set value of Signature
	 * @param context
	 * @param signature
	 */
	public final void setSignature(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String signature)
	{
		getMendixObject().setValue(context, MemberNames.Signature.toString(), signature);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Nonce
	 */
	public final java.lang.String getNonce()
	{
		return getNonce(getContext());
	}

	/**
	 * @param context
	 * @return value of Nonce
	 */
	public final java.lang.String getNonce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nonce.toString());
	}

	/**
	 * Set value of Nonce
	 * @param nonce
	 */
	public final void setNonce(java.lang.String nonce)
	{
		setNonce(getContext(), nonce);
	}

	/**
	 * Set value of Nonce
	 * @param context
	 * @param nonce
	 */
	public final void setNonce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nonce)
	{
		getMendixObject().setValue(context, MemberNames.Nonce.toString(), nonce);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of AuthorizationSuccessful
	 */
	public final java.lang.Boolean getAuthorizationSuccessful()
	{
		return getAuthorizationSuccessful(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationSuccessful
	 */
	public final java.lang.Boolean getAuthorizationSuccessful(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AuthorizationSuccessful.toString());
	}

	/**
	 * Set value of AuthorizationSuccessful
	 * @param authorizationsuccessful
	 */
	public final void setAuthorizationSuccessful(java.lang.Boolean authorizationsuccessful)
	{
		setAuthorizationSuccessful(getContext(), authorizationsuccessful);
	}

	/**
	 * Set value of AuthorizationSuccessful
	 * @param context
	 * @param authorizationsuccessful
	 */
	public final void setAuthorizationSuccessful(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean authorizationsuccessful)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationSuccessful.toString(), authorizationsuccessful);
	}

	/**
	 * @return value of Authorization_Authentication
	 */
	public final salesforce_connector.proxies.Authentication getAuthorization_Authentication() throws com.mendix.core.CoreException
	{
		return getAuthorization_Authentication(getContext());
	}

	/**
	 * @param context
	 * @return value of Authorization_Authentication
	 */
	public final salesforce_connector.proxies.Authentication getAuthorization_Authentication(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Authentication result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Authorization_Authentication.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Authentication.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Authorization_Authentication
	 * @param authorization_authentication
	 */
	public final void setAuthorization_Authentication(salesforce_connector.proxies.Authentication authorization_authentication)
	{
		setAuthorization_Authentication(getContext(), authorization_authentication);
	}

	/**
	 * Set value of Authorization_Authentication
	 * @param context
	 * @param authorization_authentication
	 */
	public final void setAuthorization_Authentication(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Authentication authorization_authentication)
	{
		if (authorization_authentication == null)
			getMendixObject().setValue(context, MemberNames.Authorization_Authentication.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Authorization_Authentication.toString(), authorization_authentication.getMendixObject().getId());
	}

	/**
	 * @return value of Authorization_User
	 */
	public final system.proxies.User getAuthorization_User() throws com.mendix.core.CoreException
	{
		return getAuthorization_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Authorization_User
	 */
	public final system.proxies.User getAuthorization_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Authorization_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Authorization_User
	 * @param authorization_user
	 */
	public final void setAuthorization_User(system.proxies.User authorization_user)
	{
		setAuthorization_User(getContext(), authorization_user);
	}

	/**
	 * Set value of Authorization_User
	 * @param context
	 * @param authorization_user
	 */
	public final void setAuthorization_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User authorization_user)
	{
		if (authorization_user == null)
			getMendixObject().setValue(context, MemberNames.Authorization_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Authorization_User.toString(), authorization_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return authorizationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Authorization that = (salesforce_connector.proxies.Authorization) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Authorization";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
