// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class CampaignMember extends salesforce_connector.proxies.SObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.CampaignMember";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Status("Status"),
		IsDeleted("IsDeleted"),
		CampaignId("CampaignId"),
		CampaignMemberType("CampaignMemberType"),
		Activateable("Activateable"),
		Createable("Createable"),
		Custom("Custom"),
		CustomSetting("CustomSetting"),
		Deletable("Deletable"),
		DeprecatedAndHidden("DeprecatedAndHidden"),
		FeedEnabled("FeedEnabled"),
		HasSubtypes("HasSubtypes"),
		IsSubtype("IsSubtype"),
		Label("Label"),
		LabelPlural("LabelPlural"),
		Layoutable("Layoutable"),
		Mergeable("Mergeable"),
		MruEnabled("MruEnabled"),
		SObjectName("SObjectName"),
		Queryable("Queryable"),
		Replicateable("Replicateable"),
		Retrieveable("Retrieveable"),
		Searchable("Searchable"),
		Triggerable("Triggerable"),
		Undeletable("Undeletable"),
		Updateable("Updateable"),
		KeyPrefix("KeyPrefix"),
		_Id("_Id"),
		Name("Name"),
		LastModifiedDate("LastModifiedDate"),
		LastModifiedById("LastModifiedById"),
		_CreatedDate("_CreatedDate"),
		CreatedById("CreatedById"),
		CampaignMember_Records("Salesforce_Connector.CampaignMember_Records"),
		CampaignMember_Campaign("Salesforce_Connector.CampaignMember_Campaign"),
		Urls_SObject("Salesforce_Connector.Urls_SObject"),
		SObject_Query("Salesforce_Connector.SObject_Query"),
		Attributes_SObject("Salesforce_Connector.Attributes_SObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CampaignMember(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.CampaignMember"));
	}

	protected CampaignMember(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject campaignMemberMendixObject)
	{
		super(context, campaignMemberMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.CampaignMember", campaignMemberMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.CampaignMember");
	}

	/**
	 * @deprecated Use 'CampaignMember.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.CampaignMember initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.CampaignMember.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.CampaignMember initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.CampaignMember(context, mendixObject);
	}

	public static salesforce_connector.proxies.CampaignMember load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.CampaignMember.initialize(context, mendixObject);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted()
	{
		return getIsDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDeleted.toString());
	}

	/**
	 * Set value of IsDeleted
	 * @param isdeleted
	 */
	public final void setIsDeleted(java.lang.Boolean isdeleted)
	{
		setIsDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of IsDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setIsDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.IsDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of CampaignId
	 */
	public final java.lang.String getCampaignId()
	{
		return getCampaignId(getContext());
	}

	/**
	 * @param context
	 * @return value of CampaignId
	 */
	public final java.lang.String getCampaignId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CampaignId.toString());
	}

	/**
	 * Set value of CampaignId
	 * @param campaignid
	 */
	public final void setCampaignId(java.lang.String campaignid)
	{
		setCampaignId(getContext(), campaignid);
	}

	/**
	 * Set value of CampaignId
	 * @param context
	 * @param campaignid
	 */
	public final void setCampaignId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String campaignid)
	{
		getMendixObject().setValue(context, MemberNames.CampaignId.toString(), campaignid);
	}

	/**
	 * @return value of CampaignMemberType
	 */
	public final java.lang.String getCampaignMemberType()
	{
		return getCampaignMemberType(getContext());
	}

	/**
	 * @param context
	 * @return value of CampaignMemberType
	 */
	public final java.lang.String getCampaignMemberType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CampaignMemberType.toString());
	}

	/**
	 * Set value of CampaignMemberType
	 * @param campaignmembertype
	 */
	public final void setCampaignMemberType(java.lang.String campaignmembertype)
	{
		setCampaignMemberType(getContext(), campaignmembertype);
	}

	/**
	 * Set value of CampaignMemberType
	 * @param context
	 * @param campaignmembertype
	 */
	public final void setCampaignMemberType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String campaignmembertype)
	{
		getMendixObject().setValue(context, MemberNames.CampaignMemberType.toString(), campaignmembertype);
	}

	/**
	 * @return value of CampaignMember_Records
	 */
	public final salesforce_connector.proxies.Records getCampaignMember_Records() throws com.mendix.core.CoreException
	{
		return getCampaignMember_Records(getContext());
	}

	/**
	 * @param context
	 * @return value of CampaignMember_Records
	 */
	public final salesforce_connector.proxies.Records getCampaignMember_Records(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Records result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CampaignMember_Records.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Records.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CampaignMember_Records
	 * @param campaignmember_records
	 */
	public final void setCampaignMember_Records(salesforce_connector.proxies.Records campaignmember_records)
	{
		setCampaignMember_Records(getContext(), campaignmember_records);
	}

	/**
	 * Set value of CampaignMember_Records
	 * @param context
	 * @param campaignmember_records
	 */
	public final void setCampaignMember_Records(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Records campaignmember_records)
	{
		if (campaignmember_records == null)
			getMendixObject().setValue(context, MemberNames.CampaignMember_Records.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CampaignMember_Records.toString(), campaignmember_records.getMendixObject().getId());
	}

	/**
	 * @return value of CampaignMember_Campaign
	 */
	public final salesforce_connector.proxies.Campaign getCampaignMember_Campaign() throws com.mendix.core.CoreException
	{
		return getCampaignMember_Campaign(getContext());
	}

	/**
	 * @param context
	 * @return value of CampaignMember_Campaign
	 */
	public final salesforce_connector.proxies.Campaign getCampaignMember_Campaign(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Campaign result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CampaignMember_Campaign.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Campaign.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CampaignMember_Campaign
	 * @param campaignmember_campaign
	 */
	public final void setCampaignMember_Campaign(salesforce_connector.proxies.Campaign campaignmember_campaign)
	{
		setCampaignMember_Campaign(getContext(), campaignmember_campaign);
	}

	/**
	 * Set value of CampaignMember_Campaign
	 * @param context
	 * @param campaignmember_campaign
	 */
	public final void setCampaignMember_Campaign(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Campaign campaignmember_campaign)
	{
		if (campaignmember_campaign == null)
			getMendixObject().setValue(context, MemberNames.CampaignMember_Campaign.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CampaignMember_Campaign.toString(), campaignmember_campaign.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.CampaignMember that = (salesforce_connector.proxies.CampaignMember) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.CampaignMember";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
