// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class fields
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fieldsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.fields";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Aggregatable("Aggregatable"),
		AiPredictionField("AiPredictionField"),
		AutoNumber("AutoNumber"),
		ByteLength("ByteLength"),
		Calculated("Calculated"),
		CascadeDelete("CascadeDelete"),
		CaseSensitive("CaseSensitive"),
		Createable("Createable"),
		Custom("Custom"),
		DefaultedOnCreate("DefaultedOnCreate"),
		DependentPicklist("DependentPicklist"),
		DeprecatedAndHidden("DeprecatedAndHidden"),
		Digits("Digits"),
		DisplayLocationInDecimal("DisplayLocationInDecimal"),
		Encrypted("Encrypted"),
		ExternalId("ExternalId"),
		Filterable("Filterable"),
		FormulaTreatNullNumberAsZero("FormulaTreatNullNumberAsZero"),
		Groupable("Groupable"),
		HighScaleNumber("HighScaleNumber"),
		HtmlFormatted("HtmlFormatted"),
		IdLookup("IdLookup"),
		Label("Label"),
		Length("Length"),
		Name("Name"),
		NameField("NameField"),
		NamePointing("NamePointing"),
		Nillable("Nillable"),
		Permissionable("Permissionable"),
		PolymorphicForeignKey("PolymorphicForeignKey"),
		Precision("Precision"),
		QueryByDistance("QueryByDistance"),
		RestrictedDelete("RestrictedDelete"),
		RestrictedPicklist("RestrictedPicklist"),
		Scale("Scale"),
		SearchPrefilterable("SearchPrefilterable"),
		SoapType("SoapType"),
		Sortable("Sortable"),
		_type("_type"),
		Unique("Unique"),
		Updateable("Updateable"),
		WriteRequiresMasterRead("WriteRequiresMasterRead"),
		fields_SObject("Salesforce_Connector.fields_SObject"),
		PicklistValues_fields("Salesforce_Connector.PicklistValues_fields"),
		ReferenceTo_fields("Salesforce_Connector.ReferenceTo_fields");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public fields(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.fields"));
	}

	protected fields(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fieldsMendixObject)
	{
		if (fieldsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.fields", fieldsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.fields");

		this.fieldsMendixObject = fieldsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'fields.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.fields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.fields.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.fields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.fields(context, mendixObject);
	}

	public static salesforce_connector.proxies.fields load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.fields.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Aggregatable
	 */
	public final java.lang.Boolean getAggregatable()
	{
		return getAggregatable(getContext());
	}

	/**
	 * @param context
	 * @return value of Aggregatable
	 */
	public final java.lang.Boolean getAggregatable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Aggregatable.toString());
	}

	/**
	 * Set value of Aggregatable
	 * @param aggregatable
	 */
	public final void setAggregatable(java.lang.Boolean aggregatable)
	{
		setAggregatable(getContext(), aggregatable);
	}

	/**
	 * Set value of Aggregatable
	 * @param context
	 * @param aggregatable
	 */
	public final void setAggregatable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean aggregatable)
	{
		getMendixObject().setValue(context, MemberNames.Aggregatable.toString(), aggregatable);
	}

	/**
	 * @return value of AiPredictionField
	 */
	public final java.lang.Boolean getAiPredictionField()
	{
		return getAiPredictionField(getContext());
	}

	/**
	 * @param context
	 * @return value of AiPredictionField
	 */
	public final java.lang.Boolean getAiPredictionField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AiPredictionField.toString());
	}

	/**
	 * Set value of AiPredictionField
	 * @param aipredictionfield
	 */
	public final void setAiPredictionField(java.lang.Boolean aipredictionfield)
	{
		setAiPredictionField(getContext(), aipredictionfield);
	}

	/**
	 * Set value of AiPredictionField
	 * @param context
	 * @param aipredictionfield
	 */
	public final void setAiPredictionField(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean aipredictionfield)
	{
		getMendixObject().setValue(context, MemberNames.AiPredictionField.toString(), aipredictionfield);
	}

	/**
	 * @return value of AutoNumber
	 */
	public final java.lang.Boolean getAutoNumber()
	{
		return getAutoNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNumber
	 */
	public final java.lang.Boolean getAutoNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AutoNumber.toString());
	}

	/**
	 * Set value of AutoNumber
	 * @param autonumber
	 */
	public final void setAutoNumber(java.lang.Boolean autonumber)
	{
		setAutoNumber(getContext(), autonumber);
	}

	/**
	 * Set value of AutoNumber
	 * @param context
	 * @param autonumber
	 */
	public final void setAutoNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean autonumber)
	{
		getMendixObject().setValue(context, MemberNames.AutoNumber.toString(), autonumber);
	}

	/**
	 * @return value of ByteLength
	 */
	public final java.lang.Integer getByteLength()
	{
		return getByteLength(getContext());
	}

	/**
	 * @param context
	 * @return value of ByteLength
	 */
	public final java.lang.Integer getByteLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ByteLength.toString());
	}

	/**
	 * Set value of ByteLength
	 * @param bytelength
	 */
	public final void setByteLength(java.lang.Integer bytelength)
	{
		setByteLength(getContext(), bytelength);
	}

	/**
	 * Set value of ByteLength
	 * @param context
	 * @param bytelength
	 */
	public final void setByteLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bytelength)
	{
		getMendixObject().setValue(context, MemberNames.ByteLength.toString(), bytelength);
	}

	/**
	 * @return value of Calculated
	 */
	public final java.lang.Boolean getCalculated()
	{
		return getCalculated(getContext());
	}

	/**
	 * @param context
	 * @return value of Calculated
	 */
	public final java.lang.Boolean getCalculated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Calculated.toString());
	}

	/**
	 * Set value of Calculated
	 * @param calculated
	 */
	public final void setCalculated(java.lang.Boolean calculated)
	{
		setCalculated(getContext(), calculated);
	}

	/**
	 * Set value of Calculated
	 * @param context
	 * @param calculated
	 */
	public final void setCalculated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean calculated)
	{
		getMendixObject().setValue(context, MemberNames.Calculated.toString(), calculated);
	}

	/**
	 * @return value of CascadeDelete
	 */
	public final java.lang.Boolean getCascadeDelete()
	{
		return getCascadeDelete(getContext());
	}

	/**
	 * @param context
	 * @return value of CascadeDelete
	 */
	public final java.lang.Boolean getCascadeDelete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CascadeDelete.toString());
	}

	/**
	 * Set value of CascadeDelete
	 * @param cascadedelete
	 */
	public final void setCascadeDelete(java.lang.Boolean cascadedelete)
	{
		setCascadeDelete(getContext(), cascadedelete);
	}

	/**
	 * Set value of CascadeDelete
	 * @param context
	 * @param cascadedelete
	 */
	public final void setCascadeDelete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cascadedelete)
	{
		getMendixObject().setValue(context, MemberNames.CascadeDelete.toString(), cascadedelete);
	}

	/**
	 * @return value of CaseSensitive
	 */
	public final java.lang.Boolean getCaseSensitive()
	{
		return getCaseSensitive(getContext());
	}

	/**
	 * @param context
	 * @return value of CaseSensitive
	 */
	public final java.lang.Boolean getCaseSensitive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CaseSensitive.toString());
	}

	/**
	 * Set value of CaseSensitive
	 * @param casesensitive
	 */
	public final void setCaseSensitive(java.lang.Boolean casesensitive)
	{
		setCaseSensitive(getContext(), casesensitive);
	}

	/**
	 * Set value of CaseSensitive
	 * @param context
	 * @param casesensitive
	 */
	public final void setCaseSensitive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean casesensitive)
	{
		getMendixObject().setValue(context, MemberNames.CaseSensitive.toString(), casesensitive);
	}

	/**
	 * @return value of Createable
	 */
	public final java.lang.Boolean getCreateable()
	{
		return getCreateable(getContext());
	}

	/**
	 * @param context
	 * @return value of Createable
	 */
	public final java.lang.Boolean getCreateable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Createable.toString());
	}

	/**
	 * Set value of Createable
	 * @param createable
	 */
	public final void setCreateable(java.lang.Boolean createable)
	{
		setCreateable(getContext(), createable);
	}

	/**
	 * Set value of Createable
	 * @param context
	 * @param createable
	 */
	public final void setCreateable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean createable)
	{
		getMendixObject().setValue(context, MemberNames.Createable.toString(), createable);
	}

	/**
	 * @return value of Custom
	 */
	public final java.lang.Boolean getCustom()
	{
		return getCustom(getContext());
	}

	/**
	 * @param context
	 * @return value of Custom
	 */
	public final java.lang.Boolean getCustom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Custom.toString());
	}

	/**
	 * Set value of Custom
	 * @param custom
	 */
	public final void setCustom(java.lang.Boolean custom)
	{
		setCustom(getContext(), custom);
	}

	/**
	 * Set value of Custom
	 * @param context
	 * @param custom
	 */
	public final void setCustom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean custom)
	{
		getMendixObject().setValue(context, MemberNames.Custom.toString(), custom);
	}

	/**
	 * @return value of DefaultedOnCreate
	 */
	public final java.lang.Boolean getDefaultedOnCreate()
	{
		return getDefaultedOnCreate(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultedOnCreate
	 */
	public final java.lang.Boolean getDefaultedOnCreate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DefaultedOnCreate.toString());
	}

	/**
	 * Set value of DefaultedOnCreate
	 * @param defaultedoncreate
	 */
	public final void setDefaultedOnCreate(java.lang.Boolean defaultedoncreate)
	{
		setDefaultedOnCreate(getContext(), defaultedoncreate);
	}

	/**
	 * Set value of DefaultedOnCreate
	 * @param context
	 * @param defaultedoncreate
	 */
	public final void setDefaultedOnCreate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean defaultedoncreate)
	{
		getMendixObject().setValue(context, MemberNames.DefaultedOnCreate.toString(), defaultedoncreate);
	}

	/**
	 * @return value of DependentPicklist
	 */
	public final java.lang.Boolean getDependentPicklist()
	{
		return getDependentPicklist(getContext());
	}

	/**
	 * @param context
	 * @return value of DependentPicklist
	 */
	public final java.lang.Boolean getDependentPicklist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DependentPicklist.toString());
	}

	/**
	 * Set value of DependentPicklist
	 * @param dependentpicklist
	 */
	public final void setDependentPicklist(java.lang.Boolean dependentpicklist)
	{
		setDependentPicklist(getContext(), dependentpicklist);
	}

	/**
	 * Set value of DependentPicklist
	 * @param context
	 * @param dependentpicklist
	 */
	public final void setDependentPicklist(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean dependentpicklist)
	{
		getMendixObject().setValue(context, MemberNames.DependentPicklist.toString(), dependentpicklist);
	}

	/**
	 * @return value of DeprecatedAndHidden
	 */
	public final java.lang.Boolean getDeprecatedAndHidden()
	{
		return getDeprecatedAndHidden(getContext());
	}

	/**
	 * @param context
	 * @return value of DeprecatedAndHidden
	 */
	public final java.lang.Boolean getDeprecatedAndHidden(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeprecatedAndHidden.toString());
	}

	/**
	 * Set value of DeprecatedAndHidden
	 * @param deprecatedandhidden
	 */
	public final void setDeprecatedAndHidden(java.lang.Boolean deprecatedandhidden)
	{
		setDeprecatedAndHidden(getContext(), deprecatedandhidden);
	}

	/**
	 * Set value of DeprecatedAndHidden
	 * @param context
	 * @param deprecatedandhidden
	 */
	public final void setDeprecatedAndHidden(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deprecatedandhidden)
	{
		getMendixObject().setValue(context, MemberNames.DeprecatedAndHidden.toString(), deprecatedandhidden);
	}

	/**
	 * @return value of Digits
	 */
	public final java.lang.Integer getDigits()
	{
		return getDigits(getContext());
	}

	/**
	 * @param context
	 * @return value of Digits
	 */
	public final java.lang.Integer getDigits(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Digits.toString());
	}

	/**
	 * Set value of Digits
	 * @param digits
	 */
	public final void setDigits(java.lang.Integer digits)
	{
		setDigits(getContext(), digits);
	}

	/**
	 * Set value of Digits
	 * @param context
	 * @param digits
	 */
	public final void setDigits(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer digits)
	{
		getMendixObject().setValue(context, MemberNames.Digits.toString(), digits);
	}

	/**
	 * @return value of DisplayLocationInDecimal
	 */
	public final java.lang.Boolean getDisplayLocationInDecimal()
	{
		return getDisplayLocationInDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayLocationInDecimal
	 */
	public final java.lang.Boolean getDisplayLocationInDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DisplayLocationInDecimal.toString());
	}

	/**
	 * Set value of DisplayLocationInDecimal
	 * @param displaylocationindecimal
	 */
	public final void setDisplayLocationInDecimal(java.lang.Boolean displaylocationindecimal)
	{
		setDisplayLocationInDecimal(getContext(), displaylocationindecimal);
	}

	/**
	 * Set value of DisplayLocationInDecimal
	 * @param context
	 * @param displaylocationindecimal
	 */
	public final void setDisplayLocationInDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean displaylocationindecimal)
	{
		getMendixObject().setValue(context, MemberNames.DisplayLocationInDecimal.toString(), displaylocationindecimal);
	}

	/**
	 * @return value of Encrypted
	 */
	public final java.lang.Boolean getEncrypted()
	{
		return getEncrypted(getContext());
	}

	/**
	 * @param context
	 * @return value of Encrypted
	 */
	public final java.lang.Boolean getEncrypted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Encrypted.toString());
	}

	/**
	 * Set value of Encrypted
	 * @param encrypted
	 */
	public final void setEncrypted(java.lang.Boolean encrypted)
	{
		setEncrypted(getContext(), encrypted);
	}

	/**
	 * Set value of Encrypted
	 * @param context
	 * @param encrypted
	 */
	public final void setEncrypted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean encrypted)
	{
		getMendixObject().setValue(context, MemberNames.Encrypted.toString(), encrypted);
	}

	/**
	 * @return value of ExternalId
	 */
	public final java.lang.Boolean getExternalId()
	{
		return getExternalId(getContext());
	}

	/**
	 * @param context
	 * @return value of ExternalId
	 */
	public final java.lang.Boolean getExternalId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExternalId.toString());
	}

	/**
	 * Set value of ExternalId
	 * @param externalid
	 */
	public final void setExternalId(java.lang.Boolean externalid)
	{
		setExternalId(getContext(), externalid);
	}

	/**
	 * Set value of ExternalId
	 * @param context
	 * @param externalid
	 */
	public final void setExternalId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean externalid)
	{
		getMendixObject().setValue(context, MemberNames.ExternalId.toString(), externalid);
	}

	/**
	 * @return value of Filterable
	 */
	public final java.lang.Boolean getFilterable()
	{
		return getFilterable(getContext());
	}

	/**
	 * @param context
	 * @return value of Filterable
	 */
	public final java.lang.Boolean getFilterable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Filterable.toString());
	}

	/**
	 * Set value of Filterable
	 * @param filterable
	 */
	public final void setFilterable(java.lang.Boolean filterable)
	{
		setFilterable(getContext(), filterable);
	}

	/**
	 * Set value of Filterable
	 * @param context
	 * @param filterable
	 */
	public final void setFilterable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean filterable)
	{
		getMendixObject().setValue(context, MemberNames.Filterable.toString(), filterable);
	}

	/**
	 * @return value of FormulaTreatNullNumberAsZero
	 */
	public final java.lang.Boolean getFormulaTreatNullNumberAsZero()
	{
		return getFormulaTreatNullNumberAsZero(getContext());
	}

	/**
	 * @param context
	 * @return value of FormulaTreatNullNumberAsZero
	 */
	public final java.lang.Boolean getFormulaTreatNullNumberAsZero(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FormulaTreatNullNumberAsZero.toString());
	}

	/**
	 * Set value of FormulaTreatNullNumberAsZero
	 * @param formulatreatnullnumberaszero
	 */
	public final void setFormulaTreatNullNumberAsZero(java.lang.Boolean formulatreatnullnumberaszero)
	{
		setFormulaTreatNullNumberAsZero(getContext(), formulatreatnullnumberaszero);
	}

	/**
	 * Set value of FormulaTreatNullNumberAsZero
	 * @param context
	 * @param formulatreatnullnumberaszero
	 */
	public final void setFormulaTreatNullNumberAsZero(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean formulatreatnullnumberaszero)
	{
		getMendixObject().setValue(context, MemberNames.FormulaTreatNullNumberAsZero.toString(), formulatreatnullnumberaszero);
	}

	/**
	 * @return value of Groupable
	 */
	public final java.lang.Boolean getGroupable()
	{
		return getGroupable(getContext());
	}

	/**
	 * @param context
	 * @return value of Groupable
	 */
	public final java.lang.Boolean getGroupable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Groupable.toString());
	}

	/**
	 * Set value of Groupable
	 * @param groupable
	 */
	public final void setGroupable(java.lang.Boolean groupable)
	{
		setGroupable(getContext(), groupable);
	}

	/**
	 * Set value of Groupable
	 * @param context
	 * @param groupable
	 */
	public final void setGroupable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean groupable)
	{
		getMendixObject().setValue(context, MemberNames.Groupable.toString(), groupable);
	}

	/**
	 * @return value of HighScaleNumber
	 */
	public final java.lang.Boolean getHighScaleNumber()
	{
		return getHighScaleNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of HighScaleNumber
	 */
	public final java.lang.Boolean getHighScaleNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HighScaleNumber.toString());
	}

	/**
	 * Set value of HighScaleNumber
	 * @param highscalenumber
	 */
	public final void setHighScaleNumber(java.lang.Boolean highscalenumber)
	{
		setHighScaleNumber(getContext(), highscalenumber);
	}

	/**
	 * Set value of HighScaleNumber
	 * @param context
	 * @param highscalenumber
	 */
	public final void setHighScaleNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean highscalenumber)
	{
		getMendixObject().setValue(context, MemberNames.HighScaleNumber.toString(), highscalenumber);
	}

	/**
	 * @return value of HtmlFormatted
	 */
	public final java.lang.Boolean getHtmlFormatted()
	{
		return getHtmlFormatted(getContext());
	}

	/**
	 * @param context
	 * @return value of HtmlFormatted
	 */
	public final java.lang.Boolean getHtmlFormatted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HtmlFormatted.toString());
	}

	/**
	 * Set value of HtmlFormatted
	 * @param htmlformatted
	 */
	public final void setHtmlFormatted(java.lang.Boolean htmlformatted)
	{
		setHtmlFormatted(getContext(), htmlformatted);
	}

	/**
	 * Set value of HtmlFormatted
	 * @param context
	 * @param htmlformatted
	 */
	public final void setHtmlFormatted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean htmlformatted)
	{
		getMendixObject().setValue(context, MemberNames.HtmlFormatted.toString(), htmlformatted);
	}

	/**
	 * @return value of IdLookup
	 */
	public final java.lang.Boolean getIdLookup()
	{
		return getIdLookup(getContext());
	}

	/**
	 * @param context
	 * @return value of IdLookup
	 */
	public final java.lang.Boolean getIdLookup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IdLookup.toString());
	}

	/**
	 * Set value of IdLookup
	 * @param idlookup
	 */
	public final void setIdLookup(java.lang.Boolean idlookup)
	{
		setIdLookup(getContext(), idlookup);
	}

	/**
	 * Set value of IdLookup
	 * @param context
	 * @param idlookup
	 */
	public final void setIdLookup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean idlookup)
	{
		getMendixObject().setValue(context, MemberNames.IdLookup.toString(), idlookup);
	}

	/**
	 * @return value of Label
	 */
	public final java.lang.String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final java.lang.String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(java.lang.String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of Length
	 */
	public final java.lang.Integer getLength()
	{
		return getLength(getContext());
	}

	/**
	 * @param context
	 * @return value of Length
	 */
	public final java.lang.Integer getLength(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Length.toString());
	}

	/**
	 * Set value of Length
	 * @param length
	 */
	public final void setLength(java.lang.Integer length)
	{
		setLength(getContext(), length);
	}

	/**
	 * Set value of Length
	 * @param context
	 * @param length
	 */
	public final void setLength(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer length)
	{
		getMendixObject().setValue(context, MemberNames.Length.toString(), length);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of NameField
	 */
	public final java.lang.Boolean getNameField()
	{
		return getNameField(getContext());
	}

	/**
	 * @param context
	 * @return value of NameField
	 */
	public final java.lang.Boolean getNameField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NameField.toString());
	}

	/**
	 * Set value of NameField
	 * @param namefield
	 */
	public final void setNameField(java.lang.Boolean namefield)
	{
		setNameField(getContext(), namefield);
	}

	/**
	 * Set value of NameField
	 * @param context
	 * @param namefield
	 */
	public final void setNameField(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean namefield)
	{
		getMendixObject().setValue(context, MemberNames.NameField.toString(), namefield);
	}

	/**
	 * @return value of NamePointing
	 */
	public final java.lang.Boolean getNamePointing()
	{
		return getNamePointing(getContext());
	}

	/**
	 * @param context
	 * @return value of NamePointing
	 */
	public final java.lang.Boolean getNamePointing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NamePointing.toString());
	}

	/**
	 * Set value of NamePointing
	 * @param namepointing
	 */
	public final void setNamePointing(java.lang.Boolean namepointing)
	{
		setNamePointing(getContext(), namepointing);
	}

	/**
	 * Set value of NamePointing
	 * @param context
	 * @param namepointing
	 */
	public final void setNamePointing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean namepointing)
	{
		getMendixObject().setValue(context, MemberNames.NamePointing.toString(), namepointing);
	}

	/**
	 * @return value of Nillable
	 */
	public final java.lang.Boolean getNillable()
	{
		return getNillable(getContext());
	}

	/**
	 * @param context
	 * @return value of Nillable
	 */
	public final java.lang.Boolean getNillable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Nillable.toString());
	}

	/**
	 * Set value of Nillable
	 * @param nillable
	 */
	public final void setNillable(java.lang.Boolean nillable)
	{
		setNillable(getContext(), nillable);
	}

	/**
	 * Set value of Nillable
	 * @param context
	 * @param nillable
	 */
	public final void setNillable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean nillable)
	{
		getMendixObject().setValue(context, MemberNames.Nillable.toString(), nillable);
	}

	/**
	 * @return value of Permissionable
	 */
	public final java.lang.Boolean getPermissionable()
	{
		return getPermissionable(getContext());
	}

	/**
	 * @param context
	 * @return value of Permissionable
	 */
	public final java.lang.Boolean getPermissionable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Permissionable.toString());
	}

	/**
	 * Set value of Permissionable
	 * @param permissionable
	 */
	public final void setPermissionable(java.lang.Boolean permissionable)
	{
		setPermissionable(getContext(), permissionable);
	}

	/**
	 * Set value of Permissionable
	 * @param context
	 * @param permissionable
	 */
	public final void setPermissionable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean permissionable)
	{
		getMendixObject().setValue(context, MemberNames.Permissionable.toString(), permissionable);
	}

	/**
	 * @return value of PolymorphicForeignKey
	 */
	public final java.lang.Boolean getPolymorphicForeignKey()
	{
		return getPolymorphicForeignKey(getContext());
	}

	/**
	 * @param context
	 * @return value of PolymorphicForeignKey
	 */
	public final java.lang.Boolean getPolymorphicForeignKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PolymorphicForeignKey.toString());
	}

	/**
	 * Set value of PolymorphicForeignKey
	 * @param polymorphicforeignkey
	 */
	public final void setPolymorphicForeignKey(java.lang.Boolean polymorphicforeignkey)
	{
		setPolymorphicForeignKey(getContext(), polymorphicforeignkey);
	}

	/**
	 * Set value of PolymorphicForeignKey
	 * @param context
	 * @param polymorphicforeignkey
	 */
	public final void setPolymorphicForeignKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean polymorphicforeignkey)
	{
		getMendixObject().setValue(context, MemberNames.PolymorphicForeignKey.toString(), polymorphicforeignkey);
	}

	/**
	 * @return value of Precision
	 */
	public final java.lang.Integer getPrecision()
	{
		return getPrecision(getContext());
	}

	/**
	 * @param context
	 * @return value of Precision
	 */
	public final java.lang.Integer getPrecision(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Precision.toString());
	}

	/**
	 * Set value of Precision
	 * @param precision
	 */
	public final void setPrecision(java.lang.Integer precision)
	{
		setPrecision(getContext(), precision);
	}

	/**
	 * Set value of Precision
	 * @param context
	 * @param precision
	 */
	public final void setPrecision(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer precision)
	{
		getMendixObject().setValue(context, MemberNames.Precision.toString(), precision);
	}

	/**
	 * @return value of QueryByDistance
	 */
	public final java.lang.Boolean getQueryByDistance()
	{
		return getQueryByDistance(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryByDistance
	 */
	public final java.lang.Boolean getQueryByDistance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.QueryByDistance.toString());
	}

	/**
	 * Set value of QueryByDistance
	 * @param querybydistance
	 */
	public final void setQueryByDistance(java.lang.Boolean querybydistance)
	{
		setQueryByDistance(getContext(), querybydistance);
	}

	/**
	 * Set value of QueryByDistance
	 * @param context
	 * @param querybydistance
	 */
	public final void setQueryByDistance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean querybydistance)
	{
		getMendixObject().setValue(context, MemberNames.QueryByDistance.toString(), querybydistance);
	}

	/**
	 * @return value of RestrictedDelete
	 */
	public final java.lang.Boolean getRestrictedDelete()
	{
		return getRestrictedDelete(getContext());
	}

	/**
	 * @param context
	 * @return value of RestrictedDelete
	 */
	public final java.lang.Boolean getRestrictedDelete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RestrictedDelete.toString());
	}

	/**
	 * Set value of RestrictedDelete
	 * @param restricteddelete
	 */
	public final void setRestrictedDelete(java.lang.Boolean restricteddelete)
	{
		setRestrictedDelete(getContext(), restricteddelete);
	}

	/**
	 * Set value of RestrictedDelete
	 * @param context
	 * @param restricteddelete
	 */
	public final void setRestrictedDelete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean restricteddelete)
	{
		getMendixObject().setValue(context, MemberNames.RestrictedDelete.toString(), restricteddelete);
	}

	/**
	 * @return value of RestrictedPicklist
	 */
	public final java.lang.Boolean getRestrictedPicklist()
	{
		return getRestrictedPicklist(getContext());
	}

	/**
	 * @param context
	 * @return value of RestrictedPicklist
	 */
	public final java.lang.Boolean getRestrictedPicklist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RestrictedPicklist.toString());
	}

	/**
	 * Set value of RestrictedPicklist
	 * @param restrictedpicklist
	 */
	public final void setRestrictedPicklist(java.lang.Boolean restrictedpicklist)
	{
		setRestrictedPicklist(getContext(), restrictedpicklist);
	}

	/**
	 * Set value of RestrictedPicklist
	 * @param context
	 * @param restrictedpicklist
	 */
	public final void setRestrictedPicklist(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean restrictedpicklist)
	{
		getMendixObject().setValue(context, MemberNames.RestrictedPicklist.toString(), restrictedpicklist);
	}

	/**
	 * @return value of Scale
	 */
	public final java.lang.Integer getScale()
	{
		return getScale(getContext());
	}

	/**
	 * @param context
	 * @return value of Scale
	 */
	public final java.lang.Integer getScale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Scale.toString());
	}

	/**
	 * Set value of Scale
	 * @param scale
	 */
	public final void setScale(java.lang.Integer scale)
	{
		setScale(getContext(), scale);
	}

	/**
	 * Set value of Scale
	 * @param context
	 * @param scale
	 */
	public final void setScale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer scale)
	{
		getMendixObject().setValue(context, MemberNames.Scale.toString(), scale);
	}

	/**
	 * @return value of SearchPrefilterable
	 */
	public final java.lang.Boolean getSearchPrefilterable()
	{
		return getSearchPrefilterable(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchPrefilterable
	 */
	public final java.lang.Boolean getSearchPrefilterable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SearchPrefilterable.toString());
	}

	/**
	 * Set value of SearchPrefilterable
	 * @param searchprefilterable
	 */
	public final void setSearchPrefilterable(java.lang.Boolean searchprefilterable)
	{
		setSearchPrefilterable(getContext(), searchprefilterable);
	}

	/**
	 * Set value of SearchPrefilterable
	 * @param context
	 * @param searchprefilterable
	 */
	public final void setSearchPrefilterable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean searchprefilterable)
	{
		getMendixObject().setValue(context, MemberNames.SearchPrefilterable.toString(), searchprefilterable);
	}

	/**
	 * @return value of SoapType
	 */
	public final java.lang.String getSoapType()
	{
		return getSoapType(getContext());
	}

	/**
	 * @param context
	 * @return value of SoapType
	 */
	public final java.lang.String getSoapType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SoapType.toString());
	}

	/**
	 * Set value of SoapType
	 * @param soaptype
	 */
	public final void setSoapType(java.lang.String soaptype)
	{
		setSoapType(getContext(), soaptype);
	}

	/**
	 * Set value of SoapType
	 * @param context
	 * @param soaptype
	 */
	public final void setSoapType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String soaptype)
	{
		getMendixObject().setValue(context, MemberNames.SoapType.toString(), soaptype);
	}

	/**
	 * @return value of Sortable
	 */
	public final java.lang.Boolean getSortable()
	{
		return getSortable(getContext());
	}

	/**
	 * @param context
	 * @return value of Sortable
	 */
	public final java.lang.Boolean getSortable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Sortable.toString());
	}

	/**
	 * Set value of Sortable
	 * @param sortable
	 */
	public final void setSortable(java.lang.Boolean sortable)
	{
		setSortable(getContext(), sortable);
	}

	/**
	 * Set value of Sortable
	 * @param context
	 * @param sortable
	 */
	public final void setSortable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sortable)
	{
		getMendixObject().setValue(context, MemberNames.Sortable.toString(), sortable);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Unique
	 */
	public final java.lang.Boolean getUnique()
	{
		return getUnique(getContext());
	}

	/**
	 * @param context
	 * @return value of Unique
	 */
	public final java.lang.Boolean getUnique(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Unique.toString());
	}

	/**
	 * Set value of Unique
	 * @param unique
	 */
	public final void setUnique(java.lang.Boolean unique)
	{
		setUnique(getContext(), unique);
	}

	/**
	 * Set value of Unique
	 * @param context
	 * @param unique
	 */
	public final void setUnique(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean unique)
	{
		getMendixObject().setValue(context, MemberNames.Unique.toString(), unique);
	}

	/**
	 * @return value of Updateable
	 */
	public final java.lang.Boolean getUpdateable()
	{
		return getUpdateable(getContext());
	}

	/**
	 * @param context
	 * @return value of Updateable
	 */
	public final java.lang.Boolean getUpdateable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Updateable.toString());
	}

	/**
	 * Set value of Updateable
	 * @param updateable
	 */
	public final void setUpdateable(java.lang.Boolean updateable)
	{
		setUpdateable(getContext(), updateable);
	}

	/**
	 * Set value of Updateable
	 * @param context
	 * @param updateable
	 */
	public final void setUpdateable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean updateable)
	{
		getMendixObject().setValue(context, MemberNames.Updateable.toString(), updateable);
	}

	/**
	 * @return value of WriteRequiresMasterRead
	 */
	public final java.lang.Boolean getWriteRequiresMasterRead()
	{
		return getWriteRequiresMasterRead(getContext());
	}

	/**
	 * @param context
	 * @return value of WriteRequiresMasterRead
	 */
	public final java.lang.Boolean getWriteRequiresMasterRead(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WriteRequiresMasterRead.toString());
	}

	/**
	 * Set value of WriteRequiresMasterRead
	 * @param writerequiresmasterread
	 */
	public final void setWriteRequiresMasterRead(java.lang.Boolean writerequiresmasterread)
	{
		setWriteRequiresMasterRead(getContext(), writerequiresmasterread);
	}

	/**
	 * Set value of WriteRequiresMasterRead
	 * @param context
	 * @param writerequiresmasterread
	 */
	public final void setWriteRequiresMasterRead(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean writerequiresmasterread)
	{
		getMendixObject().setValue(context, MemberNames.WriteRequiresMasterRead.toString(), writerequiresmasterread);
	}

	/**
	 * @return value of fields_SObject
	 */
	public final salesforce_connector.proxies.SObject getfields_SObject() throws com.mendix.core.CoreException
	{
		return getfields_SObject(getContext());
	}

	/**
	 * @param context
	 * @return value of fields_SObject
	 */
	public final salesforce_connector.proxies.SObject getfields_SObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.SObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.fields_SObject.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.SObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of fields_SObject
	 * @param fields_sobject
	 */
	public final void setfields_SObject(salesforce_connector.proxies.SObject fields_sobject)
	{
		setfields_SObject(getContext(), fields_sobject);
	}

	/**
	 * Set value of fields_SObject
	 * @param context
	 * @param fields_sobject
	 */
	public final void setfields_SObject(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.SObject fields_sobject)
	{
		if (fields_sobject == null)
			getMendixObject().setValue(context, MemberNames.fields_SObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.fields_SObject.toString(), fields_sobject.getMendixObject().getId());
	}

	/**
	 * @return value of PicklistValues_fields
	 */
	public final salesforce_connector.proxies.PicklistValues getPicklistValues_fields() throws com.mendix.core.CoreException
	{
		return getPicklistValues_fields(getContext());
	}

	/**
	 * @param context
	 * @return value of PicklistValues_fields
	 */
	public final salesforce_connector.proxies.PicklistValues getPicklistValues_fields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.PicklistValues result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PicklistValues_fields.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.PicklistValues.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PicklistValues_fields
	 * @param picklistvalues_fields
	 */
	public final void setPicklistValues_fields(salesforce_connector.proxies.PicklistValues picklistvalues_fields)
	{
		setPicklistValues_fields(getContext(), picklistvalues_fields);
	}

	/**
	 * Set value of PicklistValues_fields
	 * @param context
	 * @param picklistvalues_fields
	 */
	public final void setPicklistValues_fields(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.PicklistValues picklistvalues_fields)
	{
		if (picklistvalues_fields == null)
			getMendixObject().setValue(context, MemberNames.PicklistValues_fields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PicklistValues_fields.toString(), picklistvalues_fields.getMendixObject().getId());
	}

	/**
	 * @return value of ReferenceTo_fields
	 */
	public final salesforce_connector.proxies.ReferenceTo getReferenceTo_fields() throws com.mendix.core.CoreException
	{
		return getReferenceTo_fields(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceTo_fields
	 */
	public final salesforce_connector.proxies.ReferenceTo getReferenceTo_fields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.ReferenceTo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReferenceTo_fields.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.ReferenceTo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReferenceTo_fields
	 * @param referenceto_fields
	 */
	public final void setReferenceTo_fields(salesforce_connector.proxies.ReferenceTo referenceto_fields)
	{
		setReferenceTo_fields(getContext(), referenceto_fields);
	}

	/**
	 * Set value of ReferenceTo_fields
	 * @param context
	 * @param referenceto_fields
	 */
	public final void setReferenceTo_fields(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.ReferenceTo referenceto_fields)
	{
		if (referenceto_fields == null)
			getMendixObject().setValue(context, MemberNames.ReferenceTo_fields.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReferenceTo_fields.toString(), referenceto_fields.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fieldsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.fields that = (salesforce_connector.proxies.fields) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.fields";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
