// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Opportunity extends salesforce_connector.proxies.SObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Opportunity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsDeleted("IsDeleted"),
		AccountId("AccountId"),
		StageName("StageName"),
		CloseDate("CloseDate"),
		IsClosed("IsClosed"),
		IsWon("IsWon"),
		OwnerId("OwnerId"),
		Activateable("Activateable"),
		Createable("Createable"),
		Custom("Custom"),
		CustomSetting("CustomSetting"),
		Deletable("Deletable"),
		DeprecatedAndHidden("DeprecatedAndHidden"),
		FeedEnabled("FeedEnabled"),
		HasSubtypes("HasSubtypes"),
		IsSubtype("IsSubtype"),
		Label("Label"),
		LabelPlural("LabelPlural"),
		Layoutable("Layoutable"),
		Mergeable("Mergeable"),
		MruEnabled("MruEnabled"),
		SObjectName("SObjectName"),
		Queryable("Queryable"),
		Replicateable("Replicateable"),
		Retrieveable("Retrieveable"),
		Searchable("Searchable"),
		Triggerable("Triggerable"),
		Undeletable("Undeletable"),
		Updateable("Updateable"),
		KeyPrefix("KeyPrefix"),
		_Id("_Id"),
		Name("Name"),
		LastModifiedDate("LastModifiedDate"),
		LastModifiedById("LastModifiedById"),
		_CreatedDate("_CreatedDate"),
		CreatedById("CreatedById"),
		Opportunity_Records("Salesforce_Connector.Opportunity_Records"),
		Urls_SObject("Salesforce_Connector.Urls_SObject"),
		SObject_Query("Salesforce_Connector.SObject_Query"),
		Attributes_SObject("Salesforce_Connector.Attributes_SObject");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Opportunity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Opportunity"));
	}

	protected Opportunity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject opportunityMendixObject)
	{
		super(context, opportunityMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Opportunity", opportunityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Opportunity");
	}

	/**
	 * @deprecated Use 'Opportunity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Opportunity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Opportunity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Opportunity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Opportunity(context, mendixObject);
	}

	public static salesforce_connector.proxies.Opportunity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Opportunity.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted()
	{
		return getIsDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDeleted
	 */
	public final java.lang.Boolean getIsDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDeleted.toString());
	}

	/**
	 * Set value of IsDeleted
	 * @param isdeleted
	 */
	public final void setIsDeleted(java.lang.Boolean isdeleted)
	{
		setIsDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of IsDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setIsDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.IsDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of AccountId
	 */
	public final java.lang.String getAccountId()
	{
		return getAccountId(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountId
	 */
	public final java.lang.String getAccountId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountId.toString());
	}

	/**
	 * Set value of AccountId
	 * @param accountid
	 */
	public final void setAccountId(java.lang.String accountid)
	{
		setAccountId(getContext(), accountid);
	}

	/**
	 * Set value of AccountId
	 * @param context
	 * @param accountid
	 */
	public final void setAccountId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountid)
	{
		getMendixObject().setValue(context, MemberNames.AccountId.toString(), accountid);
	}

	/**
	 * @return value of StageName
	 */
	public final java.lang.String getStageName()
	{
		return getStageName(getContext());
	}

	/**
	 * @param context
	 * @return value of StageName
	 */
	public final java.lang.String getStageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StageName.toString());
	}

	/**
	 * Set value of StageName
	 * @param stagename
	 */
	public final void setStageName(java.lang.String stagename)
	{
		setStageName(getContext(), stagename);
	}

	/**
	 * Set value of StageName
	 * @param context
	 * @param stagename
	 */
	public final void setStageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stagename)
	{
		getMendixObject().setValue(context, MemberNames.StageName.toString(), stagename);
	}

	/**
	 * @return value of CloseDate
	 */
	public final java.util.Date getCloseDate()
	{
		return getCloseDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CloseDate
	 */
	public final java.util.Date getCloseDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CloseDate.toString());
	}

	/**
	 * Set value of CloseDate
	 * @param closedate
	 */
	public final void setCloseDate(java.util.Date closedate)
	{
		setCloseDate(getContext(), closedate);
	}

	/**
	 * Set value of CloseDate
	 * @param context
	 * @param closedate
	 */
	public final void setCloseDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date closedate)
	{
		getMendixObject().setValue(context, MemberNames.CloseDate.toString(), closedate);
	}

	/**
	 * @return value of IsClosed
	 */
	public final java.lang.Boolean getIsClosed()
	{
		return getIsClosed(getContext());
	}

	/**
	 * @param context
	 * @return value of IsClosed
	 */
	public final java.lang.Boolean getIsClosed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsClosed.toString());
	}

	/**
	 * Set value of IsClosed
	 * @param isclosed
	 */
	public final void setIsClosed(java.lang.Boolean isclosed)
	{
		setIsClosed(getContext(), isclosed);
	}

	/**
	 * Set value of IsClosed
	 * @param context
	 * @param isclosed
	 */
	public final void setIsClosed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isclosed)
	{
		getMendixObject().setValue(context, MemberNames.IsClosed.toString(), isclosed);
	}

	/**
	 * @return value of IsWon
	 */
	public final java.lang.Boolean getIsWon()
	{
		return getIsWon(getContext());
	}

	/**
	 * @param context
	 * @return value of IsWon
	 */
	public final java.lang.Boolean getIsWon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsWon.toString());
	}

	/**
	 * Set value of IsWon
	 * @param iswon
	 */
	public final void setIsWon(java.lang.Boolean iswon)
	{
		setIsWon(getContext(), iswon);
	}

	/**
	 * Set value of IsWon
	 * @param context
	 * @param iswon
	 */
	public final void setIsWon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iswon)
	{
		getMendixObject().setValue(context, MemberNames.IsWon.toString(), iswon);
	}

	/**
	 * @return value of OwnerId
	 */
	public final java.lang.String getOwnerId()
	{
		return getOwnerId(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerId
	 */
	public final java.lang.String getOwnerId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerId.toString());
	}

	/**
	 * Set value of OwnerId
	 * @param ownerid
	 */
	public final void setOwnerId(java.lang.String ownerid)
	{
		setOwnerId(getContext(), ownerid);
	}

	/**
	 * Set value of OwnerId
	 * @param context
	 * @param ownerid
	 */
	public final void setOwnerId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownerid)
	{
		getMendixObject().setValue(context, MemberNames.OwnerId.toString(), ownerid);
	}

	/**
	 * @return value of Opportunity_Records
	 */
	public final salesforce_connector.proxies.Records getOpportunity_Records() throws com.mendix.core.CoreException
	{
		return getOpportunity_Records(getContext());
	}

	/**
	 * @param context
	 * @return value of Opportunity_Records
	 */
	public final salesforce_connector.proxies.Records getOpportunity_Records(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.Records result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Opportunity_Records.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.Records.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Opportunity_Records
	 * @param opportunity_records
	 */
	public final void setOpportunity_Records(salesforce_connector.proxies.Records opportunity_records)
	{
		setOpportunity_Records(getContext(), opportunity_records);
	}

	/**
	 * Set value of Opportunity_Records
	 * @param context
	 * @param opportunity_records
	 */
	public final void setOpportunity_Records(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.Records opportunity_records)
	{
		if (opportunity_records == null)
			getMendixObject().setValue(context, MemberNames.Opportunity_Records.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Opportunity_Records.toString(), opportunity_records.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Opportunity that = (salesforce_connector.proxies.Opportunity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Opportunity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
