// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Resources
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject resourcesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Resources";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Tooling("Tooling"),
		Metadata("Metadata"),
		Eclair("Eclair"),
		Folders("Folders"),
		PrechatForms("PrechatForms"),
		Chatter("Chatter"),
		Tabs("Tabs"),
		AppMenu("AppMenu"),
		QuickActions("QuickActions"),
		QueryAll("QueryAll"),
		Wave("Wave"),
		Iot("Iot"),
		Analytics("Analytics"),
		Search("Search"),
		Smartdatadiscovery("Smartdatadiscovery"),
		Identity("Identity"),
		Composite("Composite"),
		ParameterizedSearch("ParameterizedSearch"),
		Fingerprint("Fingerprint"),
		Theme("Theme"),
		Nouns("Nouns"),
		Event("Event"),
		ServiceTemplates("ServiceTemplates"),
		Recent("Recent"),
		Connect("Connect"),
		Licensing("Licensing"),
		Limits("Limits"),
		Process("Process"),
		Dedupe("Dedupe"),
		Async_queries("Async_queries"),
		Query("Query"),
		Jobs("Jobs"),
		EmailConnect("EmailConnect"),
		Consent("Consent"),
		CompactLayouts("CompactLayouts"),
		KnowledgeManagement("KnowledgeManagement"),
		Sobjects("Sobjects"),
		Actions("Actions"),
		Support("Support");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Resources(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Resources"));
	}

	protected Resources(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resourcesMendixObject)
	{
		if (resourcesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Resources", resourcesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Resources");

		this.resourcesMendixObject = resourcesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Resources.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Resources initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Resources.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Resources initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Resources(context, mendixObject);
	}

	public static salesforce_connector.proxies.Resources load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Resources.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Tooling
	 */
	public final java.lang.String getTooling()
	{
		return getTooling(getContext());
	}

	/**
	 * @param context
	 * @return value of Tooling
	 */
	public final java.lang.String getTooling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tooling.toString());
	}

	/**
	 * Set value of Tooling
	 * @param tooling
	 */
	public final void setTooling(java.lang.String tooling)
	{
		setTooling(getContext(), tooling);
	}

	/**
	 * Set value of Tooling
	 * @param context
	 * @param tooling
	 */
	public final void setTooling(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tooling)
	{
		getMendixObject().setValue(context, MemberNames.Tooling.toString(), tooling);
	}

	/**
	 * @return value of Metadata
	 */
	public final java.lang.String getMetadata()
	{
		return getMetadata(getContext());
	}

	/**
	 * @param context
	 * @return value of Metadata
	 */
	public final java.lang.String getMetadata(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Metadata.toString());
	}

	/**
	 * Set value of Metadata
	 * @param metadata
	 */
	public final void setMetadata(java.lang.String metadata)
	{
		setMetadata(getContext(), metadata);
	}

	/**
	 * Set value of Metadata
	 * @param context
	 * @param metadata
	 */
	public final void setMetadata(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metadata)
	{
		getMendixObject().setValue(context, MemberNames.Metadata.toString(), metadata);
	}

	/**
	 * @return value of Eclair
	 */
	public final java.lang.String getEclair()
	{
		return getEclair(getContext());
	}

	/**
	 * @param context
	 * @return value of Eclair
	 */
	public final java.lang.String getEclair(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Eclair.toString());
	}

	/**
	 * Set value of Eclair
	 * @param eclair
	 */
	public final void setEclair(java.lang.String eclair)
	{
		setEclair(getContext(), eclair);
	}

	/**
	 * Set value of Eclair
	 * @param context
	 * @param eclair
	 */
	public final void setEclair(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String eclair)
	{
		getMendixObject().setValue(context, MemberNames.Eclair.toString(), eclair);
	}

	/**
	 * @return value of Folders
	 */
	public final java.lang.String getFolders()
	{
		return getFolders(getContext());
	}

	/**
	 * @param context
	 * @return value of Folders
	 */
	public final java.lang.String getFolders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Folders.toString());
	}

	/**
	 * Set value of Folders
	 * @param folders
	 */
	public final void setFolders(java.lang.String folders)
	{
		setFolders(getContext(), folders);
	}

	/**
	 * Set value of Folders
	 * @param context
	 * @param folders
	 */
	public final void setFolders(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String folders)
	{
		getMendixObject().setValue(context, MemberNames.Folders.toString(), folders);
	}

	/**
	 * @return value of PrechatForms
	 */
	public final java.lang.String getPrechatForms()
	{
		return getPrechatForms(getContext());
	}

	/**
	 * @param context
	 * @return value of PrechatForms
	 */
	public final java.lang.String getPrechatForms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PrechatForms.toString());
	}

	/**
	 * Set value of PrechatForms
	 * @param prechatforms
	 */
	public final void setPrechatForms(java.lang.String prechatforms)
	{
		setPrechatForms(getContext(), prechatforms);
	}

	/**
	 * Set value of PrechatForms
	 * @param context
	 * @param prechatforms
	 */
	public final void setPrechatForms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prechatforms)
	{
		getMendixObject().setValue(context, MemberNames.PrechatForms.toString(), prechatforms);
	}

	/**
	 * @return value of Chatter
	 */
	public final java.lang.String getChatter()
	{
		return getChatter(getContext());
	}

	/**
	 * @param context
	 * @return value of Chatter
	 */
	public final java.lang.String getChatter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Chatter.toString());
	}

	/**
	 * Set value of Chatter
	 * @param chatter
	 */
	public final void setChatter(java.lang.String chatter)
	{
		setChatter(getContext(), chatter);
	}

	/**
	 * Set value of Chatter
	 * @param context
	 * @param chatter
	 */
	public final void setChatter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String chatter)
	{
		getMendixObject().setValue(context, MemberNames.Chatter.toString(), chatter);
	}

	/**
	 * @return value of Tabs
	 */
	public final java.lang.String getTabs()
	{
		return getTabs(getContext());
	}

	/**
	 * @param context
	 * @return value of Tabs
	 */
	public final java.lang.String getTabs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tabs.toString());
	}

	/**
	 * Set value of Tabs
	 * @param tabs
	 */
	public final void setTabs(java.lang.String tabs)
	{
		setTabs(getContext(), tabs);
	}

	/**
	 * Set value of Tabs
	 * @param context
	 * @param tabs
	 */
	public final void setTabs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tabs)
	{
		getMendixObject().setValue(context, MemberNames.Tabs.toString(), tabs);
	}

	/**
	 * @return value of AppMenu
	 */
	public final java.lang.String getAppMenu()
	{
		return getAppMenu(getContext());
	}

	/**
	 * @param context
	 * @return value of AppMenu
	 */
	public final java.lang.String getAppMenu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AppMenu.toString());
	}

	/**
	 * Set value of AppMenu
	 * @param appmenu
	 */
	public final void setAppMenu(java.lang.String appmenu)
	{
		setAppMenu(getContext(), appmenu);
	}

	/**
	 * Set value of AppMenu
	 * @param context
	 * @param appmenu
	 */
	public final void setAppMenu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String appmenu)
	{
		getMendixObject().setValue(context, MemberNames.AppMenu.toString(), appmenu);
	}

	/**
	 * @return value of QuickActions
	 */
	public final java.lang.String getQuickActions()
	{
		return getQuickActions(getContext());
	}

	/**
	 * @param context
	 * @return value of QuickActions
	 */
	public final java.lang.String getQuickActions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuickActions.toString());
	}

	/**
	 * Set value of QuickActions
	 * @param quickactions
	 */
	public final void setQuickActions(java.lang.String quickactions)
	{
		setQuickActions(getContext(), quickactions);
	}

	/**
	 * Set value of QuickActions
	 * @param context
	 * @param quickactions
	 */
	public final void setQuickActions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quickactions)
	{
		getMendixObject().setValue(context, MemberNames.QuickActions.toString(), quickactions);
	}

	/**
	 * @return value of QueryAll
	 */
	public final java.lang.String getQueryAll()
	{
		return getQueryAll(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryAll
	 */
	public final java.lang.String getQueryAll(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QueryAll.toString());
	}

	/**
	 * Set value of QueryAll
	 * @param queryall
	 */
	public final void setQueryAll(java.lang.String queryall)
	{
		setQueryAll(getContext(), queryall);
	}

	/**
	 * Set value of QueryAll
	 * @param context
	 * @param queryall
	 */
	public final void setQueryAll(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String queryall)
	{
		getMendixObject().setValue(context, MemberNames.QueryAll.toString(), queryall);
	}

	/**
	 * @return value of Wave
	 */
	public final java.lang.String getWave()
	{
		return getWave(getContext());
	}

	/**
	 * @param context
	 * @return value of Wave
	 */
	public final java.lang.String getWave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wave.toString());
	}

	/**
	 * Set value of Wave
	 * @param wave
	 */
	public final void setWave(java.lang.String wave)
	{
		setWave(getContext(), wave);
	}

	/**
	 * Set value of Wave
	 * @param context
	 * @param wave
	 */
	public final void setWave(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wave)
	{
		getMendixObject().setValue(context, MemberNames.Wave.toString(), wave);
	}

	/**
	 * @return value of Iot
	 */
	public final java.lang.String getIot()
	{
		return getIot(getContext());
	}

	/**
	 * @param context
	 * @return value of Iot
	 */
	public final java.lang.String getIot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Iot.toString());
	}

	/**
	 * Set value of Iot
	 * @param iot
	 */
	public final void setIot(java.lang.String iot)
	{
		setIot(getContext(), iot);
	}

	/**
	 * Set value of Iot
	 * @param context
	 * @param iot
	 */
	public final void setIot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iot)
	{
		getMendixObject().setValue(context, MemberNames.Iot.toString(), iot);
	}

	/**
	 * @return value of Analytics
	 */
	public final java.lang.String getAnalytics()
	{
		return getAnalytics(getContext());
	}

	/**
	 * @param context
	 * @return value of Analytics
	 */
	public final java.lang.String getAnalytics(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Analytics.toString());
	}

	/**
	 * Set value of Analytics
	 * @param analytics
	 */
	public final void setAnalytics(java.lang.String analytics)
	{
		setAnalytics(getContext(), analytics);
	}

	/**
	 * Set value of Analytics
	 * @param context
	 * @param analytics
	 */
	public final void setAnalytics(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String analytics)
	{
		getMendixObject().setValue(context, MemberNames.Analytics.toString(), analytics);
	}

	/**
	 * @return value of Search
	 */
	public final java.lang.String getSearch()
	{
		return getSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of Search
	 */
	public final java.lang.String getSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Search.toString());
	}

	/**
	 * Set value of Search
	 * @param search
	 */
	public final void setSearch(java.lang.String search)
	{
		setSearch(getContext(), search);
	}

	/**
	 * Set value of Search
	 * @param context
	 * @param search
	 */
	public final void setSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String search)
	{
		getMendixObject().setValue(context, MemberNames.Search.toString(), search);
	}

	/**
	 * @return value of Smartdatadiscovery
	 */
	public final java.lang.String getSmartdatadiscovery()
	{
		return getSmartdatadiscovery(getContext());
	}

	/**
	 * @param context
	 * @return value of Smartdatadiscovery
	 */
	public final java.lang.String getSmartdatadiscovery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Smartdatadiscovery.toString());
	}

	/**
	 * Set value of Smartdatadiscovery
	 * @param smartdatadiscovery
	 */
	public final void setSmartdatadiscovery(java.lang.String smartdatadiscovery)
	{
		setSmartdatadiscovery(getContext(), smartdatadiscovery);
	}

	/**
	 * Set value of Smartdatadiscovery
	 * @param context
	 * @param smartdatadiscovery
	 */
	public final void setSmartdatadiscovery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String smartdatadiscovery)
	{
		getMendixObject().setValue(context, MemberNames.Smartdatadiscovery.toString(), smartdatadiscovery);
	}

	/**
	 * @return value of Identity
	 */
	public final java.lang.String getIdentity()
	{
		return getIdentity(getContext());
	}

	/**
	 * @param context
	 * @return value of Identity
	 */
	public final java.lang.String getIdentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Identity.toString());
	}

	/**
	 * Set value of Identity
	 * @param identity
	 */
	public final void setIdentity(java.lang.String identity)
	{
		setIdentity(getContext(), identity);
	}

	/**
	 * Set value of Identity
	 * @param context
	 * @param identity
	 */
	public final void setIdentity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identity)
	{
		getMendixObject().setValue(context, MemberNames.Identity.toString(), identity);
	}

	/**
	 * @return value of Composite
	 */
	public final java.lang.String getComposite()
	{
		return getComposite(getContext());
	}

	/**
	 * @param context
	 * @return value of Composite
	 */
	public final java.lang.String getComposite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Composite.toString());
	}

	/**
	 * Set value of Composite
	 * @param composite
	 */
	public final void setComposite(java.lang.String composite)
	{
		setComposite(getContext(), composite);
	}

	/**
	 * Set value of Composite
	 * @param context
	 * @param composite
	 */
	public final void setComposite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String composite)
	{
		getMendixObject().setValue(context, MemberNames.Composite.toString(), composite);
	}

	/**
	 * @return value of ParameterizedSearch
	 */
	public final java.lang.String getParameterizedSearch()
	{
		return getParameterizedSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterizedSearch
	 */
	public final java.lang.String getParameterizedSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParameterizedSearch.toString());
	}

	/**
	 * Set value of ParameterizedSearch
	 * @param parameterizedsearch
	 */
	public final void setParameterizedSearch(java.lang.String parameterizedsearch)
	{
		setParameterizedSearch(getContext(), parameterizedsearch);
	}

	/**
	 * Set value of ParameterizedSearch
	 * @param context
	 * @param parameterizedsearch
	 */
	public final void setParameterizedSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parameterizedsearch)
	{
		getMendixObject().setValue(context, MemberNames.ParameterizedSearch.toString(), parameterizedsearch);
	}

	/**
	 * @return value of Fingerprint
	 */
	public final java.lang.String getFingerprint()
	{
		return getFingerprint(getContext());
	}

	/**
	 * @param context
	 * @return value of Fingerprint
	 */
	public final java.lang.String getFingerprint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Fingerprint.toString());
	}

	/**
	 * Set value of Fingerprint
	 * @param fingerprint
	 */
	public final void setFingerprint(java.lang.String fingerprint)
	{
		setFingerprint(getContext(), fingerprint);
	}

	/**
	 * Set value of Fingerprint
	 * @param context
	 * @param fingerprint
	 */
	public final void setFingerprint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fingerprint)
	{
		getMendixObject().setValue(context, MemberNames.Fingerprint.toString(), fingerprint);
	}

	/**
	 * @return value of Theme
	 */
	public final java.lang.String getTheme()
	{
		return getTheme(getContext());
	}

	/**
	 * @param context
	 * @return value of Theme
	 */
	public final java.lang.String getTheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Theme.toString());
	}

	/**
	 * Set value of Theme
	 * @param theme
	 */
	public final void setTheme(java.lang.String theme)
	{
		setTheme(getContext(), theme);
	}

	/**
	 * Set value of Theme
	 * @param context
	 * @param theme
	 */
	public final void setTheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String theme)
	{
		getMendixObject().setValue(context, MemberNames.Theme.toString(), theme);
	}

	/**
	 * @return value of Nouns
	 */
	public final java.lang.String getNouns()
	{
		return getNouns(getContext());
	}

	/**
	 * @param context
	 * @return value of Nouns
	 */
	public final java.lang.String getNouns(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nouns.toString());
	}

	/**
	 * Set value of Nouns
	 * @param nouns
	 */
	public final void setNouns(java.lang.String nouns)
	{
		setNouns(getContext(), nouns);
	}

	/**
	 * Set value of Nouns
	 * @param context
	 * @param nouns
	 */
	public final void setNouns(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nouns)
	{
		getMendixObject().setValue(context, MemberNames.Nouns.toString(), nouns);
	}

	/**
	 * @return value of Event
	 */
	public final java.lang.String getEvent()
	{
		return getEvent(getContext());
	}

	/**
	 * @param context
	 * @return value of Event
	 */
	public final java.lang.String getEvent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Event.toString());
	}

	/**
	 * Set value of Event
	 * @param event
	 */
	public final void setEvent(java.lang.String event)
	{
		setEvent(getContext(), event);
	}

	/**
	 * Set value of Event
	 * @param context
	 * @param event
	 */
	public final void setEvent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String event)
	{
		getMendixObject().setValue(context, MemberNames.Event.toString(), event);
	}

	/**
	 * @return value of ServiceTemplates
	 */
	public final java.lang.String getServiceTemplates()
	{
		return getServiceTemplates(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceTemplates
	 */
	public final java.lang.String getServiceTemplates(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceTemplates.toString());
	}

	/**
	 * Set value of ServiceTemplates
	 * @param servicetemplates
	 */
	public final void setServiceTemplates(java.lang.String servicetemplates)
	{
		setServiceTemplates(getContext(), servicetemplates);
	}

	/**
	 * Set value of ServiceTemplates
	 * @param context
	 * @param servicetemplates
	 */
	public final void setServiceTemplates(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String servicetemplates)
	{
		getMendixObject().setValue(context, MemberNames.ServiceTemplates.toString(), servicetemplates);
	}

	/**
	 * @return value of Recent
	 */
	public final java.lang.String getRecent()
	{
		return getRecent(getContext());
	}

	/**
	 * @param context
	 * @return value of Recent
	 */
	public final java.lang.String getRecent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Recent.toString());
	}

	/**
	 * Set value of Recent
	 * @param recent
	 */
	public final void setRecent(java.lang.String recent)
	{
		setRecent(getContext(), recent);
	}

	/**
	 * Set value of Recent
	 * @param context
	 * @param recent
	 */
	public final void setRecent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recent)
	{
		getMendixObject().setValue(context, MemberNames.Recent.toString(), recent);
	}

	/**
	 * @return value of Connect
	 */
	public final java.lang.String getConnect()
	{
		return getConnect(getContext());
	}

	/**
	 * @param context
	 * @return value of Connect
	 */
	public final java.lang.String getConnect(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Connect.toString());
	}

	/**
	 * Set value of Connect
	 * @param connect
	 */
	public final void setConnect(java.lang.String connect)
	{
		setConnect(getContext(), connect);
	}

	/**
	 * Set value of Connect
	 * @param context
	 * @param connect
	 */
	public final void setConnect(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String connect)
	{
		getMendixObject().setValue(context, MemberNames.Connect.toString(), connect);
	}

	/**
	 * @return value of Licensing
	 */
	public final java.lang.String getLicensing()
	{
		return getLicensing(getContext());
	}

	/**
	 * @param context
	 * @return value of Licensing
	 */
	public final java.lang.String getLicensing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Licensing.toString());
	}

	/**
	 * Set value of Licensing
	 * @param licensing
	 */
	public final void setLicensing(java.lang.String licensing)
	{
		setLicensing(getContext(), licensing);
	}

	/**
	 * Set value of Licensing
	 * @param context
	 * @param licensing
	 */
	public final void setLicensing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String licensing)
	{
		getMendixObject().setValue(context, MemberNames.Licensing.toString(), licensing);
	}

	/**
	 * @return value of Limits
	 */
	public final java.lang.String getLimits()
	{
		return getLimits(getContext());
	}

	/**
	 * @param context
	 * @return value of Limits
	 */
	public final java.lang.String getLimits(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Limits.toString());
	}

	/**
	 * Set value of Limits
	 * @param limits
	 */
	public final void setLimits(java.lang.String limits)
	{
		setLimits(getContext(), limits);
	}

	/**
	 * Set value of Limits
	 * @param context
	 * @param limits
	 */
	public final void setLimits(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String limits)
	{
		getMendixObject().setValue(context, MemberNames.Limits.toString(), limits);
	}

	/**
	 * @return value of Process
	 */
	public final java.lang.String getProcess()
	{
		return getProcess(getContext());
	}

	/**
	 * @param context
	 * @return value of Process
	 */
	public final java.lang.String getProcess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Process.toString());
	}

	/**
	 * Set value of Process
	 * @param process
	 */
	public final void setProcess(java.lang.String process)
	{
		setProcess(getContext(), process);
	}

	/**
	 * Set value of Process
	 * @param context
	 * @param process
	 */
	public final void setProcess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String process)
	{
		getMendixObject().setValue(context, MemberNames.Process.toString(), process);
	}

	/**
	 * @return value of Dedupe
	 */
	public final java.lang.String getDedupe()
	{
		return getDedupe(getContext());
	}

	/**
	 * @param context
	 * @return value of Dedupe
	 */
	public final java.lang.String getDedupe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dedupe.toString());
	}

	/**
	 * Set value of Dedupe
	 * @param dedupe
	 */
	public final void setDedupe(java.lang.String dedupe)
	{
		setDedupe(getContext(), dedupe);
	}

	/**
	 * Set value of Dedupe
	 * @param context
	 * @param dedupe
	 */
	public final void setDedupe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dedupe)
	{
		getMendixObject().setValue(context, MemberNames.Dedupe.toString(), dedupe);
	}

	/**
	 * @return value of Async_queries
	 */
	public final java.lang.String getAsync_queries()
	{
		return getAsync_queries(getContext());
	}

	/**
	 * @param context
	 * @return value of Async_queries
	 */
	public final java.lang.String getAsync_queries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Async_queries.toString());
	}

	/**
	 * Set value of Async_queries
	 * @param async_queries
	 */
	public final void setAsync_queries(java.lang.String async_queries)
	{
		setAsync_queries(getContext(), async_queries);
	}

	/**
	 * Set value of Async_queries
	 * @param context
	 * @param async_queries
	 */
	public final void setAsync_queries(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String async_queries)
	{
		getMendixObject().setValue(context, MemberNames.Async_queries.toString(), async_queries);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Jobs
	 */
	public final java.lang.String getJobs()
	{
		return getJobs(getContext());
	}

	/**
	 * @param context
	 * @return value of Jobs
	 */
	public final java.lang.String getJobs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Jobs.toString());
	}

	/**
	 * Set value of Jobs
	 * @param jobs
	 */
	public final void setJobs(java.lang.String jobs)
	{
		setJobs(getContext(), jobs);
	}

	/**
	 * Set value of Jobs
	 * @param context
	 * @param jobs
	 */
	public final void setJobs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jobs)
	{
		getMendixObject().setValue(context, MemberNames.Jobs.toString(), jobs);
	}

	/**
	 * @return value of EmailConnect
	 */
	public final java.lang.String getEmailConnect()
	{
		return getEmailConnect(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailConnect
	 */
	public final java.lang.String getEmailConnect(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailConnect.toString());
	}

	/**
	 * Set value of EmailConnect
	 * @param emailconnect
	 */
	public final void setEmailConnect(java.lang.String emailconnect)
	{
		setEmailConnect(getContext(), emailconnect);
	}

	/**
	 * Set value of EmailConnect
	 * @param context
	 * @param emailconnect
	 */
	public final void setEmailConnect(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailconnect)
	{
		getMendixObject().setValue(context, MemberNames.EmailConnect.toString(), emailconnect);
	}

	/**
	 * @return value of Consent
	 */
	public final java.lang.String getConsent()
	{
		return getConsent(getContext());
	}

	/**
	 * @param context
	 * @return value of Consent
	 */
	public final java.lang.String getConsent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Consent.toString());
	}

	/**
	 * Set value of Consent
	 * @param consent
	 */
	public final void setConsent(java.lang.String consent)
	{
		setConsent(getContext(), consent);
	}

	/**
	 * Set value of Consent
	 * @param context
	 * @param consent
	 */
	public final void setConsent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String consent)
	{
		getMendixObject().setValue(context, MemberNames.Consent.toString(), consent);
	}

	/**
	 * @return value of CompactLayouts
	 */
	public final java.lang.String getCompactLayouts()
	{
		return getCompactLayouts(getContext());
	}

	/**
	 * @param context
	 * @return value of CompactLayouts
	 */
	public final java.lang.String getCompactLayouts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompactLayouts.toString());
	}

	/**
	 * Set value of CompactLayouts
	 * @param compactlayouts
	 */
	public final void setCompactLayouts(java.lang.String compactlayouts)
	{
		setCompactLayouts(getContext(), compactlayouts);
	}

	/**
	 * Set value of CompactLayouts
	 * @param context
	 * @param compactlayouts
	 */
	public final void setCompactLayouts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String compactlayouts)
	{
		getMendixObject().setValue(context, MemberNames.CompactLayouts.toString(), compactlayouts);
	}

	/**
	 * @return value of KnowledgeManagement
	 */
	public final java.lang.String getKnowledgeManagement()
	{
		return getKnowledgeManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of KnowledgeManagement
	 */
	public final java.lang.String getKnowledgeManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.KnowledgeManagement.toString());
	}

	/**
	 * Set value of KnowledgeManagement
	 * @param knowledgemanagement
	 */
	public final void setKnowledgeManagement(java.lang.String knowledgemanagement)
	{
		setKnowledgeManagement(getContext(), knowledgemanagement);
	}

	/**
	 * Set value of KnowledgeManagement
	 * @param context
	 * @param knowledgemanagement
	 */
	public final void setKnowledgeManagement(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String knowledgemanagement)
	{
		getMendixObject().setValue(context, MemberNames.KnowledgeManagement.toString(), knowledgemanagement);
	}

	/**
	 * @return value of Sobjects
	 */
	public final java.lang.String getSobjects()
	{
		return getSobjects(getContext());
	}

	/**
	 * @param context
	 * @return value of Sobjects
	 */
	public final java.lang.String getSobjects(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sobjects.toString());
	}

	/**
	 * Set value of Sobjects
	 * @param sobjects
	 */
	public final void setSobjects(java.lang.String sobjects)
	{
		setSobjects(getContext(), sobjects);
	}

	/**
	 * Set value of Sobjects
	 * @param context
	 * @param sobjects
	 */
	public final void setSobjects(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sobjects)
	{
		getMendixObject().setValue(context, MemberNames.Sobjects.toString(), sobjects);
	}

	/**
	 * @return value of Actions
	 */
	public final java.lang.String getActions()
	{
		return getActions(getContext());
	}

	/**
	 * @param context
	 * @return value of Actions
	 */
	public final java.lang.String getActions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Actions.toString());
	}

	/**
	 * Set value of Actions
	 * @param actions
	 */
	public final void setActions(java.lang.String actions)
	{
		setActions(getContext(), actions);
	}

	/**
	 * Set value of Actions
	 * @param context
	 * @param actions
	 */
	public final void setActions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actions)
	{
		getMendixObject().setValue(context, MemberNames.Actions.toString(), actions);
	}

	/**
	 * @return value of Support
	 */
	public final java.lang.String getSupport()
	{
		return getSupport(getContext());
	}

	/**
	 * @param context
	 * @return value of Support
	 */
	public final java.lang.String getSupport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Support.toString());
	}

	/**
	 * Set value of Support
	 * @param support
	 */
	public final void setSupport(java.lang.String support)
	{
		setSupport(getContext(), support);
	}

	/**
	 * Set value of Support
	 * @param context
	 * @param support
	 */
	public final void setSupport(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String support)
	{
		getMendixObject().setValue(context, MemberNames.Support.toString(), support);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return resourcesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Resources that = (salesforce_connector.proxies.Resources) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Resources";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
