// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesforce_connector.proxies;

public class Urls
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject urlsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Salesforce_Connector.Urls";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RowTemplate("RowTemplate"),
		DefaultValues("DefaultValues"),
		Describe("Describe"),
		Sobject("Sobject"),
		CompactLayouts("CompactLayouts"),
		ApprovalLayouts("ApprovalLayouts"),
		Listviews("Listviews"),
		QuickActions("QuickActions"),
		Layouts("Layouts"),
		UiDetailTemplate("UiDetailTemplate"),
		UiEditTemplate("UiEditTemplate"),
		UiNewRecord("UiNewRecord"),
		QuickAction("QuickAction"),
		DefaultValuesTemplate("DefaultValuesTemplate"),
		Urls_SObject("Salesforce_Connector.Urls_SObject"),
		Urls_recordTypeInfos("Salesforce_Connector.Urls_recordTypeInfos"),
		Urls_QuickAction("Salesforce_Connector.Urls_QuickAction");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Urls(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Salesforce_Connector.Urls"));
	}

	protected Urls(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject urlsMendixObject)
	{
		if (urlsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Salesforce_Connector.Urls", urlsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Salesforce_Connector.Urls");

		this.urlsMendixObject = urlsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Urls.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesforce_connector.proxies.Urls initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesforce_connector.proxies.Urls.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesforce_connector.proxies.Urls initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesforce_connector.proxies.Urls(context, mendixObject);
	}

	public static salesforce_connector.proxies.Urls load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesforce_connector.proxies.Urls.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RowTemplate
	 */
	public final java.lang.String getRowTemplate()
	{
		return getRowTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of RowTemplate
	 */
	public final java.lang.String getRowTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RowTemplate.toString());
	}

	/**
	 * Set value of RowTemplate
	 * @param rowtemplate
	 */
	public final void setRowTemplate(java.lang.String rowtemplate)
	{
		setRowTemplate(getContext(), rowtemplate);
	}

	/**
	 * Set value of RowTemplate
	 * @param context
	 * @param rowtemplate
	 */
	public final void setRowTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rowtemplate)
	{
		getMendixObject().setValue(context, MemberNames.RowTemplate.toString(), rowtemplate);
	}

	/**
	 * @return value of DefaultValues
	 */
	public final java.lang.String getDefaultValues()
	{
		return getDefaultValues(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultValues
	 */
	public final java.lang.String getDefaultValues(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DefaultValues.toString());
	}

	/**
	 * Set value of DefaultValues
	 * @param defaultvalues
	 */
	public final void setDefaultValues(java.lang.String defaultvalues)
	{
		setDefaultValues(getContext(), defaultvalues);
	}

	/**
	 * Set value of DefaultValues
	 * @param context
	 * @param defaultvalues
	 */
	public final void setDefaultValues(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String defaultvalues)
	{
		getMendixObject().setValue(context, MemberNames.DefaultValues.toString(), defaultvalues);
	}

	/**
	 * @return value of Describe
	 */
	public final java.lang.String getDescribe()
	{
		return getDescribe(getContext());
	}

	/**
	 * @param context
	 * @return value of Describe
	 */
	public final java.lang.String getDescribe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Describe.toString());
	}

	/**
	 * Set value of Describe
	 * @param describe
	 */
	public final void setDescribe(java.lang.String describe)
	{
		setDescribe(getContext(), describe);
	}

	/**
	 * Set value of Describe
	 * @param context
	 * @param describe
	 */
	public final void setDescribe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String describe)
	{
		getMendixObject().setValue(context, MemberNames.Describe.toString(), describe);
	}

	/**
	 * @return value of Sobject
	 */
	public final java.lang.String getSobject()
	{
		return getSobject(getContext());
	}

	/**
	 * @param context
	 * @return value of Sobject
	 */
	public final java.lang.String getSobject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sobject.toString());
	}

	/**
	 * Set value of Sobject
	 * @param sobject
	 */
	public final void setSobject(java.lang.String sobject)
	{
		setSobject(getContext(), sobject);
	}

	/**
	 * Set value of Sobject
	 * @param context
	 * @param sobject
	 */
	public final void setSobject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sobject)
	{
		getMendixObject().setValue(context, MemberNames.Sobject.toString(), sobject);
	}

	/**
	 * @return value of CompactLayouts
	 */
	public final java.lang.String getCompactLayouts()
	{
		return getCompactLayouts(getContext());
	}

	/**
	 * @param context
	 * @return value of CompactLayouts
	 */
	public final java.lang.String getCompactLayouts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CompactLayouts.toString());
	}

	/**
	 * Set value of CompactLayouts
	 * @param compactlayouts
	 */
	public final void setCompactLayouts(java.lang.String compactlayouts)
	{
		setCompactLayouts(getContext(), compactlayouts);
	}

	/**
	 * Set value of CompactLayouts
	 * @param context
	 * @param compactlayouts
	 */
	public final void setCompactLayouts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String compactlayouts)
	{
		getMendixObject().setValue(context, MemberNames.CompactLayouts.toString(), compactlayouts);
	}

	/**
	 * @return value of ApprovalLayouts
	 */
	public final java.lang.String getApprovalLayouts()
	{
		return getApprovalLayouts(getContext());
	}

	/**
	 * @param context
	 * @return value of ApprovalLayouts
	 */
	public final java.lang.String getApprovalLayouts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApprovalLayouts.toString());
	}

	/**
	 * Set value of ApprovalLayouts
	 * @param approvallayouts
	 */
	public final void setApprovalLayouts(java.lang.String approvallayouts)
	{
		setApprovalLayouts(getContext(), approvallayouts);
	}

	/**
	 * Set value of ApprovalLayouts
	 * @param context
	 * @param approvallayouts
	 */
	public final void setApprovalLayouts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String approvallayouts)
	{
		getMendixObject().setValue(context, MemberNames.ApprovalLayouts.toString(), approvallayouts);
	}

	/**
	 * @return value of Listviews
	 */
	public final java.lang.String getListviews()
	{
		return getListviews(getContext());
	}

	/**
	 * @param context
	 * @return value of Listviews
	 */
	public final java.lang.String getListviews(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Listviews.toString());
	}

	/**
	 * Set value of Listviews
	 * @param listviews
	 */
	public final void setListviews(java.lang.String listviews)
	{
		setListviews(getContext(), listviews);
	}

	/**
	 * Set value of Listviews
	 * @param context
	 * @param listviews
	 */
	public final void setListviews(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String listviews)
	{
		getMendixObject().setValue(context, MemberNames.Listviews.toString(), listviews);
	}

	/**
	 * @return value of QuickActions
	 */
	public final java.lang.String getQuickActions()
	{
		return getQuickActions(getContext());
	}

	/**
	 * @param context
	 * @return value of QuickActions
	 */
	public final java.lang.String getQuickActions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuickActions.toString());
	}

	/**
	 * Set value of QuickActions
	 * @param quickactions
	 */
	public final void setQuickActions(java.lang.String quickactions)
	{
		setQuickActions(getContext(), quickactions);
	}

	/**
	 * Set value of QuickActions
	 * @param context
	 * @param quickactions
	 */
	public final void setQuickActions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quickactions)
	{
		getMendixObject().setValue(context, MemberNames.QuickActions.toString(), quickactions);
	}

	/**
	 * @return value of Layouts
	 */
	public final java.lang.String getLayouts()
	{
		return getLayouts(getContext());
	}

	/**
	 * @param context
	 * @return value of Layouts
	 */
	public final java.lang.String getLayouts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Layouts.toString());
	}

	/**
	 * Set value of Layouts
	 * @param layouts
	 */
	public final void setLayouts(java.lang.String layouts)
	{
		setLayouts(getContext(), layouts);
	}

	/**
	 * Set value of Layouts
	 * @param context
	 * @param layouts
	 */
	public final void setLayouts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String layouts)
	{
		getMendixObject().setValue(context, MemberNames.Layouts.toString(), layouts);
	}

	/**
	 * @return value of UiDetailTemplate
	 */
	public final java.lang.String getUiDetailTemplate()
	{
		return getUiDetailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of UiDetailTemplate
	 */
	public final java.lang.String getUiDetailTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UiDetailTemplate.toString());
	}

	/**
	 * Set value of UiDetailTemplate
	 * @param uidetailtemplate
	 */
	public final void setUiDetailTemplate(java.lang.String uidetailtemplate)
	{
		setUiDetailTemplate(getContext(), uidetailtemplate);
	}

	/**
	 * Set value of UiDetailTemplate
	 * @param context
	 * @param uidetailtemplate
	 */
	public final void setUiDetailTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uidetailtemplate)
	{
		getMendixObject().setValue(context, MemberNames.UiDetailTemplate.toString(), uidetailtemplate);
	}

	/**
	 * @return value of UiEditTemplate
	 */
	public final java.lang.String getUiEditTemplate()
	{
		return getUiEditTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of UiEditTemplate
	 */
	public final java.lang.String getUiEditTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UiEditTemplate.toString());
	}

	/**
	 * Set value of UiEditTemplate
	 * @param uiedittemplate
	 */
	public final void setUiEditTemplate(java.lang.String uiedittemplate)
	{
		setUiEditTemplate(getContext(), uiedittemplate);
	}

	/**
	 * Set value of UiEditTemplate
	 * @param context
	 * @param uiedittemplate
	 */
	public final void setUiEditTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uiedittemplate)
	{
		getMendixObject().setValue(context, MemberNames.UiEditTemplate.toString(), uiedittemplate);
	}

	/**
	 * @return value of UiNewRecord
	 */
	public final java.lang.String getUiNewRecord()
	{
		return getUiNewRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of UiNewRecord
	 */
	public final java.lang.String getUiNewRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UiNewRecord.toString());
	}

	/**
	 * Set value of UiNewRecord
	 * @param uinewrecord
	 */
	public final void setUiNewRecord(java.lang.String uinewrecord)
	{
		setUiNewRecord(getContext(), uinewrecord);
	}

	/**
	 * Set value of UiNewRecord
	 * @param context
	 * @param uinewrecord
	 */
	public final void setUiNewRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uinewrecord)
	{
		getMendixObject().setValue(context, MemberNames.UiNewRecord.toString(), uinewrecord);
	}

	/**
	 * @return value of QuickAction
	 */
	public final java.lang.String getQuickAction()
	{
		return getQuickAction(getContext());
	}

	/**
	 * @param context
	 * @return value of QuickAction
	 */
	public final java.lang.String getQuickAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QuickAction.toString());
	}

	/**
	 * Set value of QuickAction
	 * @param quickaction
	 */
	public final void setQuickAction(java.lang.String quickaction)
	{
		setQuickAction(getContext(), quickaction);
	}

	/**
	 * Set value of QuickAction
	 * @param context
	 * @param quickaction
	 */
	public final void setQuickAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quickaction)
	{
		getMendixObject().setValue(context, MemberNames.QuickAction.toString(), quickaction);
	}

	/**
	 * @return value of DefaultValuesTemplate
	 */
	public final java.lang.String getDefaultValuesTemplate()
	{
		return getDefaultValuesTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultValuesTemplate
	 */
	public final java.lang.String getDefaultValuesTemplate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DefaultValuesTemplate.toString());
	}

	/**
	 * Set value of DefaultValuesTemplate
	 * @param defaultvaluestemplate
	 */
	public final void setDefaultValuesTemplate(java.lang.String defaultvaluestemplate)
	{
		setDefaultValuesTemplate(getContext(), defaultvaluestemplate);
	}

	/**
	 * Set value of DefaultValuesTemplate
	 * @param context
	 * @param defaultvaluestemplate
	 */
	public final void setDefaultValuesTemplate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String defaultvaluestemplate)
	{
		getMendixObject().setValue(context, MemberNames.DefaultValuesTemplate.toString(), defaultvaluestemplate);
	}

	/**
	 * @return value of Urls_SObject
	 */
	public final salesforce_connector.proxies.SObject getUrls_SObject() throws com.mendix.core.CoreException
	{
		return getUrls_SObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Urls_SObject
	 */
	public final salesforce_connector.proxies.SObject getUrls_SObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.SObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Urls_SObject.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.SObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Urls_SObject
	 * @param urls_sobject
	 */
	public final void setUrls_SObject(salesforce_connector.proxies.SObject urls_sobject)
	{
		setUrls_SObject(getContext(), urls_sobject);
	}

	/**
	 * Set value of Urls_SObject
	 * @param context
	 * @param urls_sobject
	 */
	public final void setUrls_SObject(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.SObject urls_sobject)
	{
		if (urls_sobject == null)
			getMendixObject().setValue(context, MemberNames.Urls_SObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Urls_SObject.toString(), urls_sobject.getMendixObject().getId());
	}

	/**
	 * @return value of Urls_recordTypeInfos
	 */
	public final salesforce_connector.proxies.recordTypeInfos getUrls_recordTypeInfos() throws com.mendix.core.CoreException
	{
		return getUrls_recordTypeInfos(getContext());
	}

	/**
	 * @param context
	 * @return value of Urls_recordTypeInfos
	 */
	public final salesforce_connector.proxies.recordTypeInfos getUrls_recordTypeInfos(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.recordTypeInfos result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Urls_recordTypeInfos.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.recordTypeInfos.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Urls_recordTypeInfos
	 * @param urls_recordtypeinfos
	 */
	public final void setUrls_recordTypeInfos(salesforce_connector.proxies.recordTypeInfos urls_recordtypeinfos)
	{
		setUrls_recordTypeInfos(getContext(), urls_recordtypeinfos);
	}

	/**
	 * Set value of Urls_recordTypeInfos
	 * @param context
	 * @param urls_recordtypeinfos
	 */
	public final void setUrls_recordTypeInfos(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.recordTypeInfos urls_recordtypeinfos)
	{
		if (urls_recordtypeinfos == null)
			getMendixObject().setValue(context, MemberNames.Urls_recordTypeInfos.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Urls_recordTypeInfos.toString(), urls_recordtypeinfos.getMendixObject().getId());
	}

	/**
	 * @return value of Urls_QuickAction
	 */
	public final salesforce_connector.proxies.QuickAction getUrls_QuickAction() throws com.mendix.core.CoreException
	{
		return getUrls_QuickAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Urls_QuickAction
	 */
	public final salesforce_connector.proxies.QuickAction getUrls_QuickAction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesforce_connector.proxies.QuickAction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Urls_QuickAction.toString());
		if (identifier != null)
			result = salesforce_connector.proxies.QuickAction.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Urls_QuickAction
	 * @param urls_quickaction
	 */
	public final void setUrls_QuickAction(salesforce_connector.proxies.QuickAction urls_quickaction)
	{
		setUrls_QuickAction(getContext(), urls_quickaction);
	}

	/**
	 * Set value of Urls_QuickAction
	 * @param context
	 * @param urls_quickaction
	 */
	public final void setUrls_QuickAction(com.mendix.systemwideinterfaces.core.IContext context, salesforce_connector.proxies.QuickAction urls_quickaction)
	{
		if (urls_quickaction == null)
			getMendixObject().setValue(context, MemberNames.Urls_QuickAction.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Urls_QuickAction.toString(), urls_quickaction.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return urlsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesforce_connector.proxies.Urls that = (salesforce_connector.proxies.Urls) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Salesforce_Connector.Urls";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
